[package]
name = "ts_checker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ts_ast = { path = "../ts_ast" }
ts_binder = { path = "../ts_binder" }
ts_diagnostics = { path = "../ts_diagnostics" }

[dev-dependencies]
ts_core = { path = "../ts_core" }

[lints]
workspace = true
