//! Go `internal/project/project_stringer_generated.go`.
//! Code generated by "stringer -type=Kind -trimprefix=Kind -output=project_stringer_generated.go"; DO NOT EDIT.

use crate::project::prelude::*;

// Go: project/project_stringer_generated.go:7 _
// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
// PORT: the Go array-index check is a const assertion.
const _: () = {
    assert!(Kind::INFERRED.0 == 0);
    assert!(Kind::CONFIGURED.0 == 1);
};

// Go: project/project_stringer_generated.go:15 _Kind_name
const _KIND_NAME: &str = "InferredConfigured";

// Go: project/project_stringer_generated.go:17 _Kind_index
const _KIND_INDEX: [u8; 3] = [0, 8, 18];

impl Kind {
    // Go: project/project_stringer_generated.go:19 Kind.String
    pub fn string(&self) -> String {
        let i = self.0;
        let idx = i64::from(i); // Go: int(i) - 0
        if i < 0 || idx >= (_KIND_INDEX.len() - 1) as i64 {
            return format!("Kind({})", i64::from(i));
        }
        let idx = idx as usize;
        _KIND_NAME[_KIND_INDEX[idx] as usize.._KIND_INDEX[idx + 1] as usize].to_string()
    }
}
