#!/usr/bin/env python3
"""Generate crates/ts_goport/src/scanner_util/js_case_tables.rs from Go's
internal/stringutil/js_case_generated.go.

Usage: gen-js-case-tables.py <js_case_generated.go> [out.rs]

Go's `specialCasingMappings` maps 2,927 code points to their lower and upper
case strings (`ToLowerJS`, `ToUpperJS`). As 2,927 tuples of strings it was
about 100 KB of the wasm module. The port keeps the same data in about 8 KB:

- CASE_RANGES: the entries that map one code point to one code point both
  ways, as runs of code points with the same deltas, and as runs that
  alternate upper and lower case (Go's `unicode.UpperLower` ranges).
- SPECIAL_CASE_MAPPINGS: the other entries, with their strings.
- FINAL_SIGMA: the one entry with a conditional lower case (Final_Sigma).

The script checks that the tables give back each Go entry. Run it again when
the Go file changes (new Unicode data at a pin bump).
"""
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
OUT = pathlib.Path(sys.argv[2] if len(sys.argv) > 2 else HERE / "../src/scanner_util/js_case_tables.rs").resolve()
UPPER_LOWER = "UPPER_LOWER"

go = pathlib.Path(sys.argv[1]).read_text()
version = re.search(r"\(Unicode ([0-9.]+)\)", go).group(1)
body = go[go.index("var specialCasingMappings") :]
body = body[: body.index("\n}")]


def runes(text):
    return [int(h, 16) for h in re.findall(r"\\[uU]([0-9A-Fa-f]+)", text)]


entries = {}
for m in re.finditer(r"(0x[0-9A-Fa-f]+):\s*\{([^}]*)\}", body):
    fields = dict(re.findall(r'(\w+):\s*("[^"]*"|\w+)', m.group(2)))
    entries[int(m.group(1), 16)] = (
        runes(fields["lower"]),
        runes(fields["upper"]),
        runes(fields.get("conditionalLower", '""')),
        fields["condition"],
    )
assert len(entries) == body.count("condition:"), "an entry did not parse"

# The one conditional entry: Σ lowers to ς in Final_Sigma context.
conditional = [c for c, e in entries.items() if e[3] != "specialCasingConditionNone"]
assert len(conditional) == 1, conditional
sigma = conditional[0]
assert entries[sigma][3] == "specialCasingConditionFinalSigma"
assert len(entries[sigma][2]) == 1
final_sigma = (sigma, entries[sigma][2][0])

deltas = {}
special = []
for code, (lower, upper, _, _) in sorted(entries.items()):
    if len(lower) == 1 and len(upper) == 1:
        deltas[code] = (lower[0] - code, upper[0] - code)
    else:
        special.append((code, lower, upper))

# Runs of consecutive code points. An alternating run starts with an upper
# case letter: even offsets map down one code point, odd offsets up one.
ranges = []
codes = sorted(deltas)
i = 0
while i < len(codes):
    lo = hi = codes[i]
    while deltas.get(hi + 1) == ((0, -1) if (hi + 1 - lo) % 2 else (1, 0)):
        hi += 1
    if deltas[lo] == (1, 0) and hi > lo:
        ranges.append((lo, hi, UPPER_LOWER, UPPER_LOWER))
    else:
        hi = lo
        while deltas.get(hi + 1) == deltas[lo]:
            hi += 1
        ranges.append((lo, hi, *deltas[lo]))
    i += hi - lo + 1

# The tables give back every entry.
back = {}
for lo, hi, lower, upper in ranges:
    for code in range(lo, hi + 1):
        if lower == UPPER_LOWER:
            back[code] = (lo + ((code - lo) | 1) - code, lo + ((code - lo) & ~1) - code)
        else:
            back[code] = (lower, upper)
assert back == deltas
assert all(abs(d) < 2**31 - 1 for pair in deltas.values() for d in pair)


def rust_str(rs):
    return '"' + "".join(f"\\u{{{r:X}}}" for r in rs) + '"'


out = [
    "//! Code generated by `crates/ts_goport/scripts/gen-js-case-tables.py` from",
    f"//! Go stringutil/js_case_generated.go (Unicode {version}). DO NOT EDIT.",
    "//!",
    "//! Go `specialCasingMappings` in less space. `special_casing_mapping` in",
    "//! scanner_util.rs reads these tables.",
    "",
    "/// The deltas of a `CASE_RANGES` run that alternates upper and lower case",
    "/// (Go `unicode.UpperLower`): even offsets from `lo` are upper case and",
    "/// lower to the next code point, odd offsets are lower case and upper to",
    "/// the previous one.",
    "pub(super) const UPPER_LOWER: i32 = i32::MAX;",
    "",
    "/// The entries that map one code point to one code point both ways, as",
    "/// sorted runs `(lo, hi, lower, upper)`: each code point `r` in `lo..=hi`",
    "/// lowers to `r + lower` and uppers to `r + upper`.",
    f"/// {len(deltas):,} entries in {len(ranges)} runs.",
    "pub(super) static CASE_RANGES: &[(u32, u32, i32, i32)] = &[",
]
out += [f"    (0x{lo:X}, 0x{hi:X}, {lower}, {upper})," for lo, hi, lower, upper in ranges]
out += [
    "];",
    "",
    "/// The other entries, sorted: `(code point, lower, upper)`.",
    "pub(super) static SPECIAL_CASE_MAPPINGS: &[(u32, &str, &str)] = &[",
]
out += [f"    (0x{code:X}, {rust_str(lower)}, {rust_str(upper)})," for code, lower, upper in special]
out += [
    "];",
    "",
    "/// The one entry with a conditional lower case: `.0` lowers to `.1` in",
    "/// Final_Sigma context. `CASE_RANGES` has its usual mappings.",
    f"pub(super) const FINAL_SIGMA: (char, char) = ('\\u{{{final_sigma[0]:X}}}', '\\u{{{final_sigma[1]:X}}}');",
    "",
]
OUT.write_text("\n".join(out))
print(f"{OUT}: {len(entries)} entries, {len(ranges)} runs, {len(special)} special")
