//! Port of internal/api/stringer_generated.go.
//! Code generated by "stringer -type=MessageType -output=stringer_generated.go"; DO NOT EDIT.

use crate::api::prelude::*;

use crate::api::protocol_msgpack::MessageType;

// Go: stringer_generated.go:7 _
// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
const _: () = {
    assert!(MessageType::UNKNOWN.0 == 0);
    assert!(MessageType::REQUEST.0 == 1);
    assert!(MessageType::CALL_RESPONSE.0 == 2);
    assert!(MessageType::CALL_ERROR.0 == 3);
    assert!(MessageType::RESPONSE.0 == 4);
    assert!(MessageType::ERROR.0 == 5);
    assert!(MessageType::CALL.0 == 6);
};

// Go: stringer_generated.go:20 _MessageType_name
const _MESSAGE_TYPE_NAME: &str = "MessageTypeUnknownMessageTypeRequestMessageTypeCallResponseMessageTypeCallErrorMessageTypeResponseMessageTypeErrorMessageTypeCall";

// Go: stringer_generated.go:22 _MessageType_index
const _MESSAGE_TYPE_INDEX: [u8; 8] = [0, 18, 36, 59, 79, 98, 114, 129];

impl MessageType {
    // Go: stringer_generated.go:24 String
    // PORT: Go also tests `i < 0`, which never holds for the uint8 type.
    pub fn string(self) -> String {
        let idx = usize::from(self.0);
        if idx >= _MESSAGE_TYPE_INDEX.len() - 1 {
            return format!("MessageType({})", self.0);
        }
        _MESSAGE_TYPE_NAME
            [usize::from(_MESSAGE_TYPE_INDEX[idx])..usize::from(_MESSAGE_TYPE_INDEX[idx + 1])]
            .to_string()
    }
}

// Go `%v` / `%s` of a MessageType calls String.
impl std::fmt::Display for MessageType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}
