[package]
name = "ts_goport"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ts_ast = { path = "../ts_ast" }
ts_compiler = { path = "../ts_compiler" }
ts_core = { path = "../ts_core" }
ts_diagnostic_writer = { path = "../ts_diagnostic_writer" }
ts_diagnostics = { path = "../ts_diagnostics" }
ts_jsnum = { path = "../ts_jsnum" }
ts_module = { path = "../ts_module" }
ts_options = { path = "../ts_options" }
ts_parser = { path = "../ts_parser" }
ts_scanner = { path = "../ts_scanner" }
ts_path = { path = "../ts_path" }
ts_vfs = { path = "../ts_vfs" }
rustc-hash = "=2.1.2"
indexmap = "=2.14.0"

[lints]
workspace = true
