[package]
name = "ts_fixture"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Parser for TypeScript compiler baseline fixtures"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ts_fixture_baseline"
path = "src/main.rs"

[dependencies]
ts_compiler = { path = "../../crates/ts_compiler" }
ts_config = { path = "../../crates/ts_config" }
ts_core = { path = "../../crates/ts_core" }
ts_diagnostic_writer = { path = "../../crates/ts_diagnostic_writer" }
ts_options = { path = "../../crates/ts_options" }
ts_path = { path = "../../crates/ts_path" }
ts_vfs = { path = "../../crates/ts_vfs" }

[dev-dependencies]
ts_parser = { path = "../../crates/ts_parser" }

[lints]
workspace = true
