//! Generator for TypeScript's diagnostic message catalog.

use std::{
    collections::{BTreeMap, HashMap},
    error::Error,
    fmt::{self, Write as _},
    fs,
    path::Path,
};

use serde::Deserialize;

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum Category {
    Warning,
    Error,
    Suggestion,
    Message,
}

impl Category {
    fn rust_name(self) -> &'static str {
        match self {
            Self::Warning => "Warning",
            Self::Error => "Error",
            Self::Suggestion => "Suggestion",
            Self::Message => "Message",
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Entry {
    pub code: u32,
    pub category: Category,
    pub key: String,
    pub text: String,
    pub reports_unnecessary: bool,
    pub elided_in_compatibility_pyramid: bool,
    pub reports_deprecated: bool,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct JsonEntry {
    category: String,
    code: u32,
    #[serde(default)]
    reports_unnecessary: bool,
    #[serde(default)]
    reports_deprecated: bool,
    #[serde(default, rename = "elidedInCompatabilityPyramid")]
    elided_in_compatibility_pyramid: bool,
}

#[derive(Debug)]
pub struct GenerateError(String);

impl fmt::Display for GenerateError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl Error for GenerateError {}

/// Reads TypeScript diagnosticMessages.json inputs. Later files replace an
/// earlier entry with the same diagnostic code, matching the Go generator.
///
/// # Errors
///
/// Returns errors for unreadable files, malformed JSON, or unknown categories.
pub fn read_json_catalog(paths: &[impl AsRef<Path>]) -> Result<Vec<Entry>, GenerateError> {
    let mut messages = BTreeMap::<u32, (String, JsonEntry)>::new();
    for path in paths {
        let path = path.as_ref();
        let source = fs::read_to_string(path).map_err(|error| {
            GenerateError(format!("failed to read {}: {error}", path.display()))
        })?;
        let input: BTreeMap<String, JsonEntry> =
            serde_json::from_str(&source).map_err(|error| {
                GenerateError(format!("failed to parse {}: {error}", path.display()))
            })?;
        messages.extend(
            input
                .into_iter()
                .map(|(text, entry)| (entry.code, (text, entry))),
        );
    }

    let entries = messages
        .into_values()
        .map(|(text, input)| {
            Ok(Entry {
                code: input.code,
                category: parse_category(&input.category)?,
                key: diagnostic_key(&text, input.code),
                text,
                reports_unnecessary: input.reports_unnecessary,
                elided_in_compatibility_pyramid: input.elided_in_compatibility_pyramid,
                reports_deprecated: input.reports_deprecated,
            })
        })
        .collect::<Result<Vec<_>, GenerateError>>()?;
    validate_and_sort(entries)
}

/// Reads the merged <code>diagnostics_generated.go</code> catalog from a pinned ts-go
/// checkout. This fallback is useful when its TypeScript submodule is absent.
///
/// # Errors
///
/// Returns errors for unreadable or malformed generated input.
pub fn read_go_catalog(path: impl AsRef<Path>) -> Result<Vec<Entry>, GenerateError> {
    let path = path.as_ref();
    let source = fs::read_to_string(path)
        .map_err(|error| GenerateError(format!("failed to read {}: {error}", path.display())))?;
    let entries = source
        .lines()
        .filter(|line| is_go_message_line(line))
        .map(parse_go_entry)
        .collect::<Result<Vec<_>, _>>()?;
    if entries.is_empty() {
        return Err(GenerateError(format!(
            "{} contained no generated messages",
            path.display()
        )));
    }
    validate_and_sort(entries)
}

/// Emits a deterministic Rust catalog sorted by diagnostic code.
#[must_use]
pub fn generate_rust(entries: &[Entry], provenance: &str) -> String {
    let mut output = String::from("// @generated by ts_diagnostics_codegen; DO NOT EDIT.\n");
    output.push_str("// Source: ");
    output.push_str(provenance);
    output.push_str("\n\nuse super::{Category, Message};\n\npub static CATALOG: &[Message] = &[\n");
    for entry in entries {
        output.push_str("    Message::catalog(\n        ");
        output.push_str(&rust_number(entry.code));
        output.push_str(",\n        Category::");
        output.push_str(entry.category.rust_name());
        output.push_str(",\n        ");
        output.push_str(&rust_string(&entry.key));
        output.push_str(",\n        ");
        output.push_str(&rust_string(&entry.text));
        output.push_str(",\n        ");
        output.push_str(if entry.reports_unnecessary {
            "true"
        } else {
            "false"
        });
        output.push_str(",\n        ");
        output.push_str(if entry.elided_in_compatibility_pyramid {
            "true"
        } else {
            "false"
        });
        output.push_str(",\n        ");
        output.push_str(if entry.reports_deprecated {
            "true"
        } else {
            "false"
        });
        output.push_str(",\n    ),\n");
    }
    output.push_str("];\n");
    output
}

/// Reads the Go variable name and message key of each message in a
/// <code>diagnostics_generated.go</code> catalog, in file order.
///
/// # Errors
///
/// Returns errors for unreadable or malformed generated input.
pub fn read_go_names(path: impl AsRef<Path>) -> Result<Vec<(String, String)>, GenerateError> {
    let path = path.as_ref();
    let source = fs::read_to_string(path)
        .map_err(|error| GenerateError(format!("failed to read {}: {error}", path.display())))?;
    source
        .lines()
        .filter(|line| is_go_message_line(line))
        .map(|line| {
            let name = parse_field(line, "var ", " ")?.to_owned();
            Ok((name, parse_quoted_field(line, "key: ")?))
        })
        .collect()
}

/// Reads the messages that Go removed at the pin but that unported Rust code
/// still uses. Each line is the message's Go line from the previous pin's
/// <code>diagnostics_generated.go</code>; blank lines and `#` comments are skipped.
/// They stay out of `CATALOG`, so `message_by_key` and the catalog are Go's.
///
/// # Errors
///
/// Returns errors for an unreadable file or a line that is not a Go message.
pub fn read_removed(path: impl AsRef<Path>) -> Result<Vec<(String, Entry)>, GenerateError> {
    let path = path.as_ref();
    let source = fs::read_to_string(path)
        .map_err(|error| GenerateError(format!("failed to read {}: {error}", path.display())))?;
    source
        .lines()
        .filter(|line| !line.trim().is_empty() && !line.starts_with('#'))
        .map(|line| {
            if !is_go_message_line(line) {
                return Err(GenerateError(format!("not a Go message line: {line:?}")));
            }
            Ok((
                parse_field(line, "var ", " ")?.to_owned(),
                parse_go_entry(line)?,
            ))
        })
        .collect()
}

// Go: a message is `var Name = &Message{...}`. Since #64402 the file also has
// `var allMessages = [...]**Message{`, the list behind the lazy key map.
fn is_go_message_line(line: &str) -> bool {
    line.starts_with("var ") && line.contains(" = &Message{")
}

/// Emits `diag.rs`: one `pub static` per Go `diagnostics.Name` variable, in Go
/// order, that points at its message in the `CATALOG` of [`generate_rust`], and
/// Go's `keyToMessage`. The `removed` messages (see [`read_removed`]) follow as
/// local statics outside `CATALOG`; `key_to_message` finds them first.
/// `lazy_key_map` names Go's `keyToMessage` in `diagnostics.go` (see
/// [`has_lazy_key_map`]). Run rustfmt on the output: it wraps the long lines.
///
/// # Errors
///
/// Returns an error when the key of a name is not in `entries`, or when a
/// removed message is still in the Go catalog.
pub fn generate_names_rust(
    names: &[(String, String)],
    entries: &[Entry],
    removed: &[(String, Entry)],
    lazy_key_map: bool,
    provenance: &str,
) -> Result<String, GenerateError> {
    let positions: HashMap<&str, usize> = entries
        .iter()
        .enumerate()
        .map(|(index, entry)| (entry.key.as_str(), index))
        .collect();
    let imports = if removed.is_empty() {
        "CATALOG, Message"
    } else {
        "CATALOG, Category, Message"
    };
    let mut output = format!(
        "// @generated by ts_diagnostics_codegen; DO NOT EDIT.\n// Source: {provenance}\n\
         //! Go `diagnostics.Name` messages. Use them as `diag::Name`.\n\
         #![allow(non_upper_case_globals)]\n\n\
         use crate::diagnostics::{{{imports}}};\n\n"
    );
    for (name, key) in names {
        let index = positions
            .get(key.as_str())
            .ok_or_else(|| GenerateError(format!("{name}: key {key:?} is not in the catalog")))?;
        writeln!(output, "pub static {name}: &Message = &CATALOG[{index}];")
            .expect("writing to a String does not fail");
    }
    if !removed.is_empty() {
        output.push_str(
            "\n// PORT: messages that Go removed at the pin. Rust code in lanes that have not ported\n\
             // the removing change yet still uses them. Remove each one from the --removed file\n\
             // with its last Rust user.\n",
        );
    }
    for (name, entry) in removed {
        if names.iter().any(|(present, _)| present == name)
            || positions.contains_key(entry.key.as_str())
        {
            return Err(GenerateError(format!(
                "{name}: removed message is still in the Go catalog"
            )));
        }
        writeln!(
            output,
            "pub static {name}: &Message = &Message::new({}, Category::{}, {}, {}, {}, {}, {});",
            rust_number(entry.code),
            entry.category.rust_name(),
            rust_string(&entry.key),
            rust_string(&entry.text),
            entry.reports_unnecessary,
            entry.elided_in_compatibility_pyramid,
            entry.reports_deprecated,
        )
        .expect("writing to a String does not fail");
    }
    output.push_str(if lazy_key_map {
        "\n// Go: diagnostics/diagnostics.go keyToMessage\n\
         /// PORT: Go builds a lazy map from `allMessages`. `CATALOG` holds the same messages.\n"
    } else {
        "\n// Go: diagnostics/diagnostics_generated.go keyToMessage\n\
         /// PORT: Go switches over every key. `CATALOG` holds the same messages.\n"
    });
    if !removed.is_empty() {
        output.push_str(
            "/// The removed messages above match first: unported code still reports them, and a\n\
             /// serialized diagnostic must read back (Go at the previous pin knew their keys).\n",
        );
    }
    output.push_str(
        "#[must_use]\n\
         pub fn key_to_message(key: &str) -> Option<&'static Message> {\n",
    );
    if removed.is_empty() {
        output.push_str("    crate::diagnostics::message_by_key(key)\n}\n");
    } else {
        output.push_str("    match key {\n");
        for (name, entry) in removed {
            writeln!(
                output,
                "        {} => Some({name}),",
                rust_string(&entry.key)
            )
            .expect("writing to a String does not fail");
        }
        output.push_str("        _ => crate::diagnostics::message_by_key(key),\n    }\n}\n");
    }
    Ok(output)
}

/// Reports whether a <code>diagnostics_generated.go</code> has Go's `allMessages`
/// list (#64402): Go then builds `keyToMessage` lazily in `diagnostics.go`.
///
/// # Errors
///
/// Returns an error for an unreadable file.
pub fn has_lazy_key_map(path: impl AsRef<Path>) -> Result<bool, GenerateError> {
    let path = path.as_ref();
    let source = fs::read_to_string(path)
        .map_err(|error| GenerateError(format!("failed to read {}: {error}", path.display())))?;
    Ok(source
        .lines()
        .any(|line| line.starts_with("var allMessages = ")))
}

fn parse_go_entry(line: &str) -> Result<Entry, GenerateError> {
    let code = parse_field(line, "code: ", ",")?
        .parse::<u32>()
        .map_err(|error| GenerateError(format!("invalid code in generated line: {error}")))?;
    let category = parse_category(parse_field(line, "category: Category", ",")?)?;
    let key = parse_quoted_field(line, "key: ")?;
    let text = parse_quoted_field(line, "text: ")?;
    Ok(Entry {
        code,
        category,
        key,
        text,
        reports_unnecessary: line.contains("reportsUnnecessary: true"),
        elided_in_compatibility_pyramid: line.contains("elidedInCompatibilityPyramid: true"),
        reports_deprecated: line.contains("reportsDeprecated: true"),
    })
}

fn parse_field<'a>(
    line: &'a str,
    prefix: &str,
    terminator: &str,
) -> Result<&'a str, GenerateError> {
    let start = line
        .find(prefix)
        .map(|index| index + prefix.len())
        .ok_or_else(|| GenerateError(format!("missing {prefix:?} in generated line")))?;
    let tail = &line[start..];
    let end = tail
        .find(terminator)
        .ok_or_else(|| GenerateError(format!("missing {terminator:?} after {prefix:?}")))?;
    Ok(&tail[..end])
}

fn parse_quoted_field(line: &str, prefix: &str) -> Result<String, GenerateError> {
    let start = line
        .find(prefix)
        .map(|index| index + prefix.len())
        .ok_or_else(|| GenerateError(format!("missing {prefix:?} in generated line")))?;
    let tail = &line[start..];
    let mut escaped = false;
    let mut end = None;
    for (index, byte) in tail.as_bytes().iter().copied().enumerate().skip(1) {
        match byte {
            b'"' if !escaped => {
                end = Some(index + 1);
                break;
            }
            b'\\' if !escaped => escaped = true,
            _ => escaped = false,
        }
    }
    let literal = &tail[..end.ok_or_else(|| GenerateError("unterminated string field".into()))?];
    serde_json::from_str(literal)
        .map_err(|error| GenerateError(format!("invalid generated string {literal:?}: {error}")))
}

fn parse_category(value: &str) -> Result<Category, GenerateError> {
    match value {
        "Warning" => Ok(Category::Warning),
        "Error" => Ok(Category::Error),
        "Suggestion" => Ok(Category::Suggestion),
        "Message" => Ok(Category::Message),
        _ => Err(GenerateError(format!(
            "unknown diagnostic category {value:?}"
        ))),
    }
}

fn validate_and_sort(mut entries: Vec<Entry>) -> Result<Vec<Entry>, GenerateError> {
    entries.sort_by_key(|entry| entry.code);
    for pair in entries.windows(2) {
        if pair[0].code == pair[1].code {
            return Err(GenerateError(format!(
                "duplicate diagnostic code {}",
                pair[0].code
            )));
        }
    }
    Ok(entries)
}

fn diagnostic_key(text: &str, code: u32) -> String {
    let mut key = String::with_capacity(text.len() + 8);
    for character in text.chars() {
        match character {
            '*' => key.push_str("_Asterisk"),
            '/' => key.push_str("_Slash"),
            ':' => key.push_str("_Colon"),
            character if character.is_alphanumeric() => key.push(character),
            _ => key.push('_'),
        }
    }

    while key.contains("__") {
        key = key.replace("__", "_");
    }
    if key.starts_with('_')
        && !key
            .chars()
            .nth(1)
            .is_some_and(|character| character.is_ascii_digit())
    {
        key.remove(0);
    }
    if key.ends_with('_') {
        key.pop();
    }
    if key.len() > 100 {
        let mut end = 100;
        while !key.is_char_boundary(end) {
            end -= 1;
        }
        key.truncate(end);
    }
    format!("{key}_{code}")
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

fn rust_number(value: u32) -> String {
    let plain = value.to_string();
    let mut output = String::with_capacity(plain.len() + plain.len() / 3);
    for (index, character) in plain.chars().enumerate() {
        if index > 0 && (plain.len() - index).is_multiple_of(3) {
            output.push('_');
        }
        output.push(character);
    }
    output
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::{
        Category, generate_names_rust, generate_rust, has_lazy_key_map, read_go_catalog,
        read_go_names, read_json_catalog, read_removed,
    };

    fn temp_dir(name: &str) -> std::path::PathBuf {
        std::env::temp_dir().join(format!("{name}-{}", std::process::id()))
    }

    #[test]
    fn reads_json_inputs_and_flags() {
        let directory = temp_dir("ts-diagnostics-json-codegen");
        fs::create_dir_all(&directory).unwrap();
        let input = directory.join("diagnosticMessages.json");
        fs::write(
            &input,
            r#"{
                "Identifier expected.": { "category": "Error", "code": 1003 },
                "'{0}' is deprecated.": {
                    "category": "Suggestion",
                    "code": 6385,
                    "reportsDeprecated": true
                }
            }"#,
        )
        .unwrap();

        let entries = read_json_catalog(&[input]).unwrap();
        assert_eq!(entries[0].code, 1003);
        assert_eq!(entries[0].category, Category::Error);
        assert_eq!(entries[0].key, "Identifier_expected_1003");
        assert!(entries[1].reports_deprecated);
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn json_keys_match_typescript_punctuation_rules() {
        let directory = temp_dir("ts-diagnostics-key-codegen");
        fs::create_dir_all(&directory).unwrap();
        let input = directory.join("messages.json");
        fs::write(
            &input,
            r#"{
                "'{0}' expected.": {"category": "Error", "code": 1005},
                "'*/' expected.": {"category": "Error", "code": 1010}
            }"#,
        )
        .unwrap();
        let entries = read_json_catalog(&[input]).unwrap();
        assert_eq!(entries[0].key, "_0_expected_1005");
        assert_eq!(entries[1].key, "Asterisk_Slash_expected_1010");
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn later_json_inputs_replace_messages_with_the_same_code() {
        let directory = temp_dir("ts-diagnostics-code-override");
        fs::create_dir_all(&directory).unwrap();
        let original = directory.join("diagnosticMessages.json");
        let extra = directory.join("extraDiagnosticMessages.json");
        fs::write(
            &original,
            r#"{
                "Original message.": { "category": "Error", "code": 5074 },
                "Preserved message.": { "category": "Warning", "code": 5075 }
            }"#,
        )
        .unwrap();
        fs::write(
            &extra,
            r#"{"Replacement message.": {"category": "Message", "code": 5074}}"#,
        )
        .unwrap();

        let entries = read_json_catalog(&[original, extra]).unwrap();
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0].code, 5074);
        assert_eq!(entries[0].category, Category::Message);
        assert_eq!(entries[0].text, "Replacement message.");
        assert_eq!(entries[0].key, "Replacement_message_5074");
        assert_eq!(entries[1].text, "Preserved message.");
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn reads_pinned_go_fallback() {
        let directory = temp_dir("ts-diagnostics-go-codegen");
        fs::create_dir_all(&directory).unwrap();
        let input = directory.join("diagnostics_generated.go");
        fs::write(
            &input,
            r#"var Identifier_expected = &Message{code: 1003, category: CategoryError, key: "Identifier_expected_1003", text: "Identifier expected."}
var Deprecated = &Message{code: 6385, category: CategorySuggestion, key: "_0_is_deprecated_6385", text: "'{0}' is deprecated.", reportsDeprecated: true}
"#,
        )
        .unwrap();

        let entries = read_go_catalog(&input).unwrap();
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[1].text, "'{0}' is deprecated.");
        assert!(entries[1].reports_deprecated);
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn emits_go_names_in_go_order() {
        let directory = temp_dir("ts-diagnostics-go-names");
        fs::create_dir_all(&directory).unwrap();
        let input = directory.join("diagnostics_generated.go");
        fs::write(
            &input,
            r#"var Deprecated = &Message{code: 6385, category: CategorySuggestion, key: "_0_is_deprecated_6385", text: "'{0}' is deprecated.", reportsDeprecated: true}
var Identifier_expected = &Message{code: 1003, category: CategoryError, key: "Identifier_expected_1003", text: "Identifier expected."}
"#,
        )
        .unwrap();

        let entries = read_go_catalog(&input).unwrap();
        let names = read_go_names(&input).unwrap();
        let output = generate_names_rust(&names, &entries, &[], false, "pinned input").unwrap();
        let deprecated = output
            .find("pub static Deprecated: &Message = &CATALOG[1];")
            .unwrap();
        let identifier = output
            .find("pub static Identifier_expected: &Message = &CATALOG[0];")
            .unwrap();
        assert!(deprecated < identifier);
        assert!(output.contains("pub fn key_to_message("));

        let missing = [("Gone".to_owned(), "Gone_1".to_owned())];
        assert!(generate_names_rust(&missing, &entries, &[], false, "pinned input").is_err());
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn skips_the_message_list_and_keeps_removed_messages_outside_the_catalog() {
        let directory = temp_dir("ts-diagnostics-go-removed");
        fs::create_dir_all(&directory).unwrap();
        let input = directory.join("diagnostics_generated.go");
        fs::write(
            &input,
            r#"var Identifier_expected = &Message{code: 1003, category: CategoryError, key: "Identifier_expected_1003", text: "Identifier expected."}

var allMessages = [...]**Message{
	&Identifier_expected,
}
"#,
        )
        .unwrap();
        let removed_path = directory.join("removed.txt");
        fs::write(
            &removed_path,
            r#"# lane, PR
var Gone = &Message{code: 1463, category: CategoryError, key: "Gone_1463", text: "Gone."}
"#,
        )
        .unwrap();

        let entries = read_go_catalog(&input).unwrap();
        let names = read_go_names(&input).unwrap();
        assert_eq!(entries.len(), 1);
        assert_eq!(names.len(), 1);
        let removed = read_removed(&removed_path).unwrap();
        let output = generate_names_rust(&names, &entries, &removed, true, "pinned input").unwrap();
        assert!(output.contains("use crate::diagnostics::{CATALOG, Category, Message};"));
        assert!(output.contains(
            r#"pub static Gone: &Message = &Message::new(1_463, Category::Error, "Gone_1463", "Gone.", false, false, false);"#
        ));
        assert!(output.contains("// Go: diagnostics/diagnostics.go keyToMessage"));
        assert!(output.contains(r#""Gone_1463" => Some(Gone),"#));
        assert!(has_lazy_key_map(&input).unwrap());

        let present = [("Identifier_expected".to_owned(), entries[0].clone())];
        assert!(generate_names_rust(&names, &entries, &present, true, "pinned input").is_err());
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn emits_sorted_static_catalog() {
        let directory = temp_dir("ts-diagnostics-rust-codegen");
        fs::create_dir_all(&directory).unwrap();
        let input = directory.join("messages.json");
        fs::write(
            &input,
            r#"{"Identifier expected.": {"category": "Error", "code": 1003}}"#,
        )
        .unwrap();
        let entries = read_json_catalog(&[input]).unwrap();
        let output = generate_rust(&entries, "pinned input");
        assert!(output.contains("Message::catalog(\n        1_003,\n        Category::Error"));
        assert!(output.contains("Identifier_expected_1003"));
        fs::remove_dir_all(directory).unwrap();
    }
}
