//! Generator for TypeScript's diagnostic message catalog.

use std::{collections::BTreeMap, error::Error, fmt, fs, path::Path};

use serde::Deserialize;

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum Category {
    Warning,
    Error,
    Suggestion,
    Message,
}

impl Category {
    fn rust_name(self) -> &'static str {
        match self {
            Self::Warning => "Warning",
            Self::Error => "Error",
            Self::Suggestion => "Suggestion",
            Self::Message => "Message",
        }
    }
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Entry {
    pub code: u32,
    pub category: Category,
    pub key: String,
    pub text: String,
    pub reports_unnecessary: bool,
    pub elided_in_compatibility_pyramid: bool,
    pub reports_deprecated: bool,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct JsonEntry {
    category: String,
    code: u32,
    #[serde(default)]
    reports_unnecessary: bool,
    #[serde(default)]
    reports_deprecated: bool,
    #[serde(default, rename = "elidedInCompatabilityPyramid")]
    elided_in_compatibility_pyramid: bool,
}

#[derive(Debug)]
pub struct GenerateError(String);

impl fmt::Display for GenerateError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.0)
    }
}

impl Error for GenerateError {}

/// Reads TypeScript diagnosticMessages.json inputs. Later files replace an
/// earlier entry with the same English message, matching the Go generator.
///
/// # Errors
///
/// Returns errors for unreadable files, malformed JSON, categories, or duplicate codes.
pub fn read_json_catalog(paths: &[impl AsRef<Path>]) -> Result<Vec<Entry>, GenerateError> {
    let mut messages = BTreeMap::<String, JsonEntry>::new();
    for path in paths {
        let path = path.as_ref();
        let source = fs::read_to_string(path).map_err(|error| {
            GenerateError(format!("failed to read {}: {error}", path.display()))
        })?;
        let input: BTreeMap<String, JsonEntry> =
            serde_json::from_str(&source).map_err(|error| {
                GenerateError(format!("failed to parse {}: {error}", path.display()))
            })?;
        messages.extend(input);
    }

    let entries = messages
        .into_iter()
        .map(|(text, input)| {
            Ok(Entry {
                code: input.code,
                category: parse_category(&input.category)?,
                key: diagnostic_key(&text, input.code),
                text,
                reports_unnecessary: input.reports_unnecessary,
                elided_in_compatibility_pyramid: input.elided_in_compatibility_pyramid,
                reports_deprecated: input.reports_deprecated,
            })
        })
        .collect::<Result<Vec<_>, GenerateError>>()?;
    validate_and_sort(entries)
}

/// Reads the merged <code>diagnostics_generated.go</code> catalog from a pinned ts-go
/// checkout. This fallback is useful when its TypeScript submodule is absent.
///
/// # Errors
///
/// Returns errors for unreadable or malformed generated input.
pub fn read_go_catalog(path: impl AsRef<Path>) -> Result<Vec<Entry>, GenerateError> {
    let path = path.as_ref();
    let source = fs::read_to_string(path)
        .map_err(|error| GenerateError(format!("failed to read {}: {error}", path.display())))?;
    let entries = source
        .lines()
        .filter(|line| line.starts_with("var "))
        .map(parse_go_entry)
        .collect::<Result<Vec<_>, _>>()?;
    if entries.is_empty() {
        return Err(GenerateError(format!(
            "{} contained no generated messages",
            path.display()
        )));
    }
    validate_and_sort(entries)
}

/// Emits a deterministic Rust catalog sorted by diagnostic code.
#[must_use]
pub fn generate_rust(entries: &[Entry], provenance: &str) -> String {
    let mut output = String::from("// @generated by ts_diagnostics_codegen; DO NOT EDIT.\n");
    output.push_str("// Source: ");
    output.push_str(provenance);
    output.push_str("\n\nuse crate::{Category, Message};\n\npub static CATALOG: &[Message] = &[\n");
    for entry in entries {
        output.push_str("    Message::new(\n        ");
        output.push_str(&rust_number(entry.code));
        output.push_str(",\n        Category::");
        output.push_str(entry.category.rust_name());
        output.push_str(",\n        ");
        output.push_str(&rust_string(&entry.key));
        output.push_str(",\n        ");
        output.push_str(&rust_string(&entry.text));
        output.push_str(",\n        ");
        output.push_str(if entry.reports_unnecessary {
            "true"
        } else {
            "false"
        });
        output.push_str(",\n        ");
        output.push_str(if entry.elided_in_compatibility_pyramid {
            "true"
        } else {
            "false"
        });
        output.push_str(",\n        ");
        output.push_str(if entry.reports_deprecated {
            "true"
        } else {
            "false"
        });
        output.push_str(",\n    ),\n");
    }
    output.push_str("];\n");
    output
}

fn parse_go_entry(line: &str) -> Result<Entry, GenerateError> {
    let code = parse_field(line, "code: ", ",")?
        .parse::<u32>()
        .map_err(|error| GenerateError(format!("invalid code in generated line: {error}")))?;
    let category = parse_category(parse_field(line, "category: Category", ",")?)?;
    let key = parse_quoted_field(line, "key: ")?;
    let text = parse_quoted_field(line, "text: ")?;
    Ok(Entry {
        code,
        category,
        key,
        text,
        reports_unnecessary: line.contains("reportsUnnecessary: true"),
        elided_in_compatibility_pyramid: line.contains("elidedInCompatibilityPyramid: true"),
        reports_deprecated: line.contains("reportsDeprecated: true"),
    })
}

fn parse_field<'a>(
    line: &'a str,
    prefix: &str,
    terminator: &str,
) -> Result<&'a str, GenerateError> {
    let start = line
        .find(prefix)
        .map(|index| index + prefix.len())
        .ok_or_else(|| GenerateError(format!("missing {prefix:?} in generated line")))?;
    let tail = &line[start..];
    let end = tail
        .find(terminator)
        .ok_or_else(|| GenerateError(format!("missing {terminator:?} after {prefix:?}")))?;
    Ok(&tail[..end])
}

fn parse_quoted_field(line: &str, prefix: &str) -> Result<String, GenerateError> {
    let start = line
        .find(prefix)
        .map(|index| index + prefix.len())
        .ok_or_else(|| GenerateError(format!("missing {prefix:?} in generated line")))?;
    let tail = &line[start..];
    let mut escaped = false;
    let mut end = None;
    for (index, byte) in tail.as_bytes().iter().copied().enumerate().skip(1) {
        match byte {
            b'"' if !escaped => {
                end = Some(index + 1);
                break;
            }
            b'\\' if !escaped => escaped = true,
            _ => escaped = false,
        }
    }
    let literal = &tail[..end.ok_or_else(|| GenerateError("unterminated string field".into()))?];
    serde_json::from_str(literal)
        .map_err(|error| GenerateError(format!("invalid generated string {literal:?}: {error}")))
}

fn parse_category(value: &str) -> Result<Category, GenerateError> {
    match value {
        "Warning" => Ok(Category::Warning),
        "Error" => Ok(Category::Error),
        "Suggestion" => Ok(Category::Suggestion),
        "Message" => Ok(Category::Message),
        _ => Err(GenerateError(format!(
            "unknown diagnostic category {value:?}"
        ))),
    }
}

fn validate_and_sort(mut entries: Vec<Entry>) -> Result<Vec<Entry>, GenerateError> {
    entries.sort_by_key(|entry| entry.code);
    for pair in entries.windows(2) {
        if pair[0].code == pair[1].code {
            return Err(GenerateError(format!(
                "duplicate diagnostic code {}",
                pair[0].code
            )));
        }
    }
    Ok(entries)
}

fn diagnostic_key(text: &str, code: u32) -> String {
    let mut key = String::with_capacity(text.len() + 8);
    for character in text.chars() {
        match character {
            '*' => key.push_str("_Asterisk"),
            '/' => key.push_str("_Slash"),
            ':' => key.push_str("_Colon"),
            character if character.is_alphanumeric() => key.push(character),
            _ => key.push('_'),
        }
    }

    while key.contains("__") {
        key = key.replace("__", "_");
    }
    if key.starts_with('_')
        && !key
            .chars()
            .nth(1)
            .is_some_and(|character| character.is_ascii_digit())
    {
        key.remove(0);
    }
    if key.ends_with('_') {
        key.pop();
    }
    if key.len() > 100 {
        let mut end = 100;
        while !key.is_char_boundary(end) {
            end -= 1;
        }
        key.truncate(end);
    }
    format!("{key}_{code}")
}

fn rust_string(value: &str) -> String {
    format!("{value:?}")
}

fn rust_number(value: u32) -> String {
    let plain = value.to_string();
    let mut output = String::with_capacity(plain.len() + plain.len() / 3);
    for (index, character) in plain.chars().enumerate() {
        if index > 0 && (plain.len() - index).is_multiple_of(3) {
            output.push('_');
        }
        output.push(character);
    }
    output
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::{Category, generate_rust, read_go_catalog, read_json_catalog};

    fn temp_dir(name: &str) -> std::path::PathBuf {
        std::env::temp_dir().join(format!("{name}-{}", std::process::id()))
    }

    #[test]
    fn reads_json_inputs_and_flags() {
        let directory = temp_dir("ts-diagnostics-json-codegen");
        fs::create_dir_all(&directory).unwrap();
        let input = directory.join("diagnosticMessages.json");
        fs::write(
            &input,
            r#"{
                "Identifier expected.": { "category": "Error", "code": 1003 },
                "'{0}' is deprecated.": {
                    "category": "Suggestion",
                    "code": 6385,
                    "reportsDeprecated": true
                }
            }"#,
        )
        .unwrap();

        let entries = read_json_catalog(&[input]).unwrap();
        assert_eq!(entries[0].code, 1003);
        assert_eq!(entries[0].category, Category::Error);
        assert_eq!(entries[0].key, "Identifier_expected_1003");
        assert!(entries[1].reports_deprecated);
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn json_keys_match_typescript_punctuation_rules() {
        let directory = temp_dir("ts-diagnostics-key-codegen");
        fs::create_dir_all(&directory).unwrap();
        let input = directory.join("messages.json");
        fs::write(
            &input,
            r#"{
                "'{0}' expected.": {"category": "Error", "code": 1005},
                "'*/' expected.": {"category": "Error", "code": 1010}
            }"#,
        )
        .unwrap();
        let entries = read_json_catalog(&[input]).unwrap();
        assert_eq!(entries[0].key, "_0_expected_1005");
        assert_eq!(entries[1].key, "Asterisk_Slash_expected_1010");
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn reads_pinned_go_fallback() {
        let directory = temp_dir("ts-diagnostics-go-codegen");
        fs::create_dir_all(&directory).unwrap();
        let input = directory.join("diagnostics_generated.go");
        fs::write(
            &input,
            r#"var Identifier_expected = &Message{code: 1003, category: CategoryError, key: "Identifier_expected_1003", text: "Identifier expected."}
var Deprecated = &Message{code: 6385, category: CategorySuggestion, key: "_0_is_deprecated_6385", text: "'{0}' is deprecated.", reportsDeprecated: true}
"#,
        )
        .unwrap();

        let entries = read_go_catalog(&input).unwrap();
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[1].text, "'{0}' is deprecated.");
        assert!(entries[1].reports_deprecated);
        fs::remove_dir_all(directory).unwrap();
    }

    #[test]
    fn emits_sorted_static_catalog() {
        let directory = temp_dir("ts-diagnostics-rust-codegen");
        fs::create_dir_all(&directory).unwrap();
        let input = directory.join("messages.json");
        fs::write(
            &input,
            r#"{"Identifier expected.": {"category": "Error", "code": 1003}}"#,
        )
        .unwrap();
        let entries = read_json_catalog(&[input]).unwrap();
        let output = generate_rust(&entries, "pinned input");
        assert!(output.contains("Message::new(\n        1_003,\n        Category::Error"));
        assert!(output.contains("Identifier_expected_1003"));
        fs::remove_dir_all(directory).unwrap();
    }
}
