//! Go `ast.As<Kind>().<Field>` accessors and `ast.Is<Kind>` / `ast.Is<X>Kind`
//! helpers from pinned typescript-go `internal/ast/ast_generated.go`.
//!
//! Generated by a one-off script from `ast_generated.go` (Go struct fields and
//! `Is*` functions) and `crates/ts_ast/src/ast_generated.rs` (the `NodeData`
//! variants that hold the data). Regenerate instead of editing by hand.
//!
//! Rules (see PORTING.md "AST"):
//! - One `Node` method per exported Go node field. It works for every node
//!   struct that has the field and panics on other kinds, like a Go `AsX()`
//!   type assertion.
//! - Go fields that share a name with a Go `*Node` method (`Name`, `Body`,
//!   `Type`, `Expression`, `Text`, `Arguments`, ...) are not generated here.
//!   The `node.rs` method wins.
//! - Binder fields (`Symbol`, `LocalSymbol`, `Locals`, `NextContainer`,
//!   `FlowNode`, `EndFlowNode`, `ReturnFlowNode`) come from `NodeBindData`
//!   through `node.rs`. `SourceFile` fields other than `EndOfFileToken` come
//!   from `source_file_info` / `file_bind_data`.
//! - Unexported Go fields (`name`, `modifiers`, `facts`, `text`) are only
//!   reachable through Go `*Node` methods, so they are not generated.

use crate::prelude::*;
use ts_ast::NodeData;

/// The ts_ast data for `n`. Go reads node fields without a context; we reach
/// the parsed arena through the installed program.
fn node_data(n: Node) -> &'static NodeData {
    debug_assert!(n.is_some(), "nil node dereference");
    ast_data_of(n)
}

/// Go `nil` for an optional child.
fn opt_node(file: usize, id: Option<ts_ast::NodeId>) -> Node {
    match id {
        Some(id) => Node::new(file, id),
        None => Node::NIL,
    }
}

/// Builds the `NodeList` handle for a ts_ast list. `None` is Go `nil`.
// PORT: PORTING.md gives `NodeList` only as an example shape
// (`{ file: u32, list: Option<&'static ts_ast::NodeList> }`). This is the one
// place that depends on that shape.
fn make_node_list(file: usize, list: Option<&'static ts_ast::NodeList>) -> NodeList {
    NodeList { file: file as u32, list }
}

/// Go panics with a failed type assertion when `AsX()` gets the wrong kind.
#[cold]
fn field_panic(n: Node, field: &str) -> ! {
    panic!("ast field {field} does not exist on node kind {:?}", n.kind())
}

// ──────────────────────────────────────────────────────────────────────
// Node fields
// ──────────────────────────────────────────────────────────────────────

impl Node {
    // Go: ast/ast_generated.go:160 FullSignature
    /// Go `node.AsX().FullSignature` for: FunctionDeclaration, CallSignatureDeclaration, ConstructSignatureDeclaration, ConstructorDeclaration, GetAccessorDeclaration, SetAccessorDeclaration, IndexSignatureDeclaration, MethodSignatureDeclaration, MethodDeclaration, ArrowFunction, FunctionExpression, FunctionTypeNode, ConstructorTypeNode, JSDocSignature.
    #[must_use]
    pub fn full_signature(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::FunctionDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::CallSignatureDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::ConstructSignatureDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::ConstructorDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::GetAccessorDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::SetAccessorDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::IndexSignatureDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::MethodSignatureDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::MethodDeclaration(d) => opt_node(file, d.full_signature),
            NodeData::ArrowFunction(d) => opt_node(file, d.full_signature),
            NodeData::FunctionExpression(d) => opt_node(file, d.full_signature),
            NodeData::FunctionTypeNode(d) => opt_node(file, d.full_signature),
            NodeData::ConstructorTypeNode(d) => opt_node(file, d.full_signature),
            NodeData::JsDocSignature(d) => opt_node(file, d.full_signature),
            _ => field_panic(self, "FullSignature"),
        }
    }

    // Go: ast/ast_generated.go:164 AsteriskToken
    /// Go `node.AsX().AsteriskToken` for: FunctionDeclaration, ConstructorDeclaration, GetAccessorDeclaration, SetAccessorDeclaration, MethodDeclaration, YieldExpression, ArrowFunction, FunctionExpression, ModuleDeclaration.
    #[must_use]
    pub fn asterisk_token(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::FunctionDeclaration(d) => opt_node(file, d.asterisk_token),
            NodeData::ConstructorDeclaration(d) => opt_node(file, d.asterisk_token),
            NodeData::GetAccessorDeclaration(d) => opt_node(file, d.asterisk_token),
            NodeData::SetAccessorDeclaration(d) => opt_node(file, d.asterisk_token),
            NodeData::MethodDeclaration(d) => opt_node(file, d.asterisk_token),
            NodeData::YieldExpression(d) => opt_node(file, d.asterisk_token),
            NodeData::ArrowFunction(d) => opt_node(file, d.asterisk_token),
            NodeData::FunctionExpression(d) => opt_node(file, d.asterisk_token),
            NodeData::ModuleDeclaration(d) => opt_node(file, d.asterisk_token),
            _ => field_panic(self, "AsteriskToken"),
        }
    }

    // Go: ast/ast_generated.go:182 HeritageClauses
    /// Go `node.AsX().HeritageClauses` for: ClassDeclaration, ClassExpression, InterfaceDeclaration.
    #[must_use]
    pub fn heritage_clauses(self) -> NodeList {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ClassDeclaration(d) => make_node_list(file, d.heritage_clauses.as_ref()),
            NodeData::ClassExpression(d) => make_node_list(file, d.heritage_clauses.as_ref()),
            NodeData::InterfaceDeclaration(d) => make_node_list(file, d.heritage_clauses.as_ref()),
            _ => field_panic(self, "HeritageClauses"),
        }
    }

    // Go: ast/ast_generated.go:188 TokenFlags
    /// Go `node.AsX().TokenFlags` for: StringLiteral, NumericLiteral, BigIntLiteral, RegularExpressionLiteral, NoSubstitutionTemplateLiteral, TemplateHead, TemplateMiddle, TemplateTail, JsxText.
    #[must_use]
    pub fn token_flags(self) -> TokenFlags {
        match node_data(self) {
            NodeData::StringLiteral(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::NumericLiteral(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::BigIntLiteral(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::RegularExpressionLiteral(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::NoSubstitutionTemplateLiteral(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::TemplateHead(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::TemplateMiddle(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::TemplateTail(d) => TokenFlags(d.token_flags.0 as i32),
            NodeData::JsxText(d) => TokenFlags(d.token_flags.0 as i32),
            _ => field_panic(self, "TokenFlags"),
        }
    }

    // Go: ast/ast_generated.go:199 TemplateFlags
    /// Go `node.AsX().TemplateFlags` for: NoSubstitutionTemplateLiteral, TemplateHead, TemplateMiddle, TemplateTail.
    #[must_use]
    pub fn template_flags(self) -> TokenFlags {
        match node_data(self) {
            NodeData::NoSubstitutionTemplateLiteral(d) => TokenFlags(d.template_flags.0 as i32),
            NodeData::TemplateHead(d) => TokenFlags(d.template_flags.0 as i32),
            NodeData::TemplateMiddle(d) => TokenFlags(d.template_flags.0 as i32),
            NodeData::TemplateTail(d) => TokenFlags(d.template_flags.0 as i32),
            _ => field_panic(self, "TemplateFlags"),
        }
    }

    // Go: ast/ast_generated.go:2321 Types
    /// Go `node.AsX().Types` for: HeritageClause, UnionTypeNode, IntersectionTypeNode.
    #[must_use]
    pub fn types(self) -> NodeList {
        let file = self.file_index();
        match node_data(self) {
            NodeData::HeritageClause(d) => make_node_list(file, Some(&d.types)),
            NodeData::UnionTypeNode(d) => make_node_list(file, Some(&d.types)),
            NodeData::IntersectionTypeNode(d) => make_node_list(file, Some(&d.types)),
            _ => field_panic(self, "Types"),
        }
    }

    // Go: ast/ast_generated.go:7053 Comment
    /// Go `node.AsX().Comment` for: JSDoc, JSDocTypeTag, JSDocUnknownTag, JSDocTemplateTag, JSDocReturnTag, JSDocPublicTag, JSDocPrivateTag, JSDocProtectedTag, JSDocReadonlyTag, JSDocOverrideTag, JSDocDeprecatedTag, JSDocSeeTag, JSDocImplementsTag, JSDocAugmentsTag, JSDocSatisfiesTag, JSDocThrowsTag, JSDocThisTag, JSDocImportTag, JSDocCallbackTag, JSDocOverloadTag, JSDocTypedefTag, JSDocParameterOrPropertyTag.
    #[must_use]
    pub fn comment(self) -> NodeList {
        let file = self.file_index();
        match node_data(self) {
            NodeData::JsDoc(d) => make_node_list(file, Some(&d.comment)),
            NodeData::JsDocTypeTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocUnknownTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocTemplateTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocReturnTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocPublicTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocPrivateTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocProtectedTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocReadonlyTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocOverrideTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocDeprecatedTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocSeeTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocImplementsTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocAugmentsTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocSatisfiesTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocThrowsTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocThisTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocImportTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocCallbackTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocOverloadTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocTypedefTag(d) => make_node_list(file, d.comment.as_ref()),
            NodeData::JsDocParameterOrPropertyTag(d) => make_node_list(file, d.comment.as_ref()),
            _ => field_panic(self, "Comment"),
        }
    }

    // Go: ast/ast_generated.go:839 Left
    /// Go `node.AsX().Left` for: QualifiedName, BinaryExpression.
    #[must_use]
    pub fn left(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::QualifiedName(d) => Node::new(file, d.left),
            NodeData::BinaryExpression(d) => Node::new(file, d.left),
            _ => field_panic(self, "Left"),
        }
    }

    // Go: ast/ast_generated.go:840 Right
    /// Go `node.AsX().Right` for: QualifiedName, BinaryExpression.
    #[must_use]
    pub fn right(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::QualifiedName(d) => Node::new(file, d.right),
            NodeData::BinaryExpression(d) => Node::new(file, d.right),
            _ => field_panic(self, "Right"),
        }
    }

    // Go: ast/ast_generated.go:989 ThenStatement
    /// Go `node.AsX().ThenStatement` for: IfStatement.
    #[must_use]
    pub fn then_statement(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::IfStatement(d) => Node::new(file, d.then_statement),
            _ => field_panic(self, "ThenStatement"),
        }
    }

    // Go: ast/ast_generated.go:990 ElseStatement
    /// Go `node.AsX().ElseStatement` for: IfStatement.
    #[must_use]
    pub fn else_statement(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::IfStatement(d) => opt_node(file, d.else_statement),
            _ => field_panic(self, "ElseStatement"),
        }
    }

    // Go: ast/ast_generated.go:1129 Condition
    /// Go `node.AsX().Condition` for: ForStatement, ConditionalExpression.
    #[must_use]
    pub fn condition(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ForStatement(d) => opt_node(file, d.condition),
            NodeData::ConditionalExpression(d) => Node::new(file, d.condition),
            _ => field_panic(self, "Condition"),
        }
    }

    // Go: ast/ast_generated.go:1130 Incrementor
    /// Go `node.AsX().Incrementor` for: ForStatement.
    #[must_use]
    pub fn incrementor(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ForStatement(d) => opt_node(file, d.incrementor),
            _ => field_panic(self, "Incrementor"),
        }
    }

    // Go: ast/ast_generated.go:1183 AwaitModifier
    /// Go `node.AsX().AwaitModifier` for: ForInOrOfStatement.
    #[must_use]
    pub fn await_modifier(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ForInOrOfStatement(d) => opt_node(file, d.await_modifier),
            _ => field_panic(self, "AwaitModifier"),
        }
    }

    // Go: ast/ast_generated.go:1397 CaseBlock
    /// Go `node.AsX().CaseBlock` for: SwitchStatement.
    #[must_use]
    pub fn case_block(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::SwitchStatement(d) => Node::new(file, d.case_block),
            _ => field_panic(self, "CaseBlock"),
        }
    }

    // Go: ast/ast_generated.go:1443 Clauses
    /// Go `node.AsX().Clauses` for: CaseBlock.
    #[must_use]
    pub fn clauses(self) -> NodeList {
        let file = self.file_index();
        match node_data(self) {
            NodeData::CaseBlock(d) => make_node_list(file, Some(&d.clauses)),
            _ => field_panic(self, "Clauses"),
        }
    }

    // Go: ast/ast_generated.go:1488 FallthroughFlowNode
    /// Go `node.AsX().FallthroughFlowNode` for: CaseOrDefaultClause.
    /// PORT: the binder sets this field. `core::NodeBindData` has no
    /// separate slot, and case/default clauses have no Go `FlowNodeData`, so
    /// `bindCaseBlock` (binder_p3.rs) stores it in the clause's `flow_node`
    /// slot. The ts_ast value is not a Go flow node id and is not read.
    #[must_use]
    pub fn fallthrough_flow_node(self) -> FlowNodeId {
        match node_data(self) {
            NodeData::CaseOrDefaultClause(_) => self.bind().flow_node,
            _ => field_panic(self, "FallthroughFlowNode"),
        }
    }

    // Go: ast/ast_generated.go:1580 TryBlock
    /// Go `node.AsX().TryBlock` for: TryStatement.
    #[must_use]
    pub fn try_block(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::TryStatement(d) => Node::new(file, d.try_block),
            _ => field_panic(self, "TryBlock"),
        }
    }

    // Go: ast/ast_generated.go:1581 CatchClause
    /// Go `node.AsX().CatchClause` for: TryStatement.
    #[must_use]
    pub fn catch_clause(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::TryStatement(d) => opt_node(file, d.catch_clause),
            _ => field_panic(self, "CatchClause"),
        }
    }

    // Go: ast/ast_generated.go:1582 FinallyBlock
    /// Go `node.AsX().FinallyBlock` for: TryStatement.
    #[must_use]
    pub fn finally_block(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::TryStatement(d) => opt_node(file, d.finally_block),
            _ => field_panic(self, "FinallyBlock"),
        }
    }

    // Go: ast/ast_generated.go:1630 VariableDeclaration
    /// Go `node.AsX().VariableDeclaration` for: CatchClause.
    #[must_use]
    pub fn variable_declaration(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::CatchClause(d) => opt_node(file, d.variable_declaration),
            _ => field_panic(self, "VariableDeclaration"),
        }
    }

    // Go: ast/ast_generated.go:1631 Block
    /// Go `node.AsX().Block` for: CatchClause.
    #[must_use]
    pub fn block(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::CatchClause(d) => Node::new(file, d.block),
            _ => field_panic(self, "Block"),
        }
    }

    // Go: ast/ast_generated.go:1781 MultiLine
    /// Go `node.AsX().MultiLine` for: Block, ArrayLiteralExpression, ObjectLiteralExpression, ImportAttributes.
    #[must_use]
    pub fn multi_line(self) -> bool {
        match node_data(self) {
            NodeData::Block(d) => d.multi_line,
            NodeData::ArrayLiteralExpression(d) => d.multi_line,
            NodeData::ObjectLiteralExpression(d) => d.multi_line,
            NodeData::ImportAttributes(d) => d.multi_line,
            _ => field_panic(self, "MultiLine"),
        }
    }

    // Go: ast/ast_generated.go:1826 DeclarationList
    /// Go `node.AsX().DeclarationList` for: VariableStatement.
    #[must_use]
    pub fn declaration_list(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::VariableStatement(d) => Node::new(file, d.declaration_list),
            _ => field_panic(self, "DeclarationList"),
        }
    }

    // Go: ast/ast_generated.go:1869 ExclamationToken
    /// Go `node.AsX().ExclamationToken` for: VariableDeclaration.
    #[must_use]
    pub fn exclamation_token(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::VariableDeclaration(d) => opt_node(file, d.exclamation_token),
            _ => field_panic(self, "ExclamationToken"),
        }
    }

    // Go: ast/ast_generated.go:1920 Declarations
    /// Go `node.AsX().Declarations` for: VariableDeclarationList.
    #[must_use]
    pub fn declarations(self) -> NodeList {
        let file = self.file_index();
        match node_data(self) {
            NodeData::VariableDeclarationList(d) => make_node_list(file, Some(&d.declarations)),
            _ => field_panic(self, "Declarations"),
        }
    }

    // Go: ast/ast_generated.go:2006 DotDotDotToken
    /// Go `node.AsX().DotDotDotToken` for: ParameterDeclaration, BindingElement, NamedTupleMember, JsxExpression.
    #[must_use]
    pub fn dot_dot_dot_token(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ParameterDeclaration(d) => opt_node(file, d.dot_dot_dot_token),
            NodeData::BindingElement(d) => opt_node(file, d.dot_dot_dot_token),
            // PORT: an array binding hole, Go `BindingElement` with nil fields.
            NodeData::OmittedExpression(_) if self.kind() == SyntaxKind::BindingElement => Node::NIL,
            NodeData::NamedTupleMember(d) => opt_node(file, d.dot_dot_dot_token),
            NodeData::JsxExpression(d) => opt_node(file, d.dot_dot_dot_token),
            _ => field_panic(self, "DotDotDotToken"),
        }
    }

    // Go: ast/ast_generated.go:2320 Token
    /// Go `node.AsX().Token` for: HeritageClause, ImportAttributes.
    #[must_use]
    pub fn token(self) -> SyntaxKind {
        match node_data(self) {
            NodeData::HeritageClause(d) => d.token,
            NodeData::ImportAttributes(d) => d.token,
            _ => field_panic(self, "Token"),
        }
    }

    // Go: ast/ast_generated.go:2898 IsExportEquals
    /// Go `node.AsX().IsExportEquals` for: ExportAssignment.
    #[must_use]
    pub fn is_export_equals(self) -> bool {
        match node_data(self) {
            NodeData::ExportAssignment(d) => d.is_export_equals,
            _ => field_panic(self, "IsExportEquals"),
        }
    }

    // Go: ast/ast_generated.go:3889 OperatorToken
    /// Go `node.AsX().OperatorToken` for: BinaryExpression.
    #[must_use]
    pub fn operator_token(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::BinaryExpression(d) => Node::new(file, d.operator_token),
            _ => field_panic(self, "OperatorToken"),
        }
    }

    // Go: ast/ast_generated.go:3936 Operator
    /// Go `node.AsX().Operator` for: PrefixUnaryExpression, PostfixUnaryExpression, TypeOperatorNode.
    #[must_use]
    pub fn operator(self) -> SyntaxKind {
        match node_data(self) {
            NodeData::PrefixUnaryExpression(d) => d.operator,
            NodeData::PostfixUnaryExpression(d) => d.operator,
            NodeData::TypeOperatorNode(d) => d.operator,
            _ => field_panic(self, "Operator"),
        }
    }

    // Go: ast/ast_generated.go:3937 Operand
    /// Go `node.AsX().Operand` for: PrefixUnaryExpression, PostfixUnaryExpression.
    #[must_use]
    pub fn operand(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::PrefixUnaryExpression(d) => Node::new(file, d.operand),
            NodeData::PostfixUnaryExpression(d) => Node::new(file, d.operand),
            _ => field_panic(self, "Operand"),
        }
    }

    // Go: ast/ast_generated.go:4069 EqualsGreaterThanToken
    /// Go `node.AsX().EqualsGreaterThanToken` for: ArrowFunction.
    #[must_use]
    pub fn equals_greater_than_token(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ArrowFunction(d) => Node::new(file, d.equals_greater_than_token),
            _ => field_panic(self, "EqualsGreaterThanToken"),
        }
    }

    // Go: ast/ast_generated.go:4264 WhenTrue
    /// Go `node.AsX().WhenTrue` for: ConditionalExpression.
    #[must_use]
    pub fn when_true(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ConditionalExpression(d) => Node::new(file, d.when_true),
            _ => field_panic(self, "WhenTrue"),
        }
    }

    // Go: ast/ast_generated.go:4265 ColonToken
    /// Go `node.AsX().ColonToken` for: ConditionalExpression.
    #[must_use]
    pub fn colon_token(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ConditionalExpression(d) => Node::new(file, d.colon_token),
            _ => field_panic(self, "ColonToken"),
        }
    }

    // Go: ast/ast_generated.go:4266 WhenFalse
    /// Go `node.AsX().WhenFalse` for: ConditionalExpression.
    #[must_use]
    pub fn when_false(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ConditionalExpression(d) => Node::new(file, d.when_false),
            _ => field_panic(self, "WhenFalse"),
        }
    }

    // Go: ast/ast_generated.go:4374 ArgumentExpression
    /// Go `node.AsX().ArgumentExpression` for: ElementAccessExpression.
    #[must_use]
    pub fn argument_expression(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ElementAccessExpression(d) => Node::new(file, d.argument_expression),
            _ => field_panic(self, "ArgumentExpression"),
        }
    }

    // Go: ast/ast_generated.go:4518 KeywordToken
    /// Go `node.AsX().KeywordToken` for: MetaProperty.
    #[must_use]
    pub fn keyword_token(self) -> SyntaxKind {
        match node_data(self) {
            NodeData::MetaProperty(d) => d.keyword_token,
            _ => field_panic(self, "KeywordToken"),
        }
    }

    // Go: ast/ast_generated.go:4641 Head
    /// Go `node.AsX().Head` for: TemplateExpression, TemplateLiteralTypeNode.
    #[must_use]
    pub fn head(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::TemplateExpression(d) => Node::new(file, d.head),
            NodeData::TemplateLiteralTypeNode(d) => Node::new(file, d.head),
            _ => field_panic(self, "Head"),
        }
    }

    // Go: ast/ast_generated.go:4642 TemplateSpans
    /// Go `node.AsX().TemplateSpans` for: TemplateExpression, TemplateLiteralTypeNode.
    #[must_use]
    pub fn template_spans(self) -> NodeList {
        let file = self.file_index();
        match node_data(self) {
            NodeData::TemplateExpression(d) => make_node_list(file, Some(&d.template_spans)),
            NodeData::TemplateLiteralTypeNode(d) => make_node_list(file, Some(&d.template_spans)),
            _ => field_panic(self, "TemplateSpans"),
        }
    }

    // Go: ast/ast_generated.go:4687 Literal
    /// Go `node.AsX().Literal` for: TemplateSpan, LiteralTypeNode, TemplateLiteralTypeSpan.
    #[must_use]
    pub fn literal(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::TemplateSpan(d) => Node::new(file, d.literal),
            NodeData::LiteralTypeNode(d) => Node::new(file, d.literal),
            NodeData::TemplateLiteralTypeSpan(d) => Node::new(file, d.literal),
            _ => field_panic(self, "Literal"),
        }
    }

    // Go: ast/ast_generated.go:4732 Tag
    /// Go `node.AsX().Tag` for: TaggedTemplateExpression.
    #[must_use]
    pub fn tag(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::TaggedTemplateExpression(d) => Node::new(file, d.tag),
            _ => field_panic(self, "Tag"),
        }
    }

    // Go: ast/ast_generated.go:4735 Template
    /// Go `node.AsX().Template` for: TaggedTemplateExpression.
    #[must_use]
    pub fn template(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::TaggedTemplateExpression(d) => Node::new(file, d.template),
            _ => field_panic(self, "Template"),
        }
    }

    // Go: ast/ast_generated.go:5012 EqualsToken
    /// Go `node.AsX().EqualsToken` for: ShorthandPropertyAssignment.
    #[must_use]
    pub fn equals_token(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ShorthandPropertyAssignment(d) => opt_node(file, d.equals_token),
            _ => field_panic(self, "EqualsToken"),
        }
    }

    // Go: ast/ast_generated.go:5013 ObjectAssignmentInitializer
    /// Go `node.AsX().ObjectAssignmentInitializer` for: ShorthandPropertyAssignment.
    #[must_use]
    pub fn object_assignment_initializer(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ShorthandPropertyAssignment(d) => opt_node(file, d.object_assignment_initializer),
            _ => field_panic(self, "ObjectAssignmentInitializer"),
        }
    }

    // Go: ast/ast_generated.go:5382 CheckType
    /// Go `node.AsX().CheckType` for: ConditionalTypeNode.
    #[must_use]
    pub fn check_type(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ConditionalTypeNode(d) => Node::new(file, d.check_type),
            _ => field_panic(self, "CheckType"),
        }
    }

    // Go: ast/ast_generated.go:5383 ExtendsType
    /// Go `node.AsX().ExtendsType` for: ConditionalTypeNode.
    #[must_use]
    pub fn extends_type(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ConditionalTypeNode(d) => Node::new(file, d.extends_type),
            _ => field_panic(self, "ExtendsType"),
        }
    }

    // Go: ast/ast_generated.go:5384 TrueType
    /// Go `node.AsX().TrueType` for: ConditionalTypeNode.
    #[must_use]
    pub fn true_type(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ConditionalTypeNode(d) => Node::new(file, d.true_type),
            _ => field_panic(self, "TrueType"),
        }
    }

    // Go: ast/ast_generated.go:5385 FalseType
    /// Go `node.AsX().FalseType` for: ConditionalTypeNode.
    #[must_use]
    pub fn false_type(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ConditionalTypeNode(d) => Node::new(file, d.false_type),
            _ => field_panic(self, "FalseType"),
        }
    }

    // Go: ast/ast_generated.go:5469 TypeParameter
    /// Go `node.AsX().TypeParameter` for: InferTypeNode, MappedTypeNode.
    #[must_use]
    pub fn type_parameter(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::InferTypeNode(d) => Node::new(file, d.type_parameter),
            NodeData::MappedTypeNode(d) => Node::new(file, d.type_parameter),
            _ => field_panic(self, "TypeParameter"),
        }
    }

    // Go: ast/ast_generated.go:5507 ElementType
    /// Go `node.AsX().ElementType` for: ArrayTypeNode.
    #[must_use]
    pub fn element_type(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ArrayTypeNode(d) => Node::new(file, d.element_type),
            _ => field_panic(self, "ElementType"),
        }
    }

    // Go: ast/ast_generated.go:5545 ObjectType
    /// Go `node.AsX().ObjectType` for: IndexedAccessTypeNode.
    #[must_use]
    pub fn object_type(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::IndexedAccessTypeNode(d) => Node::new(file, d.object_type),
            _ => field_panic(self, "ObjectType"),
        }
    }

    // Go: ast/ast_generated.go:5546 IndexType
    /// Go `node.AsX().IndexType` for: IndexedAccessTypeNode.
    #[must_use]
    pub fn index_type(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::IndexedAccessTypeNode(d) => Node::new(file, d.index_type),
            _ => field_panic(self, "IndexType"),
        }
    }

    // Go: ast/ast_generated.go:5585 TypeName
    /// Go `node.AsX().TypeName` for: TypeReferenceNode.
    #[must_use]
    pub fn type_name(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::TypeReferenceNode(d) => Node::new(file, d.type_name),
            _ => field_panic(self, "TypeName"),
        }
    }

    // Go: ast/ast_generated.go:5724 AssertsModifier
    /// Go `node.AsX().AssertsModifier` for: TypePredicateNode.
    #[must_use]
    pub fn asserts_modifier(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::TypePredicateNode(d) => opt_node(file, d.asserts_modifier),
            _ => field_panic(self, "AssertsModifier"),
        }
    }

    // Go: ast/ast_generated.go:5725 ParameterName
    /// Go `node.AsX().ParameterName` for: TypePredicateNode.
    #[must_use]
    pub fn parameter_name(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::TypePredicateNode(d) => Node::new(file, d.parameter_name),
            _ => field_panic(self, "ParameterName"),
        }
    }

    // Go: ast/ast_generated.go:5768 Value
    /// Go `node.AsX().Value` for: ImportAttribute.
    #[must_use]
    pub fn value(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ImportAttribute(d) => Node::new(file, d.value),
            _ => field_panic(self, "Value"),
        }
    }

    // Go: ast/ast_generated.go:5863 ExprName
    /// Go `node.AsX().ExprName` for: TypeQueryNode.
    #[must_use]
    pub fn expr_name(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::TypeQueryNode(d) => Node::new(file, d.expr_name),
            _ => field_panic(self, "ExprName"),
        }
    }

    // Go: ast/ast_generated.go:5904 ReadonlyToken
    /// Go `node.AsX().ReadonlyToken` for: MappedTypeNode.
    #[must_use]
    pub fn readonly_token(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::MappedTypeNode(d) => opt_node(file, d.readonly_token),
            _ => field_panic(self, "ReadonlyToken"),
        }
    }

    // Go: ast/ast_generated.go:5906 NameType
    /// Go `node.AsX().NameType` for: MappedTypeNode.
    #[must_use]
    pub fn name_type(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::MappedTypeNode(d) => opt_node(file, d.name_type),
            _ => field_panic(self, "NameType"),
        }
    }

    // Go: ast/ast_generated.go:6443 IsSpread
    /// Go `node.AsX().IsSpread` for: SyntheticExpression.
    #[must_use]
    pub fn is_spread(self) -> bool {
        match node_data(self) {
            NodeData::SyntheticExpression(d) => d.is_spread,
            _ => field_panic(self, "IsSpread"),
        }
    }

    // Go: ast/ast_generated.go:6444 TupleNameSource
    /// Go `node.AsX().TupleNameSource` for: SyntheticExpression.
    #[must_use]
    pub fn tuple_name_source(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::SyntheticExpression(d) => opt_node(file, d.tuple_name_source),
            _ => field_panic(self, "TupleNameSource"),
        }
    }

    // Go: ast/ast_generated.go:6527 OpeningElement
    /// Go `node.AsX().OpeningElement` for: JsxElement.
    #[must_use]
    pub fn opening_element(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::JsxElement(d) => Node::new(file, d.opening_element),
            _ => field_panic(self, "OpeningElement"),
        }
    }

    // Go: ast/ast_generated.go:6529 ClosingElement
    /// Go `node.AsX().ClosingElement` for: JsxElement.
    #[must_use]
    pub fn closing_element(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::JsxElement(d) => Node::new(file, d.closing_element),
            _ => field_panic(self, "ClosingElement"),
        }
    }

    // Go: ast/ast_generated.go:6610 Namespace
    /// Go `node.AsX().Namespace` for: JsxNamespacedName.
    #[must_use]
    pub fn namespace(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::JsxNamespacedName(d) => Node::new(file, d.namespace),
            _ => field_panic(self, "Namespace"),
        }
    }

    // Go: ast/ast_generated.go:6741 OpeningFragment
    /// Go `node.AsX().OpeningFragment` for: JsxFragment.
    #[must_use]
    pub fn opening_fragment(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::JsxFragment(d) => Node::new(file, d.opening_fragment),
            _ => field_panic(self, "OpeningFragment"),
        }
    }

    // Go: ast/ast_generated.go:6743 ClosingFragment
    /// Go `node.AsX().ClosingFragment` for: JsxFragment.
    #[must_use]
    pub fn closing_fragment(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::JsxFragment(d) => Node::new(file, d.closing_fragment),
            _ => field_panic(self, "ClosingFragment"),
        }
    }

    // Go: ast/ast_generated.go:6989 ContainsOnlyTriviaWhiteSpaces
    /// Go `node.AsX().ContainsOnlyTriviaWhiteSpaces` for: JsxText.
    #[must_use]
    pub fn contains_only_trivia_white_spaces(self) -> bool {
        match node_data(self) {
            NodeData::JsxText(d) => d.contains_only_trivia_white_spaces,
            _ => field_panic(self, "ContainsOnlyTriviaWhiteSpaces"),
        }
    }

    // Go: ast/ast_generated.go:7054 Tags
    /// Go `node.AsX().Tags` for: JSDoc.
    #[must_use]
    pub fn tags(self) -> NodeList {
        let file = self.file_index();
        match node_data(self) {
            NodeData::JsDoc(d) => make_node_list(file, d.tags.as_ref()),
            _ => field_panic(self, "Tags"),
        }
    }

    // Go: ast/ast_generated.go:7382 Constraint
    /// Go `node.AsX().Constraint` for: JSDocTemplateTag, TypeParameterDeclaration.
    #[must_use]
    pub fn constraint(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::JsDocTemplateTag(d) => Node::new(file, d.constraint),
            NodeData::TypeParameterDeclaration(d) => opt_node(file, d.constraint),
            _ => field_panic(self, "Constraint"),
        }
    }

    // Go: ast/ast_generated.go:7695 NameExpression
    /// Go `node.AsX().NameExpression` for: JSDocSeeTag.
    #[must_use]
    pub fn name_expression(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::JsDocSeeTag(d) => Node::new(file, d.name_expression),
            _ => field_panic(self, "NameExpression"),
        }
    }

    // Go: ast/ast_generated.go:8218 Keyword
    /// Go `node.AsX().Keyword` for: ModuleDeclaration.
    #[must_use]
    pub fn keyword(self) -> SyntaxKind {
        match node_data(self) {
            NodeData::ModuleDeclaration(d) => d.keyword,
            _ => field_panic(self, "Keyword"),
        }
    }

    // Go: ast/ast_generated.go:8270 ModuleReference
    /// Go `node.AsX().ModuleReference` for: ImportEqualsDeclaration.
    #[must_use]
    pub fn module_reference(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ImportEqualsDeclaration(d) => Node::new(file, d.module_reference),
            _ => field_panic(self, "ModuleReference"),
        }
    }

    // Go: ast/ast_generated.go:8319 ExportClause
    /// Go `node.AsX().ExportClause` for: ExportDeclaration.
    #[must_use]
    pub fn export_clause(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ExportDeclaration(d) => opt_node(file, d.export_clause),
            _ => field_panic(self, "ExportClause"),
        }
    }

    // Go: ast/ast_generated.go:8366 IsTypeOf
    /// Go `node.AsX().IsTypeOf` for: ImportTypeNode.
    #[must_use]
    pub fn is_type_of(self) -> bool {
        match node_data(self) {
            NodeData::ImportTypeNode(d) => d.is_type_of,
            _ => field_panic(self, "IsTypeOf"),
        }
    }

    // Go: ast/ast_generated.go:8367 Argument
    /// Go `node.AsX().Argument` for: ImportTypeNode.
    #[must_use]
    pub fn argument(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ImportTypeNode(d) => Node::new(file, d.argument),
            _ => field_panic(self, "Argument"),
        }
    }

    // Go: ast/ast_generated.go:8369 Qualifier
    /// Go `node.AsX().Qualifier` for: ImportTypeNode.
    #[must_use]
    pub fn qualifier(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ImportTypeNode(d) => opt_node(file, d.qualifier),
            _ => field_panic(self, "Qualifier"),
        }
    }

    // Go: ast/ast_generated.go:8417 PhaseModifier
    /// Go `node.AsX().PhaseModifier` for: ImportClause.
    #[must_use]
    pub fn phase_modifier(self) -> SyntaxKind {
        match node_data(self) {
            NodeData::ImportClause(d) => d.phase_modifier.unwrap_or(SyntaxKind::Unknown),
            _ => field_panic(self, "PhaseModifier"),
        }
    }

    // Go: ast/ast_generated.go:8419 NamedBindings
    /// Go `node.AsX().NamedBindings` for: ImportClause.
    #[must_use]
    pub fn named_bindings(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::ImportClause(d) => opt_node(file, d.named_bindings),
            _ => field_panic(self, "NamedBindings"),
        }
    }

    // Go: ast/ast_generated.go:8673 DefaultType
    /// Go `node.AsX().DefaultType` for: TypeParameterDeclaration.
    #[must_use]
    pub fn default_type(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::TypeParameterDeclaration(d) => opt_node(file, d.default_type),
            _ => field_panic(self, "DefaultType"),
        }
    }

    // Go: ast/ast_generated.go:8724 ThisArg
    /// Go `node.AsX().ThisArg` for: SyntheticReferenceExpression.
    #[must_use]
    pub fn this_arg(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::SyntheticReferenceExpression(d) => Node::new(file, d.this_arg),
            _ => field_panic(self, "ThisArg"),
        }
    }

    // Go: ast/ast_generated.go:8769 JSDocPropertyTags
    /// Go `node.AsX().JSDocPropertyTags` for: JSDocTypeLiteral.
    #[must_use]
    pub fn js_doc_property_tags(self) -> Vec<Node> {
        let file = self.file_index();
        match node_data(self) {
            NodeData::JsDocTypeLiteral(d) => d.js_doc_property_tags.as_ref().map_or_else(Vec::new, |ids| ids.iter().map(|&id| Node::new(file, id)).collect()),
            _ => field_panic(self, "JSDocPropertyTags"),
        }
    }

    // Go: ast/ast_generated.go:8770 IsArrayType
    /// Go `node.AsX().IsArrayType` for: JSDocTypeLiteral.
    #[must_use]
    pub fn is_array_type(self) -> bool {
        match node_data(self) {
            NodeData::JsDocTypeLiteral(d) => d.is_array_type,
            _ => field_panic(self, "IsArrayType"),
        }
    }

    // Go: ast/ast_generated.go:8811 IsBracketed
    /// Go `node.AsX().IsBracketed` for: JSDocParameterOrPropertyTag.
    #[must_use]
    pub fn is_bracketed(self) -> bool {
        match node_data(self) {
            NodeData::JsDocParameterOrPropertyTag(d) => d.is_bracketed,
            _ => field_panic(self, "IsBracketed"),
        }
    }

    // Go: ast/ast_generated.go:8813 IsNameFirst
    /// Go `node.AsX().IsNameFirst` for: JSDocParameterOrPropertyTag.
    #[must_use]
    pub fn is_name_first(self) -> bool {
        match node_data(self) {
            NodeData::JsDocParameterOrPropertyTag(d) => d.is_name_first,
            _ => field_panic(self, "IsNameFirst"),
        }
    }

    // Go: ast/ast.go:2478 EndOfFileToken
    /// Go `node.AsX().EndOfFileToken` for: SourceFile.
    #[must_use]
    pub fn end_of_file_token(self) -> Node {
        let file = self.file_index();
        match node_data(self) {
            NodeData::SourceFile(d) => Node::new(file, d.end_of_file_token),
            _ => field_panic(self, "EndOfFileToken"),
        }
    }
}

// ──────────────────────────────────────────────────────────────────────
// Kind guards (Go IsX(node) and IsXKind(kind))
// ──────────────────────────────────────────────────────────────────────

// Go: ast/ast_generated.go:608 IsToken
#[must_use]
pub fn is_token(node: Node) -> bool {
    // PORT: Go lists 166 more `case` labels with empty bodies before the
    // last one. Go `switch` does not fall through, so those kinds reach
    // `return false`. We keep that behavior. Empty-case kinds:
    //   KindUnknown, KindEndOfFile, KindSingleLineCommentTrivia, KindMultiLineCommentTrivia, KindNewLineTrivia, KindWhitespaceTrivia
    //   KindConflictMarkerTrivia, KindNonTextFileMarkerTrivia, KindNumericLiteral, KindBigIntLiteral, KindStringLiteral, KindJsxText
    //   KindJsxTextAllWhiteSpaces, KindRegularExpressionLiteral, KindNoSubstitutionTemplateLiteral, KindTemplateHead, KindTemplateMiddle, KindTemplateTail
    //   KindOpenBraceToken, KindCloseBraceToken, KindOpenParenToken, KindCloseParenToken, KindOpenBracketToken, KindCloseBracketToken
    //   KindDotToken, KindDotDotDotToken, KindSemicolonToken, KindCommaToken, KindQuestionDotToken, KindLessThanToken
    //   KindLessThanSlashToken, KindGreaterThanToken, KindLessThanEqualsToken, KindGreaterThanEqualsToken, KindEqualsEqualsToken, KindExclamationEqualsToken
    //   KindEqualsEqualsEqualsToken, KindExclamationEqualsEqualsToken, KindEqualsGreaterThanToken, KindPlusToken, KindMinusToken, KindAsteriskToken
    //   KindAsteriskAsteriskToken, KindSlashToken, KindPercentToken, KindPlusPlusToken, KindMinusMinusToken, KindLessThanLessThanToken
    //   KindGreaterThanGreaterThanToken, KindGreaterThanGreaterThanGreaterThanToken, KindAmpersandToken, KindBarToken, KindCaretToken, KindExclamationToken
    //   KindTildeToken, KindAmpersandAmpersandToken, KindBarBarToken, KindQuestionToken, KindColonToken, KindAtToken
    //   KindQuestionQuestionToken, KindBacktickToken, KindHashToken, KindEqualsToken, KindPlusEqualsToken, KindMinusEqualsToken
    //   KindAsteriskEqualsToken, KindAsteriskAsteriskEqualsToken, KindSlashEqualsToken, KindPercentEqualsToken, KindLessThanLessThanEqualsToken, KindGreaterThanGreaterThanEqualsToken
    //   KindGreaterThanGreaterThanGreaterThanEqualsToken, KindAmpersandEqualsToken, KindBarEqualsToken, KindBarBarEqualsToken, KindAmpersandAmpersandEqualsToken, KindQuestionQuestionEqualsToken
    //   KindCaretEqualsToken, KindIdentifier, KindPrivateIdentifier, KindJSDocCommentTextToken, KindBreakKeyword, KindCaseKeyword
    //   KindCatchKeyword, KindClassKeyword, KindConstKeyword, KindContinueKeyword, KindDebuggerKeyword, KindDefaultKeyword
    //   KindDeleteKeyword, KindDoKeyword, KindElseKeyword, KindEnumKeyword, KindExportKeyword, KindExtendsKeyword
    //   KindFalseKeyword, KindFinallyKeyword, KindForKeyword, KindFunctionKeyword, KindIfKeyword, KindImportKeyword
    //   KindInKeyword, KindInstanceOfKeyword, KindNewKeyword, KindNullKeyword, KindReturnKeyword, KindSuperKeyword
    //   KindSwitchKeyword, KindThisKeyword, KindThrowKeyword, KindTrueKeyword, KindTryKeyword, KindTypeOfKeyword
    //   KindVarKeyword, KindVoidKeyword, KindWhileKeyword, KindWithKeyword, KindImplementsKeyword, KindInterfaceKeyword
    //   KindLetKeyword, KindPackageKeyword, KindPrivateKeyword, KindProtectedKeyword, KindPublicKeyword, KindStaticKeyword
    //   KindYieldKeyword, KindAbstractKeyword, KindAccessorKeyword, KindAsKeyword, KindAssertsKeyword, KindAssertKeyword
    //   KindAnyKeyword, KindAsyncKeyword, KindAwaitKeyword, KindBooleanKeyword, KindConstructorKeyword, KindDeclareKeyword
    //   KindGetKeyword, KindImmediateKeyword, KindInferKeyword, KindIntrinsicKeyword, KindIsKeyword, KindKeyOfKeyword
    //   KindModuleKeyword, KindNamespaceKeyword, KindNeverKeyword, KindOutKeyword, KindReadonlyKeyword, KindRequireKeyword
    //   KindNumberKeyword, KindObjectKeyword, KindSatisfiesKeyword, KindSetKeyword, KindStringKeyword, KindSymbolKeyword
    //   KindTypeKeyword, KindUndefinedKeyword, KindUniqueKeyword, KindUnknownKeyword, KindUsingKeyword, KindFromKeyword
    //   KindGlobalKeyword, KindBigIntKeyword, KindOverrideKeyword, KindOfKeyword
    match node.kind() {
        SyntaxKind::DeferKeyword => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:803 IsIdentifier
#[must_use]
pub fn is_identifier(node: Node) -> bool {
    node.kind() == SyntaxKind::Identifier
}

// Go: ast/ast_generated.go:827 IsPrivateIdentifier
#[must_use]
pub fn is_private_identifier(node: Node) -> bool {
    node.kind() == SyntaxKind::PrivateIdentifier
}

// Go: ast/ast_generated.go:874 IsQualifiedName
#[must_use]
pub fn is_qualified_name(node: Node) -> bool {
    node.kind() == SyntaxKind::QualifiedName
}

// Go: ast/ast_generated.go:917 IsComputedPropertyName
#[must_use]
pub fn is_computed_property_name(node: Node) -> bool {
    node.kind() == SyntaxKind::ComputedPropertyName
}

// Go: ast/ast_generated.go:956 IsDecorator
#[must_use]
pub fn is_decorator(node: Node) -> bool {
    node.kind() == SyntaxKind::Decorator
}

// Go: ast/ast_generated.go:977 IsEmptyStatement
#[must_use]
pub fn is_empty_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::EmptyStatement
}

// Go: ast/ast_generated.go:1026 IsIfStatement
#[must_use]
pub fn is_if_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::IfStatement
}

// Go: ast/ast_generated.go:1071 IsDoStatement
#[must_use]
pub fn is_do_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::DoStatement
}

// Go: ast/ast_generated.go:1116 IsWhileStatement
#[must_use]
pub fn is_while_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::WhileStatement
}

// Go: ast/ast_generated.go:1171 IsForStatement
#[must_use]
pub fn is_for_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::ForStatement
}

// Go: ast/ast_generated.go:1220 IsForInStatement
#[must_use]
pub fn is_for_in_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::ForInStatement
}

// Go: ast/ast_generated.go:1224 IsForOfStatement
#[must_use]
pub fn is_for_of_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::ForOfStatement
}

// Go: ast/ast_generated.go:1262 IsBreakStatement
#[must_use]
pub fn is_break_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::BreakStatement
}

// Go: ast/ast_generated.go:1300 IsContinueStatement
#[must_use]
pub fn is_continue_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::ContinueStatement
}

// Go: ast/ast_generated.go:1339 IsReturnStatement
#[must_use]
pub fn is_return_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::ReturnStatement
}

// Go: ast/ast_generated.go:1385 IsWithStatement
#[must_use]
pub fn is_with_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::WithStatement
}

// Go: ast/ast_generated.go:1431 IsSwitchStatement
#[must_use]
pub fn is_switch_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::SwitchStatement
}

// Go: ast/ast_generated.go:1475 IsCaseBlock
#[must_use]
pub fn is_case_block(node: Node) -> bool {
    node.kind() == SyntaxKind::CaseBlock
}

// Go: ast/ast_generated.go:1522 IsCaseClause
#[must_use]
pub fn is_case_clause(node: Node) -> bool {
    node.kind() == SyntaxKind::CaseClause
}

// Go: ast/ast_generated.go:1526 IsDefaultClause
#[must_use]
pub fn is_default_clause(node: Node) -> bool {
    node.kind() == SyntaxKind::DefaultClause
}

// Go: ast/ast_generated.go:1569 IsThrowStatement
#[must_use]
pub fn is_throw_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::ThrowStatement
}

// Go: ast/ast_generated.go:1618 IsTryStatement
#[must_use]
pub fn is_try_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::TryStatement
}

// Go: ast/ast_generated.go:1660 IsCatchClause
#[must_use]
pub fn is_catch_clause(node: Node) -> bool {
    node.kind() == SyntaxKind::CatchClause
}

// Go: ast/ast_generated.go:1681 IsDebuggerStatement
#[must_use]
pub fn is_debugger_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::DebuggerStatement
}

// Go: ast/ast_generated.go:1726 IsLabeledStatement
#[must_use]
pub fn is_labeled_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::LabeledStatement
}

// Go: ast/ast_generated.go:1768 IsExpressionStatement
#[must_use]
pub fn is_expression_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::ExpressionStatement
}

// Go: ast/ast_generated.go:1814 IsBlock
#[must_use]
pub fn is_block(node: Node) -> bool {
    node.kind() == SyntaxKind::Block
}

// Go: ast/ast_generated.go:1855 IsVariableStatement
#[must_use]
pub fn is_variable_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::VariableStatement
}

// Go: ast/ast_generated.go:1909 IsVariableDeclaration
#[must_use]
pub fn is_variable_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::VariableDeclaration
}

// Go: ast/ast_generated.go:1950 IsVariableDeclarationList
#[must_use]
pub fn is_variable_declaration_list(node: Node) -> bool {
    node.kind() == SyntaxKind::VariableDeclarationList
}

// Go: ast/ast_generated.go:1989 IsObjectBindingPattern
#[must_use]
pub fn is_object_binding_pattern(node: Node) -> bool {
    node.kind() == SyntaxKind::ObjectBindingPattern
}

// Go: ast/ast_generated.go:1993 IsArrayBindingPattern
#[must_use]
pub fn is_array_binding_pattern(node: Node) -> bool {
    node.kind() == SyntaxKind::ArrayBindingPattern
}

// Go: ast/ast_generated.go:2052 IsParameterDeclaration
#[must_use]
pub fn is_parameter_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::Parameter
}

// Go: ast/ast_generated.go:2107 IsBindingElement
#[must_use]
pub fn is_binding_element(node: Node) -> bool {
    node.kind() == SyntaxKind::BindingElement
}

// Go: ast/ast_generated.go:2146 IsMissingDeclaration
#[must_use]
pub fn is_missing_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::MissingDeclaration
}

// Go: ast/ast_generated.go:2208 IsFunctionDeclaration
#[must_use]
pub fn is_function_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::FunctionDeclaration
}

// Go: ast/ast_generated.go:2259 IsClassDeclaration
#[must_use]
pub fn is_class_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::ClassDeclaration
}

// Go: ast/ast_generated.go:2309 IsClassExpression
#[must_use]
pub fn is_class_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::ClassExpression
}

// Go: ast/ast_generated.go:2350 IsHeritageClause
#[must_use]
pub fn is_heritage_clause(node: Node) -> bool {
    node.kind() == SyntaxKind::HeritageClause
}

// Go: ast/ast_generated.go:2407 IsInterfaceDeclaration
#[must_use]
pub fn is_interface_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::InterfaceDeclaration
}

// Go: ast/ast_generated.go:2485 IsTypeAliasDeclaration
#[must_use]
pub fn is_type_alias_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeAliasDeclaration
}

// Go: ast/ast_generated.go:2489 IsJSTypeAliasDeclaration
#[must_use]
pub fn is_js_type_alias_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::JsTypeAliasDeclaration
}

// Go: ast/ast_generated.go:2534 IsEnumMember
#[must_use]
pub fn is_enum_member(node: Node) -> bool {
    node.kind() == SyntaxKind::EnumMember
}

// Go: ast/ast_generated.go:2583 IsEnumDeclaration
#[must_use]
pub fn is_enum_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::EnumDeclaration
}

// Go: ast/ast_generated.go:2626 IsModuleBlock
#[must_use]
pub fn is_module_block(node: Node) -> bool {
    node.kind() == SyntaxKind::ModuleBlock
}

// Go: ast/ast_generated.go:2647 IsNotEmittedStatement
#[must_use]
pub fn is_not_emitted_statement(node: Node) -> bool {
    node.kind() == SyntaxKind::NotEmittedStatement
}

// Go: ast/ast_generated.go:2669 IsNotEmittedTypeElement
#[must_use]
pub fn is_not_emitted_type_element(node: Node) -> bool {
    node.kind() == SyntaxKind::NotEmittedTypeElement
}

// Go: ast/ast_generated.go:2748 IsImportDeclaration
#[must_use]
pub fn is_import_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::ImportDeclaration
}

// Go: ast/ast_generated.go:2752 IsJSImportDeclaration
#[must_use]
pub fn is_js_import_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::JsImportDeclaration
}

// Go: ast/ast_generated.go:2794 IsExternalModuleReference
#[must_use]
pub fn is_external_module_reference(node: Node) -> bool {
    node.kind() == SyntaxKind::ExternalModuleReference
}

// Go: ast/ast_generated.go:2842 IsNamespaceImport
#[must_use]
pub fn is_namespace_import(node: Node) -> bool {
    node.kind() == SyntaxKind::NamespaceImport
}

// Go: ast/ast_generated.go:2885 IsNamedImports
#[must_use]
pub fn is_named_imports(node: Node) -> bool {
    node.kind() == SyntaxKind::NamedImports
}

// Go: ast/ast_generated.go:2931 IsExportAssignment
#[must_use]
pub fn is_export_assignment(node: Node) -> bool {
    node.kind() == SyntaxKind::ExportAssignment
}

// Go: ast/ast_generated.go:2977 IsNamespaceExportDeclaration
#[must_use]
pub fn is_namespace_export_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::NamespaceExportDeclaration
}

// Go: ast/ast_generated.go:3024 IsNamespaceExport
#[must_use]
pub fn is_namespace_export(node: Node) -> bool {
    node.kind() == SyntaxKind::NamespaceExport
}

// Go: ast/ast_generated.go:3067 IsNamedExports
#[must_use]
pub fn is_named_exports(node: Node) -> bool {
    node.kind() == SyntaxKind::NamedExports
}

// Go: ast/ast_generated.go:3116 IsExportSpecifier
#[must_use]
pub fn is_export_specifier(node: Node) -> bool {
    node.kind() == SyntaxKind::ExportSpecifier
}

// Go: ast/ast_generated.go:3159 IsCallSignatureDeclaration
#[must_use]
pub fn is_call_signature_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::CallSignature
}

// Go: ast/ast_generated.go:3202 IsConstructSignatureDeclaration
#[must_use]
pub fn is_construct_signature_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::ConstructSignature
}

// Go: ast/ast_generated.go:3255 IsConstructorDeclaration
#[must_use]
pub fn is_constructor_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::Constructor
}

// Go: ast/ast_generated.go:3308 IsGetAccessorDeclaration
#[must_use]
pub fn is_get_accessor_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::GetAccessor
}

// Go: ast/ast_generated.go:3361 IsSetAccessorDeclaration
#[must_use]
pub fn is_set_accessor_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::SetAccessor
}

// Go: ast/ast_generated.go:3406 IsIndexSignatureDeclaration
#[must_use]
pub fn is_index_signature_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::IndexSignature
}

// Go: ast/ast_generated.go:3461 IsMethodSignatureDeclaration
#[must_use]
pub fn is_method_signature_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::MethodSignature
}

// Go: ast/ast_generated.go:3524 IsMethodDeclaration
#[must_use]
pub fn is_method_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::MethodDeclaration
}

// Go: ast/ast_generated.go:3578 IsPropertySignatureDeclaration
#[must_use]
pub fn is_property_signature_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::PropertySignature
}

// Go: ast/ast_generated.go:3632 IsPropertyDeclaration
#[must_use]
pub fn is_property_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::PropertyDeclaration
}

// Go: ast/ast_generated.go:3655 IsSemicolonClassElement
#[must_use]
pub fn is_semicolon_class_element(node: Node) -> bool {
    node.kind() == SyntaxKind::SemicolonClassElement
}

// Go: ast/ast_generated.go:3700 IsClassStaticBlockDeclaration
#[must_use]
pub fn is_class_static_block_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::ClassStaticBlockDeclaration
}

// Go: ast/ast_generated.go:3721 IsOmittedExpression
#[must_use]
pub fn is_omitted_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::OmittedExpression
}

// Go: ast/ast_generated.go:3743 IsKeywordExpression
#[must_use]
pub fn is_keyword_expression(node: Node) -> bool {
    // PORT: Go lists 5 more `case` labels with empty bodies before the
    // last one. Go `switch` does not fall through, so those kinds reach
    // `return false`. We keep that behavior. Empty-case kinds:
    //   KindNullKeyword, KindTrueKeyword, KindFalseKeyword, KindThisKeyword, KindSuperKeyword
    match node.kind() {
        SyntaxKind::ImportKeyword => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:3776 IsStringLiteral
#[must_use]
pub fn is_string_literal(node: Node) -> bool {
    node.kind() == SyntaxKind::StringLiteral
}

// Go: ast/ast_generated.go:3800 IsNumericLiteral
#[must_use]
pub fn is_numeric_literal(node: Node) -> bool {
    node.kind() == SyntaxKind::NumericLiteral
}

// Go: ast/ast_generated.go:3824 IsBigIntLiteral
#[must_use]
pub fn is_big_int_literal(node: Node) -> bool {
    node.kind() == SyntaxKind::BigIntLiteral
}

// Go: ast/ast_generated.go:3848 IsRegularExpressionLiteral
#[must_use]
pub fn is_regular_expression_literal(node: Node) -> bool {
    node.kind() == SyntaxKind::RegularExpressionLiteral
}

// Go: ast/ast_generated.go:3874 IsNoSubstitutionTemplateLiteral
#[must_use]
pub fn is_no_substitution_template_literal(node: Node) -> bool {
    node.kind() == SyntaxKind::NoSubstitutionTemplateLiteral
}

// Go: ast/ast_generated.go:3926 IsBinaryExpression
#[must_use]
pub fn is_binary_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::BinaryExpression
}

// Go: ast/ast_generated.go:3970 IsPrefixUnaryExpression
#[must_use]
pub fn is_prefix_unary_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::PrefixUnaryExpression
}

// Go: ast/ast_generated.go:4014 IsPostfixUnaryExpression
#[must_use]
pub fn is_postfix_unary_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::PostfixUnaryExpression
}

// Go: ast/ast_generated.go:4054 IsYieldExpression
#[must_use]
pub fn is_yield_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::YieldExpression
}

// Go: ast/ast_generated.go:4109 IsArrowFunction
#[must_use]
pub fn is_arrow_function(node: Node) -> bool {
    node.kind() == SyntaxKind::ArrowFunction
}

// Go: ast/ast_generated.go:4171 IsFunctionExpression
#[must_use]
pub fn is_function_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::FunctionExpression
}

// Go: ast/ast_generated.go:4211 IsAsExpression
#[must_use]
pub fn is_as_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::AsExpression
}

// Go: ast/ast_generated.go:4251 IsSatisfiesExpression
#[must_use]
pub fn is_satisfies_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::SatisfiesExpression
}

// Go: ast/ast_generated.go:4310 IsConditionalExpression
#[must_use]
pub fn is_conditional_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::ConditionalExpression
}

// Go: ast/ast_generated.go:4360 IsPropertyAccessExpression
#[must_use]
pub fn is_property_access_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::PropertyAccessExpression
}

// Go: ast/ast_generated.go:4412 IsElementAccessExpression
#[must_use]
pub fn is_element_access_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::ElementAccessExpression
}

// Go: ast/ast_generated.go:4463 IsCallExpression
#[must_use]
pub fn is_call_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::CallExpression
}

// Go: ast/ast_generated.go:4506 IsNewExpression
#[must_use]
pub fn is_new_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::NewExpression
}

// Go: ast/ast_generated.go:4552 IsMetaProperty
#[must_use]
pub fn is_meta_property(node: Node) -> bool {
    node.kind() == SyntaxKind::MetaProperty
}

// Go: ast/ast_generated.go:4592 IsNonNullExpression
#[must_use]
pub fn is_non_null_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::NonNullExpression
}

// Go: ast/ast_generated.go:4630 IsSpreadElement
#[must_use]
pub fn is_spread_element(node: Node) -> bool {
    node.kind() == SyntaxKind::SpreadElement
}

// Go: ast/ast_generated.go:4676 IsTemplateExpression
#[must_use]
pub fn is_template_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::TemplateExpression
}

// Go: ast/ast_generated.go:4721 IsTemplateSpan
#[must_use]
pub fn is_template_span(node: Node) -> bool {
    node.kind() == SyntaxKind::TemplateSpan
}

// Go: ast/ast_generated.go:4771 IsTaggedTemplateExpression
#[must_use]
pub fn is_tagged_template_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::TaggedTemplateExpression
}

// Go: ast/ast_generated.go:4813 IsParenthesizedExpression
#[must_use]
pub fn is_parenthesized_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::ParenthesizedExpression
}

// Go: ast/ast_generated.go:4858 IsArrayLiteralExpression
#[must_use]
pub fn is_array_literal_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::ArrayLiteralExpression
}

// Go: ast/ast_generated.go:4904 IsObjectLiteralExpression
#[must_use]
pub fn is_object_literal_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::ObjectLiteralExpression
}

// Go: ast/ast_generated.go:4944 IsSpreadAssignment
#[must_use]
pub fn is_spread_assignment(node: Node) -> bool {
    node.kind() == SyntaxKind::SpreadAssignment
}

// Go: ast/ast_generated.go:4998 IsPropertyAssignment
#[must_use]
pub fn is_property_assignment(node: Node) -> bool {
    node.kind() == SyntaxKind::PropertyAssignment
}

// Go: ast/ast_generated.go:5055 IsShorthandPropertyAssignment
#[must_use]
pub fn is_shorthand_property_assignment(node: Node) -> bool {
    node.kind() == SyntaxKind::ShorthandPropertyAssignment
}

// Go: ast/ast_generated.go:5097 IsDeleteExpression
#[must_use]
pub fn is_delete_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::DeleteExpression
}

// Go: ast/ast_generated.go:5139 IsTypeOfExpression
#[must_use]
pub fn is_type_of_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeOfExpression
}

// Go: ast/ast_generated.go:5181 IsVoidExpression
#[must_use]
pub fn is_void_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::VoidExpression
}

// Go: ast/ast_generated.go:5219 IsAwaitExpression
#[must_use]
pub fn is_await_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::AwaitExpression
}

// Go: ast/ast_generated.go:5259 IsTypeAssertion
#[must_use]
pub fn is_type_assertion(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeAssertionExpression
}

// Go: ast/ast_generated.go:5280 IsKeywordTypeNode
#[must_use]
pub fn is_keyword_type_node(node: Node) -> bool {
    // PORT: Go lists 11 more `case` labels with empty bodies before the
    // last one. Go `switch` does not fall through, so those kinds reach
    // `return false`. We keep that behavior. Empty-case kinds:
    //   KindAnyKeyword, KindBigIntKeyword, KindBooleanKeyword, KindIntrinsicKeyword, KindNeverKeyword, KindNumberKeyword
    //   KindObjectKeyword, KindStringKeyword, KindSymbolKeyword, KindUndefinedKeyword, KindUnknownKeyword
    match node.kind() {
        SyntaxKind::VoidKeyword => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:5333 IsUnionTypeNode
#[must_use]
pub fn is_union_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::UnionType
}

// Go: ast/ast_generated.go:5371 IsIntersectionTypeNode
#[must_use]
pub fn is_intersection_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::IntersectionType
}

// Go: ast/ast_generated.go:5419 IsConditionalTypeNode
#[must_use]
pub fn is_conditional_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::ConditionalType
}

// Go: ast/ast_generated.go:5459 IsTypeOperatorNode
#[must_use]
pub fn is_type_operator_node(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeOperator
}

// Go: ast/ast_generated.go:5497 IsInferTypeNode
#[must_use]
pub fn is_infer_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::InferType
}

// Go: ast/ast_generated.go:5535 IsArrayTypeNode
#[must_use]
pub fn is_array_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::ArrayType
}

// Go: ast/ast_generated.go:5575 IsIndexedAccessTypeNode
#[must_use]
pub fn is_indexed_access_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::IndexedAccessType
}

// Go: ast/ast_generated.go:5614 IsTypeReferenceNode
#[must_use]
pub fn is_type_reference_node(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeReference
}

// Go: ast/ast_generated.go:5655 IsExpressionWithTypeArguments
#[must_use]
pub fn is_expression_with_type_arguments(node: Node) -> bool {
    node.kind() == SyntaxKind::ExpressionWithTypeArguments
}

// Go: ast/ast_generated.go:5693 IsLiteralTypeNode
#[must_use]
pub fn is_literal_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::LiteralType
}

// Go: ast/ast_generated.go:5714 IsThisTypeNode
#[must_use]
pub fn is_this_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::ThisType
}

// Go: ast/ast_generated.go:5756 IsTypePredicateNode
#[must_use]
pub fn is_type_predicate_node(node: Node) -> bool {
    node.kind() == SyntaxKind::TypePredicate
}

// Go: ast/ast_generated.go:5806 IsImportAttribute
#[must_use]
pub fn is_import_attribute(node: Node) -> bool {
    node.kind() == SyntaxKind::ImportAttribute
}

// Go: ast/ast_generated.go:5853 IsImportAttributes
#[must_use]
pub fn is_import_attributes(node: Node) -> bool {
    node.kind() == SyntaxKind::ImportAttributes
}

// Go: ast/ast_generated.go:5892 IsTypeQueryNode
#[must_use]
pub fn is_type_query_node(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeQuery
}

// Go: ast/ast_generated.go:5947 IsMappedTypeNode
#[must_use]
pub fn is_mapped_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::MappedType
}

// Go: ast/ast_generated.go:5986 IsTypeLiteralNode
#[must_use]
pub fn is_type_literal_node(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeLiteral
}

// Go: ast/ast_generated.go:6024 IsTupleTypeNode
#[must_use]
pub fn is_tuple_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::TupleType
}

// Go: ast/ast_generated.go:6076 IsNamedTupleMember
#[must_use]
pub fn is_named_tuple_member(node: Node) -> bool {
    node.kind() == SyntaxKind::NamedTupleMember
}

// Go: ast/ast_generated.go:6114 IsOptionalTypeNode
#[must_use]
pub fn is_optional_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::OptionalType
}

// Go: ast/ast_generated.go:6152 IsRestTypeNode
#[must_use]
pub fn is_rest_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::RestType
}

// Go: ast/ast_generated.go:6190 IsParenthesizedTypeNode
#[must_use]
pub fn is_parenthesized_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::ParenthesizedType
}

// Go: ast/ast_generated.go:6230 IsFunctionTypeNode
#[must_use]
pub fn is_function_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::FunctionType
}

// Go: ast/ast_generated.go:6274 IsConstructorTypeNode
#[must_use]
pub fn is_constructor_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::ConstructorType
}

// Go: ast/ast_generated.go:6300 IsTemplateHead
#[must_use]
pub fn is_template_head(node: Node) -> bool {
    node.kind() == SyntaxKind::TemplateHead
}

// Go: ast/ast_generated.go:6326 IsTemplateMiddle
#[must_use]
pub fn is_template_middle(node: Node) -> bool {
    node.kind() == SyntaxKind::TemplateMiddle
}

// Go: ast/ast_generated.go:6352 IsTemplateTail
#[must_use]
pub fn is_template_tail(node: Node) -> bool {
    node.kind() == SyntaxKind::TemplateTail
}

// Go: ast/ast_generated.go:6392 IsTemplateLiteralTypeNode
#[must_use]
pub fn is_template_literal_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::TemplateLiteralType
}

// Go: ast/ast_generated.go:6432 IsTemplateLiteralTypeSpan
#[must_use]
pub fn is_template_literal_type_span(node: Node) -> bool {
    node.kind() == SyntaxKind::TemplateLiteralTypeSpan
}

// Go: ast/ast_generated.go:6474 IsSyntheticExpression
#[must_use]
pub fn is_synthetic_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::SyntheticExpression
}

// Go: ast/ast_generated.go:6516 IsPartiallyEmittedExpression
#[must_use]
pub fn is_partially_emitted_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::PartiallyEmittedExpression
}

// Go: ast/ast_generated.go:6559 IsJsxElement
#[must_use]
pub fn is_jsx_element(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxElement
}

// Go: ast/ast_generated.go:6599 IsJsxAttributes
#[must_use]
pub fn is_jsx_attributes(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxAttributes
}

// Go: ast/ast_generated.go:6644 IsJsxNamespacedName
#[must_use]
pub fn is_jsx_namespaced_name(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxNamespacedName
}

// Go: ast/ast_generated.go:6687 IsJsxOpeningElement
#[must_use]
pub fn is_jsx_opening_element(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxOpeningElement
}

// Go: ast/ast_generated.go:6730 IsJsxSelfClosingElement
#[must_use]
pub fn is_jsx_self_closing_element(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxSelfClosingElement
}

// Go: ast/ast_generated.go:6773 IsJsxFragment
#[must_use]
pub fn is_jsx_fragment(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxFragment
}

// Go: ast/ast_generated.go:6794 IsJsxOpeningFragment
#[must_use]
pub fn is_jsx_opening_fragment(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxOpeningFragment
}

// Go: ast/ast_generated.go:6815 IsJsxClosingFragment
#[must_use]
pub fn is_jsx_closing_fragment(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxClosingFragment
}

// Go: ast/ast_generated.go:6861 IsJsxAttribute
#[must_use]
pub fn is_jsx_attribute(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxAttribute
}

// Go: ast/ast_generated.go:6900 IsJsxSpreadAttribute
#[must_use]
pub fn is_jsx_spread_attribute(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxSpreadAttribute
}

// Go: ast/ast_generated.go:6938 IsJsxClosingElement
#[must_use]
pub fn is_jsx_closing_element(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxClosingElement
}

// Go: ast/ast_generated.go:6978 IsJsxExpression
#[must_use]
pub fn is_jsx_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxExpression
}

// Go: ast/ast_generated.go:7004 IsJsxText
#[must_use]
pub fn is_jsx_text(node: Node) -> bool {
    node.kind() == SyntaxKind::JsxText
}

// Go: ast/ast_generated.go:7043 IsSyntaxList
#[must_use]
pub fn is_syntax_list(node: Node) -> bool {
    node.kind() == SyntaxKind::SyntaxList
}

// Go: ast/ast_generated.go:7083 IsJSDoc
#[must_use]
pub fn is_js_doc(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDoc
}

// Go: ast/ast_generated.go:7121 IsJSDocTypeExpression
#[must_use]
pub fn is_js_doc_type_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocTypeExpression
}

// Go: ast/ast_generated.go:7159 IsJSDocNonNullableType
#[must_use]
pub fn is_js_doc_non_nullable_type(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocNonNullableType
}

// Go: ast/ast_generated.go:7197 IsJSDocNullableType
#[must_use]
pub fn is_js_doc_nullable_type(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocNullableType
}

// Go: ast/ast_generated.go:7218 IsJSDocAllType
#[must_use]
pub fn is_js_doc_all_type(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocAllType
}

// Go: ast/ast_generated.go:7256 IsJSDocVariadicType
#[must_use]
pub fn is_js_doc_variadic_type(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocVariadicType
}

// Go: ast/ast_generated.go:7294 IsJSDocOptionalType
#[must_use]
pub fn is_js_doc_optional_type(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocOptionalType
}

// Go: ast/ast_generated.go:7334 IsJSDocTypeTag
#[must_use]
pub fn is_js_doc_type_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocTypeTag
}

// Go: ast/ast_generated.go:7372 IsJSDocUnknownTag
#[must_use]
pub fn is_js_doc_unknown_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocUnknownTag
}

// Go: ast/ast_generated.go:7417 IsJSDocTemplateTag
#[must_use]
pub fn is_js_doc_template_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocTemplateTag
}

// Go: ast/ast_generated.go:7457 IsJSDocReturnTag
#[must_use]
pub fn is_js_doc_return_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocReturnTag
}

// Go: ast/ast_generated.go:7495 IsJSDocPublicTag
#[must_use]
pub fn is_js_doc_public_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocPublicTag
}

// Go: ast/ast_generated.go:7533 IsJSDocPrivateTag
#[must_use]
pub fn is_js_doc_private_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocPrivateTag
}

// Go: ast/ast_generated.go:7571 IsJSDocProtectedTag
#[must_use]
pub fn is_js_doc_protected_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocProtectedTag
}

// Go: ast/ast_generated.go:7609 IsJSDocReadonlyTag
#[must_use]
pub fn is_js_doc_readonly_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocReadonlyTag
}

// Go: ast/ast_generated.go:7647 IsJSDocOverrideTag
#[must_use]
pub fn is_js_doc_override_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocOverrideTag
}

// Go: ast/ast_generated.go:7685 IsJSDocDeprecatedTag
#[must_use]
pub fn is_js_doc_deprecated_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocDeprecatedTag
}

// Go: ast/ast_generated.go:7725 IsJSDocSeeTag
#[must_use]
pub fn is_js_doc_see_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocSeeTag
}

// Go: ast/ast_generated.go:7765 IsJSDocImplementsTag
#[must_use]
pub fn is_js_doc_implements_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocImplementsTag
}

// Go: ast/ast_generated.go:7805 IsJSDocAugmentsTag
#[must_use]
pub fn is_js_doc_augments_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocAugmentsTag
}

// Go: ast/ast_generated.go:7845 IsJSDocSatisfiesTag
#[must_use]
pub fn is_js_doc_satisfies_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocSatisfiesTag
}

// Go: ast/ast_generated.go:7885 IsJSDocThrowsTag
#[must_use]
pub fn is_js_doc_throws_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocThrowsTag
}

// Go: ast/ast_generated.go:7925 IsJSDocThisTag
#[must_use]
pub fn is_js_doc_this_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocThisTag
}

// Go: ast/ast_generated.go:7973 IsJSDocImportTag
#[must_use]
pub fn is_js_doc_import_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocImportTag
}

// Go: ast/ast_generated.go:8022 IsJSDocCallbackTag
#[must_use]
pub fn is_js_doc_callback_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocCallbackTag
}

// Go: ast/ast_generated.go:8062 IsJSDocOverloadTag
#[must_use]
pub fn is_js_doc_overload_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocOverloadTag
}

// Go: ast/ast_generated.go:8111 IsJSDocTypedefTag
#[must_use]
pub fn is_js_doc_typedef_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocTypedefTag
}

// Go: ast/ast_generated.go:8151 IsJSDocSignature
#[must_use]
pub fn is_js_doc_signature(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocSignature
}

// Go: ast/ast_generated.go:8193 IsJSDocNameReference
#[must_use]
pub fn is_js_doc_name_reference(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocNameReference
}

// Go: ast/ast_generated.go:8201 IsSourceFile
#[must_use]
pub fn is_source_file(node: Node) -> bool {
    node.kind() == SyntaxKind::SourceFile
}

// Go: ast/ast_generated.go:8254 IsModuleDeclaration
#[must_use]
pub fn is_module_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::ModuleDeclaration
}

// Go: ast/ast_generated.go:8305 IsImportEqualsDeclaration
#[must_use]
pub fn is_import_equals_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::ImportEqualsDeclaration
}

// Go: ast/ast_generated.go:8356 IsExportDeclaration
#[must_use]
pub fn is_export_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::ExportDeclaration
}

// Go: ast/ast_generated.go:8404 IsImportTypeNode
#[must_use]
pub fn is_import_type_node(node: Node) -> bool {
    node.kind() == SyntaxKind::ImportType
}

// Go: ast/ast_generated.go:8453 IsImportClause
#[must_use]
pub fn is_import_clause(node: Node) -> bool {
    node.kind() == SyntaxKind::ImportClause
}

// Go: ast/ast_generated.go:8502 IsImportSpecifier
#[must_use]
pub fn is_import_specifier(node: Node) -> bool {
    node.kind() == SyntaxKind::ImportSpecifier
}

// Go: ast/ast_generated.go:8525 IsJSDocText
#[must_use]
pub fn is_js_doc_text(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocText
}

// Go: ast/ast_generated.go:8569 IsJSDocLink
#[must_use]
pub fn is_js_doc_link(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocLink
}

// Go: ast/ast_generated.go:8613 IsJSDocLinkPlain
#[must_use]
pub fn is_js_doc_link_plain(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocLinkPlain
}

// Go: ast/ast_generated.go:8657 IsJSDocLinkCode
#[must_use]
pub fn is_js_doc_link_code(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocLinkCode
}

// Go: ast/ast_generated.go:8713 IsTypeParameterDeclaration
#[must_use]
pub fn is_type_parameter_declaration(node: Node) -> bool {
    node.kind() == SyntaxKind::TypeParameter
}

// Go: ast/ast_generated.go:8758 IsSyntheticReferenceExpression
#[must_use]
pub fn is_synthetic_reference_expression(node: Node) -> bool {
    node.kind() == SyntaxKind::SyntheticReferenceExpression
}

// Go: ast/ast_generated.go:8800 IsJSDocTypeLiteral
#[must_use]
pub fn is_js_doc_type_literal(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocTypeLiteral
}

// Go: ast/ast_generated.go:8850 IsJSDocParameterTag
#[must_use]
pub fn is_js_doc_parameter_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocParameterTag
}

// Go: ast/ast_generated.go:8854 IsJSDocPropertyTag
#[must_use]
pub fn is_js_doc_property_tag(node: Node) -> bool {
    node.kind() == SyntaxKind::JsDocPropertyTag
}

// Go: ast/ast_generated.go:9634 IsTriviaKind
#[must_use]
pub fn is_trivia_kind(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::SingleLineCommentTrivia
        | SyntaxKind::MultiLineCommentTrivia
        | SyntaxKind::NewLineTrivia
        | SyntaxKind::WhitespaceTrivia
        | SyntaxKind::ConflictMarkerTrivia => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9642 IsLiteralKind
#[must_use]
pub fn is_literal_kind(kind: SyntaxKind) -> bool {
    (kind as u16) >= (SyntaxKind::FIRST_LITERAL_TOKEN as u16) && (kind as u16) <= (SyntaxKind::LAST_LITERAL_TOKEN as u16)
}

// Go: ast/ast_generated.go:9646 IsPseudoLiteralKind
#[must_use]
pub fn is_pseudo_literal_kind(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::TemplateHead
        | SyntaxKind::TemplateMiddle
        | SyntaxKind::TemplateTail => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9654 IsPunctuationKind
#[must_use]
pub fn is_punctuation_kind(kind: SyntaxKind) -> bool {
    (kind as u16) >= (SyntaxKind::FIRST_PUNCTUATION as u16) && (kind as u16) <= (SyntaxKind::LAST_PUNCTUATION as u16)
}

// Go: ast/ast_generated.go:9658 IsKeywordKind
#[must_use]
pub fn is_keyword_kind(kind: SyntaxKind) -> bool {
    (kind as u16) >= (SyntaxKind::FIRST_KEYWORD as u16) && (kind as u16) <= (SyntaxKind::LAST_KEYWORD as u16)
}

// Go: ast/ast_generated.go:9662 IsModifierKind
#[must_use]
pub fn is_modifier_kind(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AbstractKeyword
        | SyntaxKind::AccessorKeyword
        | SyntaxKind::AsyncKeyword
        | SyntaxKind::ConstKeyword
        | SyntaxKind::DeclareKeyword
        | SyntaxKind::DefaultKeyword
        | SyntaxKind::ExportKeyword
        | SyntaxKind::InKeyword
        | SyntaxKind::PrivateKeyword
        | SyntaxKind::ProtectedKeyword
        | SyntaxKind::PublicKeyword
        | SyntaxKind::ReadonlyKeyword
        | SyntaxKind::OutKeyword
        | SyntaxKind::OverrideKeyword
        | SyntaxKind::StaticKeyword => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9670 IsKeywordTypeKind
#[must_use]
pub fn is_keyword_type_kind(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AnyKeyword
        | SyntaxKind::BigIntKeyword
        | SyntaxKind::BooleanKeyword
        | SyntaxKind::IntrinsicKeyword
        | SyntaxKind::NeverKeyword
        | SyntaxKind::NumberKeyword
        | SyntaxKind::ObjectKeyword
        | SyntaxKind::StringKeyword
        | SyntaxKind::SymbolKeyword
        | SyntaxKind::UndefinedKeyword
        | SyntaxKind::UnknownKeyword
        | SyntaxKind::VoidKeyword => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9678 IsKeywordExpressionKind
#[must_use]
pub fn is_keyword_expression_kind(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::NullKeyword
        | SyntaxKind::TrueKeyword
        | SyntaxKind::FalseKeyword
        | SyntaxKind::ThisKeyword
        | SyntaxKind::SuperKeyword
        | SyntaxKind::ImportKeyword => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9686 IsTokenKind
#[must_use]
pub fn is_token_kind(kind: SyntaxKind) -> bool {
    (kind as u16) >= (SyntaxKind::FIRST_TOKEN as u16) && (kind as u16) <= (SyntaxKind::LAST_TOKEN as u16)
}

// Go: ast/ast_generated.go:9690 IsJsxTokenKind
#[must_use]
pub fn is_jsx_token_kind(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::LessThanSlashToken
        | SyntaxKind::EndOfFile
        | SyntaxKind::ConflictMarkerTrivia
        | SyntaxKind::JsxText
        | SyntaxKind::JsxTextAllWhiteSpaces
        | SyntaxKind::OpenBraceToken
        | SyntaxKind::LessThanToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9698 IsJSDocNodeKind
#[must_use]
pub fn is_js_doc_node_kind(kind: SyntaxKind) -> bool {
    (kind as u16) >= (SyntaxKind::FIRST_JS_DOC_NODE as u16) && (kind as u16) <= (SyntaxKind::LAST_JS_DOC_NODE as u16)
}

// Go: ast/ast_generated.go:9702 IsImportPhaseModifierKind
#[must_use]
pub fn is_import_phase_modifier_kind(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::TypeKeyword
        | SyntaxKind::DeferKeyword => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9710 IsPostfixUnaryOperator
#[must_use]
pub fn is_postfix_unary_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::PlusPlusToken
        | SyntaxKind::MinusMinusToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9718 IsPrefixUnaryOperator
#[must_use]
pub fn is_prefix_unary_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::TildeToken
        | SyntaxKind::ExclamationToken
        | SyntaxKind::PlusPlusToken
        | SyntaxKind::MinusMinusToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9726 IsAssignmentOperator
#[must_use]
pub fn is_assignment_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::EqualsToken
        | SyntaxKind::PlusEqualsToken
        | SyntaxKind::MinusEqualsToken
        | SyntaxKind::AsteriskAsteriskEqualsToken
        | SyntaxKind::AsteriskEqualsToken
        | SyntaxKind::SlashEqualsToken
        | SyntaxKind::PercentEqualsToken
        | SyntaxKind::AmpersandEqualsToken
        | SyntaxKind::BarEqualsToken
        | SyntaxKind::CaretEqualsToken
        | SyntaxKind::LessThanLessThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanEqualsToken
        | SyntaxKind::BarBarEqualsToken
        | SyntaxKind::AmpersandAmpersandEqualsToken
        | SyntaxKind::QuestionQuestionEqualsToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9734 IsBinaryOperator
#[must_use]
pub fn is_binary_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::QuestionQuestionToken
        | SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken
        | SyntaxKind::LessThanToken
        | SyntaxKind::LessThanEqualsToken
        | SyntaxKind::GreaterThanToken
        | SyntaxKind::GreaterThanEqualsToken
        | SyntaxKind::InstanceOfKeyword
        | SyntaxKind::InKeyword
        | SyntaxKind::EqualsEqualsToken
        | SyntaxKind::EqualsEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsToken
        | SyntaxKind::AmpersandToken
        | SyntaxKind::BarToken
        | SyntaxKind::CaretToken
        | SyntaxKind::AmpersandAmpersandToken
        | SyntaxKind::BarBarToken
        | SyntaxKind::EqualsToken
        | SyntaxKind::PlusEqualsToken
        | SyntaxKind::MinusEqualsToken
        | SyntaxKind::AsteriskAsteriskEqualsToken
        | SyntaxKind::AsteriskEqualsToken
        | SyntaxKind::SlashEqualsToken
        | SyntaxKind::PercentEqualsToken
        | SyntaxKind::AmpersandEqualsToken
        | SyntaxKind::BarEqualsToken
        | SyntaxKind::CaretEqualsToken
        | SyntaxKind::LessThanLessThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanEqualsToken
        | SyntaxKind::BarBarEqualsToken
        | SyntaxKind::AmpersandAmpersandEqualsToken
        | SyntaxKind::QuestionQuestionEqualsToken
        | SyntaxKind::CommaToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9742 IsExponentiationOperator
#[must_use]
pub fn is_exponentiation_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9750 IsMultiplicativeOperator
#[must_use]
pub fn is_multiplicative_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9758 IsMultiplicativeOperatorOrHigher
#[must_use]
pub fn is_multiplicative_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9766 IsAdditiveOperator
#[must_use]
pub fn is_additive_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::PlusToken
        | SyntaxKind::MinusToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9774 IsAdditiveOperatorOrHigher
#[must_use]
pub fn is_additive_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9782 IsShiftOperator
#[must_use]
pub fn is_shift_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9790 IsShiftOperatorOrHigher
#[must_use]
pub fn is_shift_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9798 IsRelationalOperator
#[must_use]
pub fn is_relational_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::LessThanToken
        | SyntaxKind::LessThanEqualsToken
        | SyntaxKind::GreaterThanToken
        | SyntaxKind::GreaterThanEqualsToken
        | SyntaxKind::InstanceOfKeyword
        | SyntaxKind::InKeyword => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9806 IsRelationalOperatorOrHigher
#[must_use]
pub fn is_relational_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken
        | SyntaxKind::LessThanToken
        | SyntaxKind::LessThanEqualsToken
        | SyntaxKind::GreaterThanToken
        | SyntaxKind::GreaterThanEqualsToken
        | SyntaxKind::InstanceOfKeyword
        | SyntaxKind::InKeyword => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9814 IsEqualityOperator
#[must_use]
pub fn is_equality_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::EqualsEqualsToken
        | SyntaxKind::EqualsEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9822 IsEqualityOperatorOrHigher
#[must_use]
pub fn is_equality_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken
        | SyntaxKind::LessThanToken
        | SyntaxKind::LessThanEqualsToken
        | SyntaxKind::GreaterThanToken
        | SyntaxKind::GreaterThanEqualsToken
        | SyntaxKind::InstanceOfKeyword
        | SyntaxKind::InKeyword
        | SyntaxKind::EqualsEqualsToken
        | SyntaxKind::EqualsEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9830 IsBitwiseOperator
#[must_use]
pub fn is_bitwise_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AmpersandToken
        | SyntaxKind::BarToken
        | SyntaxKind::CaretToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9838 IsBitwiseOperatorOrHigher
#[must_use]
pub fn is_bitwise_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken
        | SyntaxKind::LessThanToken
        | SyntaxKind::LessThanEqualsToken
        | SyntaxKind::GreaterThanToken
        | SyntaxKind::GreaterThanEqualsToken
        | SyntaxKind::InstanceOfKeyword
        | SyntaxKind::InKeyword
        | SyntaxKind::EqualsEqualsToken
        | SyntaxKind::EqualsEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsToken
        | SyntaxKind::AmpersandToken
        | SyntaxKind::BarToken
        | SyntaxKind::CaretToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9846 IsLogicalOperator
#[must_use]
pub fn is_logical_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AmpersandAmpersandToken
        | SyntaxKind::BarBarToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9854 IsLogicalOperatorOrHigher
#[must_use]
pub fn is_logical_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken
        | SyntaxKind::LessThanToken
        | SyntaxKind::LessThanEqualsToken
        | SyntaxKind::GreaterThanToken
        | SyntaxKind::GreaterThanEqualsToken
        | SyntaxKind::InstanceOfKeyword
        | SyntaxKind::InKeyword
        | SyntaxKind::EqualsEqualsToken
        | SyntaxKind::EqualsEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsToken
        | SyntaxKind::AmpersandToken
        | SyntaxKind::BarToken
        | SyntaxKind::CaretToken
        | SyntaxKind::AmpersandAmpersandToken
        | SyntaxKind::BarBarToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9862 IsCompoundAssignmentOperator
#[must_use]
pub fn is_compound_assignment_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::PlusEqualsToken
        | SyntaxKind::MinusEqualsToken
        | SyntaxKind::AsteriskAsteriskEqualsToken
        | SyntaxKind::AsteriskEqualsToken
        | SyntaxKind::SlashEqualsToken
        | SyntaxKind::PercentEqualsToken
        | SyntaxKind::AmpersandEqualsToken
        | SyntaxKind::BarEqualsToken
        | SyntaxKind::CaretEqualsToken
        | SyntaxKind::LessThanLessThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanEqualsToken
        | SyntaxKind::BarBarEqualsToken
        | SyntaxKind::AmpersandAmpersandEqualsToken
        | SyntaxKind::QuestionQuestionEqualsToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9870 IsAssignmentOperatorOrHigher
#[must_use]
pub fn is_assignment_operator_or_higher(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::QuestionQuestionToken
        | SyntaxKind::AsteriskAsteriskToken
        | SyntaxKind::AsteriskToken
        | SyntaxKind::SlashToken
        | SyntaxKind::PercentToken
        | SyntaxKind::PlusToken
        | SyntaxKind::MinusToken
        | SyntaxKind::LessThanLessThanToken
        | SyntaxKind::GreaterThanGreaterThanToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanToken
        | SyntaxKind::LessThanToken
        | SyntaxKind::LessThanEqualsToken
        | SyntaxKind::GreaterThanToken
        | SyntaxKind::GreaterThanEqualsToken
        | SyntaxKind::InstanceOfKeyword
        | SyntaxKind::InKeyword
        | SyntaxKind::EqualsEqualsToken
        | SyntaxKind::EqualsEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsEqualsToken
        | SyntaxKind::ExclamationEqualsToken
        | SyntaxKind::AmpersandToken
        | SyntaxKind::BarToken
        | SyntaxKind::CaretToken
        | SyntaxKind::AmpersandAmpersandToken
        | SyntaxKind::BarBarToken
        | SyntaxKind::EqualsToken
        | SyntaxKind::PlusEqualsToken
        | SyntaxKind::MinusEqualsToken
        | SyntaxKind::AsteriskAsteriskEqualsToken
        | SyntaxKind::AsteriskEqualsToken
        | SyntaxKind::SlashEqualsToken
        | SyntaxKind::PercentEqualsToken
        | SyntaxKind::AmpersandEqualsToken
        | SyntaxKind::BarEqualsToken
        | SyntaxKind::CaretEqualsToken
        | SyntaxKind::LessThanLessThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanGreaterThanEqualsToken
        | SyntaxKind::GreaterThanGreaterThanEqualsToken
        | SyntaxKind::BarBarEqualsToken
        | SyntaxKind::AmpersandAmpersandEqualsToken
        | SyntaxKind::QuestionQuestionEqualsToken => true,
        _ => false,
    }
}

// Go: ast/ast_generated.go:9878 IsLogicalOrCoalescingAssignmentOperator
#[must_use]
pub fn is_logical_or_coalescing_assignment_operator(kind: SyntaxKind) -> bool {
    match kind {
        SyntaxKind::AmpersandAmpersandEqualsToken
        | SyntaxKind::BarBarEqualsToken
        | SyntaxKind::QuestionQuestionEqualsToken => true,
        _ => false,
    }
}
