// Code generated by generate.mts; DO NOT EDIT.
//
// Rust port of typescript-go internal/lsp/lsproto/lsp_generated.go (pinned
// dc37b5249), generated from the same meta model by the ported generator.
// Meta model version 3.17.0

use crate::lsp::lsproto::prelude::*;

// Go: unmarshalParams
// PORT: Go switches on the Method consts; each arm here compares with the same const.
pub fn unmarshal_params(
    method: &Method,
    data: &[u8],
) -> Result<Option<Box<dyn AnyValue>>, GoError> {
    match method {
        m if *m == Method::TEXT_DOCUMENT_IMPLEMENTATION => {
            let v: Box<ImplementationParams> =
                unmarshal_ptr_to::<ImplementationParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_TYPE_DEFINITION => {
            let v: Box<TypeDefinitionParams> =
                unmarshal_ptr_to::<TypeDefinitionParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_WORKSPACE_FOLDERS => unmarshal_empty(data),
        m if *m == Method::WORKSPACE_CONFIGURATION => {
            let v: Box<ConfigurationParams> = unmarshal_ptr_to::<ConfigurationParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_DOCUMENT_COLOR => {
            let v: Box<DocumentColorParams> = unmarshal_ptr_to::<DocumentColorParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_COLOR_PRESENTATION => {
            let v: Box<ColorPresentationParams> =
                unmarshal_ptr_to::<ColorPresentationParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_FOLDING_RANGE => {
            let v: Box<FoldingRangeParams> = unmarshal_ptr_to::<FoldingRangeParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_FOLDING_RANGE_REFRESH => unmarshal_empty(data),
        m if *m == Method::TEXT_DOCUMENT_DECLARATION => {
            let v: Box<DeclarationParams> = unmarshal_ptr_to::<DeclarationParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_SELECTION_RANGE => {
            let v: Box<SelectionRangeParams> =
                unmarshal_ptr_to::<SelectionRangeParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WINDOW_WORK_DONE_PROGRESS_CREATE => {
            let v: Box<WorkDoneProgressCreateParams> =
                unmarshal_ptr_to::<WorkDoneProgressCreateParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_PREPARE_CALL_HIERARCHY => {
            let v: Box<CallHierarchyPrepareParams> =
                unmarshal_ptr_to::<CallHierarchyPrepareParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CALL_HIERARCHY_INCOMING_CALLS => {
            let v: Box<CallHierarchyIncomingCallsParams> =
                unmarshal_ptr_to::<CallHierarchyIncomingCallsParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CALL_HIERARCHY_OUTGOING_CALLS => {
            let v: Box<CallHierarchyOutgoingCallsParams> =
                unmarshal_ptr_to::<CallHierarchyOutgoingCallsParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL => {
            let v: Box<SemanticTokensParams> =
                unmarshal_ptr_to::<SemanticTokensParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL_DELTA => {
            let v: Box<SemanticTokensDeltaParams> =
                unmarshal_ptr_to::<SemanticTokensDeltaParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_SEMANTIC_TOKENS_RANGE => {
            let v: Box<SemanticTokensRangeParams> =
                unmarshal_ptr_to::<SemanticTokensRangeParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_SEMANTIC_TOKENS_REFRESH => unmarshal_empty(data),
        m if *m == Method::WINDOW_SHOW_DOCUMENT => {
            let v: Box<ShowDocumentParams> = unmarshal_ptr_to::<ShowDocumentParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_LINKED_EDITING_RANGE => {
            let v: Box<LinkedEditingRangeParams> =
                unmarshal_ptr_to::<LinkedEditingRangeParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_WILL_CREATE_FILES => {
            let v: Box<CreateFilesParams> = unmarshal_ptr_to::<CreateFilesParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_WILL_RENAME_FILES => {
            let v: Box<RenameFilesParams> = unmarshal_ptr_to::<RenameFilesParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_WILL_DELETE_FILES => {
            let v: Box<DeleteFilesParams> = unmarshal_ptr_to::<DeleteFilesParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_MONIKER => {
            let v: Box<MonikerParams> = unmarshal_ptr_to::<MonikerParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_PREPARE_TYPE_HIERARCHY => {
            let v: Box<TypeHierarchyPrepareParams> =
                unmarshal_ptr_to::<TypeHierarchyPrepareParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TYPE_HIERARCHY_SUPERTYPES => {
            let v: Box<TypeHierarchySupertypesParams> =
                unmarshal_ptr_to::<TypeHierarchySupertypesParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TYPE_HIERARCHY_SUBTYPES => {
            let v: Box<TypeHierarchySubtypesParams> =
                unmarshal_ptr_to::<TypeHierarchySubtypesParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_INLINE_VALUE => {
            let v: Box<InlineValueParams> = unmarshal_ptr_to::<InlineValueParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_INLINE_VALUE_REFRESH => unmarshal_empty(data),
        m if *m == Method::TEXT_DOCUMENT_INLAY_HINT => {
            let v: Box<InlayHintParams> = unmarshal_ptr_to::<InlayHintParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::INLAY_HINT_RESOLVE => {
            let v: Box<InlayHint> = unmarshal_ptr_to::<InlayHint>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_INLAY_HINT_REFRESH => unmarshal_empty(data),
        m if *m == Method::TEXT_DOCUMENT_DIAGNOSTIC => {
            let v: Box<DocumentDiagnosticParams> =
                unmarshal_ptr_to::<DocumentDiagnosticParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_DIAGNOSTIC => {
            let v: Box<WorkspaceDiagnosticParams> =
                unmarshal_ptr_to::<WorkspaceDiagnosticParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_DIAGNOSTIC_REFRESH => unmarshal_empty(data),
        m if *m == Method::TEXT_DOCUMENT_INLINE_COMPLETION => {
            let v: Box<InlineCompletionParams> =
                unmarshal_ptr_to::<InlineCompletionParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_TEXT_DOCUMENT_CONTENT => {
            let v: Box<TextDocumentContentParams> =
                unmarshal_ptr_to::<TextDocumentContentParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_TEXT_DOCUMENT_CONTENT_REFRESH => {
            let v: Box<TextDocumentContentRefreshParams> =
                unmarshal_ptr_to::<TextDocumentContentRefreshParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CLIENT_REGISTER_CAPABILITY => {
            let v: Box<RegistrationParams> = unmarshal_ptr_to::<RegistrationParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CLIENT_UNREGISTER_CAPABILITY => {
            let v: Box<UnregistrationParams> =
                unmarshal_ptr_to::<UnregistrationParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::INITIALIZE => {
            let v: Box<InitializeParams> = unmarshal_ptr_to::<InitializeParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::SHUTDOWN => unmarshal_empty(data),
        m if *m == Method::WINDOW_SHOW_MESSAGE_REQUEST => {
            let v: Box<ShowMessageRequestParams> =
                unmarshal_ptr_to::<ShowMessageRequestParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_WILL_SAVE_WAIT_UNTIL => {
            let v: Box<WillSaveTextDocumentParams> =
                unmarshal_ptr_to::<WillSaveTextDocumentParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_COMPLETION => {
            let v: Box<CompletionParams> = unmarshal_ptr_to::<CompletionParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::COMPLETION_ITEM_RESOLVE => {
            let v: Box<CompletionItem> = unmarshal_ptr_to::<CompletionItem>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_HOVER => {
            let v: Box<HoverParams> = unmarshal_ptr_to::<HoverParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_SIGNATURE_HELP => {
            let v: Box<SignatureHelpParams> = unmarshal_ptr_to::<SignatureHelpParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_DEFINITION => {
            let v: Box<DefinitionParams> = unmarshal_ptr_to::<DefinitionParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_REFERENCES => {
            let v: Box<ReferenceParams> = unmarshal_ptr_to::<ReferenceParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_DOCUMENT_HIGHLIGHT => {
            let v: Box<DocumentHighlightParams> =
                unmarshal_ptr_to::<DocumentHighlightParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_DOCUMENT_SYMBOL => {
            let v: Box<DocumentSymbolParams> =
                unmarshal_ptr_to::<DocumentSymbolParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_CODE_ACTION => {
            let v: Box<CodeActionParams> = unmarshal_ptr_to::<CodeActionParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CODE_ACTION_RESOLVE => {
            let v: Box<CodeAction> = unmarshal_ptr_to::<CodeAction>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_SYMBOL => {
            let v: Box<WorkspaceSymbolParams> =
                unmarshal_ptr_to::<WorkspaceSymbolParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_SYMBOL_RESOLVE => {
            let v: Box<WorkspaceSymbol> = unmarshal_ptr_to::<WorkspaceSymbol>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_CODE_LENS => {
            let v: Box<CodeLensParams> = unmarshal_ptr_to::<CodeLensParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CODE_LENS_RESOLVE => {
            let v: Box<CodeLens> = unmarshal_ptr_to::<CodeLens>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_CODE_LENS_REFRESH => unmarshal_empty(data),
        m if *m == Method::TEXT_DOCUMENT_DOCUMENT_LINK => {
            let v: Box<DocumentLinkParams> = unmarshal_ptr_to::<DocumentLinkParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::DOCUMENT_LINK_RESOLVE => {
            let v: Box<DocumentLink> = unmarshal_ptr_to::<DocumentLink>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_FORMATTING => {
            let v: Box<DocumentFormattingParams> =
                unmarshal_ptr_to::<DocumentFormattingParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_RANGE_FORMATTING => {
            let v: Box<DocumentRangeFormattingParams> =
                unmarshal_ptr_to::<DocumentRangeFormattingParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_RANGES_FORMATTING => {
            let v: Box<DocumentRangesFormattingParams> =
                unmarshal_ptr_to::<DocumentRangesFormattingParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_ON_TYPE_FORMATTING => {
            let v: Box<DocumentOnTypeFormattingParams> =
                unmarshal_ptr_to::<DocumentOnTypeFormattingParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_RENAME => {
            let v: Box<RenameParams> = unmarshal_ptr_to::<RenameParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_PREPARE_RENAME => {
            let v: Box<PrepareRenameParams> = unmarshal_ptr_to::<PrepareRenameParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_EXECUTE_COMMAND => {
            let v: Box<ExecuteCommandParams> =
                unmarshal_ptr_to::<ExecuteCommandParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_APPLY_EDIT => {
            let v: Box<ApplyWorkspaceEditParams> =
                unmarshal_ptr_to::<ApplyWorkspaceEditParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_RUN_GC => unmarshal_empty(data),
        m if *m == Method::CUSTOM_SAVE_HEAP_PROFILE => {
            let v: Box<ProfileParams> = unmarshal_ptr_to::<ProfileParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_SAVE_ALLOC_PROFILE => {
            let v: Box<ProfileParams> = unmarshal_ptr_to::<ProfileParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_START_CPU_PROFILE => {
            let v: Box<ProfileParams> = unmarshal_ptr_to::<ProfileParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_STOP_CPU_PROFILE => unmarshal_empty(data),
        m if *m == Method::CUSTOM_INITIALIZE_API_SESSION => {
            let v: Box<InitializeAPISessionParams> =
                unmarshal_ptr_to::<InitializeAPISessionParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_PROJECT_INFO => {
            let v: Box<ProjectInfoParams> = unmarshal_ptr_to::<ProjectInfoParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_TEXT_DOCUMENT_SOURCE_DEFINITION => {
            let v: Box<TextDocumentPositionParams> =
                unmarshal_ptr_to::<TextDocumentPositionParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_TEXT_DOCUMENT_MULTI_DOCUMENT_HIGHLIGHT => {
            let v: Box<MultiDocumentHighlightParams> =
                unmarshal_ptr_to::<MultiDocumentHighlightParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_VS_ON_AUTO_INSERT => {
            let v: Box<VSOnAutoInsertParams> =
                unmarshal_ptr_to::<VSOnAutoInsertParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_VS_REFERENCES => {
            let v: Box<ReferenceParams> = unmarshal_ptr_to::<ReferenceParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_DID_CHANGE_WORKSPACE_FOLDERS => {
            let v: Box<DidChangeWorkspaceFoldersParams> =
                unmarshal_ptr_to::<DidChangeWorkspaceFoldersParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WINDOW_WORK_DONE_PROGRESS_CANCEL => {
            let v: Box<WorkDoneProgressCancelParams> =
                unmarshal_ptr_to::<WorkDoneProgressCancelParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_DID_CREATE_FILES => {
            let v: Box<CreateFilesParams> = unmarshal_ptr_to::<CreateFilesParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_DID_RENAME_FILES => {
            let v: Box<RenameFilesParams> = unmarshal_ptr_to::<RenameFilesParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_DID_DELETE_FILES => {
            let v: Box<DeleteFilesParams> = unmarshal_ptr_to::<DeleteFilesParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::INITIALIZED => {
            let v: Box<InitializedParams> = unmarshal_ptr_to::<InitializedParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::EXIT => unmarshal_empty(data),
        m if *m == Method::WORKSPACE_DID_CHANGE_CONFIGURATION => {
            let v: Box<DidChangeConfigurationParams> =
                unmarshal_ptr_to::<DidChangeConfigurationParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WINDOW_SHOW_MESSAGE => {
            let v: Box<ShowMessageParams> = unmarshal_ptr_to::<ShowMessageParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WINDOW_LOG_MESSAGE => {
            let v: Box<LogMessageParams> = unmarshal_ptr_to::<LogMessageParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TELEMETRY_EVENT => {
            let v: Box<TelemetryEvent> = unmarshal_ptr_to::<TelemetryEvent>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_DID_OPEN => {
            let v: Box<DidOpenTextDocumentParams> =
                unmarshal_ptr_to::<DidOpenTextDocumentParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_DID_CHANGE => {
            let v: Box<DidChangeTextDocumentParams> =
                unmarshal_ptr_to::<DidChangeTextDocumentParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_DID_CLOSE => {
            let v: Box<DidCloseTextDocumentParams> =
                unmarshal_ptr_to::<DidCloseTextDocumentParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_DID_SAVE => {
            let v: Box<DidSaveTextDocumentParams> =
                unmarshal_ptr_to::<DidSaveTextDocumentParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_WILL_SAVE => {
            let v: Box<WillSaveTextDocumentParams> =
                unmarshal_ptr_to::<WillSaveTextDocumentParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_DID_CHANGE_WATCHED_FILES => {
            let v: Box<DidChangeWatchedFilesParams> =
                unmarshal_ptr_to::<DidChangeWatchedFilesParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_PUBLISH_DIAGNOSTICS => {
            let v: Box<PublishDiagnosticsParams> =
                unmarshal_ptr_to::<PublishDiagnosticsParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::SET_TRACE => {
            let v: Box<SetTraceParams> = unmarshal_ptr_to::<SetTraceParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::LOG_TRACE => {
            let v: Box<LogTraceParams> = unmarshal_ptr_to::<LogTraceParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CANCEL_REQUEST => {
            let v: Box<CancelParams> = unmarshal_ptr_to::<CancelParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::PROGRESS => {
            let v: Box<ProgressParams> = unmarshal_ptr_to::<ProgressParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_SET_LOG_VERBOSITY => {
            let v: Box<SetLogVerbosityParams> =
                unmarshal_ptr_to::<SetLogVerbosityParams>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        _ => unmarshal_any(data),
    }
}

// Go: unmarshalResult
pub fn unmarshal_result(
    method: &Method,
    data: &[u8],
) -> Result<Option<Box<dyn AnyValue>>, GoError> {
    match method {
        m if *m == Method::TEXT_DOCUMENT_IMPLEMENTATION => {
            let v: Box<ImplementationResponse> =
                unmarshal_value::<ImplementationResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_TYPE_DEFINITION => {
            let v: Box<TypeDefinitionResponse> =
                unmarshal_value::<TypeDefinitionResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_WORKSPACE_FOLDERS => {
            let v: Box<WorkspaceFoldersResponse> =
                unmarshal_value::<WorkspaceFoldersResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_CONFIGURATION => {
            let v: Box<ConfigurationResponse> =
                unmarshal_value::<ConfigurationResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_DOCUMENT_COLOR => {
            let v: Box<DocumentColorResponse> =
                unmarshal_value::<DocumentColorResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_COLOR_PRESENTATION => {
            let v: Box<ColorPresentationResponse> =
                unmarshal_value::<ColorPresentationResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_FOLDING_RANGE => {
            let v: Box<FoldingRangeResponse> =
                unmarshal_value::<FoldingRangeResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_FOLDING_RANGE_REFRESH => {
            let v: Box<FoldingRangeRefreshResponse> =
                unmarshal_value::<FoldingRangeRefreshResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_DECLARATION => {
            let v: Box<DeclarationResponse> = unmarshal_value::<DeclarationResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_SELECTION_RANGE => {
            let v: Box<SelectionRangeResponse> =
                unmarshal_value::<SelectionRangeResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WINDOW_WORK_DONE_PROGRESS_CREATE => {
            let v: Box<WorkDoneProgressCreateResponse> =
                unmarshal_value::<WorkDoneProgressCreateResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_PREPARE_CALL_HIERARCHY => {
            let v: Box<CallHierarchyPrepareResponse> =
                unmarshal_value::<CallHierarchyPrepareResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CALL_HIERARCHY_INCOMING_CALLS => {
            let v: Box<CallHierarchyIncomingCallsResponse> =
                unmarshal_value::<CallHierarchyIncomingCallsResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CALL_HIERARCHY_OUTGOING_CALLS => {
            let v: Box<CallHierarchyOutgoingCallsResponse> =
                unmarshal_value::<CallHierarchyOutgoingCallsResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL => {
            let v: Box<SemanticTokensResponse> =
                unmarshal_value::<SemanticTokensResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL_DELTA => {
            let v: Box<SemanticTokensDeltaResponse> =
                unmarshal_value::<SemanticTokensDeltaResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_SEMANTIC_TOKENS_RANGE => {
            let v: Box<SemanticTokensRangeResponse> =
                unmarshal_value::<SemanticTokensRangeResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_SEMANTIC_TOKENS_REFRESH => {
            let v: Box<SemanticTokensRefreshResponse> =
                unmarshal_value::<SemanticTokensRefreshResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WINDOW_SHOW_DOCUMENT => {
            let v: Box<ShowDocumentResponse> =
                unmarshal_value::<ShowDocumentResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_LINKED_EDITING_RANGE => {
            let v: Box<LinkedEditingRangeResponse> =
                unmarshal_value::<LinkedEditingRangeResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_WILL_CREATE_FILES => {
            let v: Box<WillCreateFilesResponse> =
                unmarshal_value::<WillCreateFilesResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_WILL_RENAME_FILES => {
            let v: Box<WillRenameFilesResponse> =
                unmarshal_value::<WillRenameFilesResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_WILL_DELETE_FILES => {
            let v: Box<WillDeleteFilesResponse> =
                unmarshal_value::<WillDeleteFilesResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_MONIKER => {
            let v: Box<MonikerResponse> = unmarshal_value::<MonikerResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_PREPARE_TYPE_HIERARCHY => {
            let v: Box<TypeHierarchyPrepareResponse> =
                unmarshal_value::<TypeHierarchyPrepareResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TYPE_HIERARCHY_SUPERTYPES => {
            let v: Box<TypeHierarchySupertypesResponse> =
                unmarshal_value::<TypeHierarchySupertypesResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TYPE_HIERARCHY_SUBTYPES => {
            let v: Box<TypeHierarchySubtypesResponse> =
                unmarshal_value::<TypeHierarchySubtypesResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_INLINE_VALUE => {
            let v: Box<InlineValueResponse> = unmarshal_value::<InlineValueResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_INLINE_VALUE_REFRESH => {
            let v: Box<InlineValueRefreshResponse> =
                unmarshal_value::<InlineValueRefreshResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_INLAY_HINT => {
            let v: Box<InlayHintResponse> = unmarshal_value::<InlayHintResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::INLAY_HINT_RESOLVE => {
            let v: Box<InlayHintResolveResponse> =
                unmarshal_value::<InlayHintResolveResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_INLAY_HINT_REFRESH => {
            let v: Box<InlayHintRefreshResponse> =
                unmarshal_value::<InlayHintRefreshResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_DIAGNOSTIC => {
            let v: Box<DocumentDiagnosticResponse> =
                unmarshal_value::<DocumentDiagnosticResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_DIAGNOSTIC => {
            let v: Box<WorkspaceDiagnosticResponse> =
                unmarshal_value::<WorkspaceDiagnosticResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_DIAGNOSTIC_REFRESH => {
            let v: Box<DiagnosticRefreshResponse> =
                unmarshal_value::<DiagnosticRefreshResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_INLINE_COMPLETION => {
            let v: Box<InlineCompletionResponse> =
                unmarshal_value::<InlineCompletionResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_TEXT_DOCUMENT_CONTENT => {
            let v: Box<TextDocumentContentResponse> =
                unmarshal_value::<TextDocumentContentResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_TEXT_DOCUMENT_CONTENT_REFRESH => {
            let v: Box<TextDocumentContentRefreshResponse> =
                unmarshal_value::<TextDocumentContentRefreshResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CLIENT_REGISTER_CAPABILITY => {
            let v: Box<RegistrationResponse> =
                unmarshal_value::<RegistrationResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CLIENT_UNREGISTER_CAPABILITY => {
            let v: Box<UnregistrationResponse> =
                unmarshal_value::<UnregistrationResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::INITIALIZE => {
            let v: Box<InitializeResponse> = unmarshal_value::<InitializeResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::SHUTDOWN => {
            let v: Box<ShutdownResponse> = unmarshal_value::<ShutdownResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WINDOW_SHOW_MESSAGE_REQUEST => {
            let v: Box<ShowMessageResponse> = unmarshal_value::<ShowMessageResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_WILL_SAVE_WAIT_UNTIL => {
            let v: Box<WillSaveTextDocumentWaitUntilResponse> =
                unmarshal_value::<WillSaveTextDocumentWaitUntilResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_COMPLETION => {
            let v: Box<CompletionResponse> = unmarshal_value::<CompletionResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::COMPLETION_ITEM_RESOLVE => {
            let v: Box<CompletionResolveResponse> =
                unmarshal_value::<CompletionResolveResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_HOVER => {
            let v: Box<HoverResponse> = unmarshal_value::<HoverResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_SIGNATURE_HELP => {
            let v: Box<SignatureHelpResponse> =
                unmarshal_value::<SignatureHelpResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_DEFINITION => {
            let v: Box<DefinitionResponse> = unmarshal_value::<DefinitionResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_REFERENCES => {
            let v: Box<ReferencesResponse> = unmarshal_value::<ReferencesResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_DOCUMENT_HIGHLIGHT => {
            let v: Box<DocumentHighlightResponse> =
                unmarshal_value::<DocumentHighlightResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_DOCUMENT_SYMBOL => {
            let v: Box<DocumentSymbolResponse> =
                unmarshal_value::<DocumentSymbolResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_CODE_ACTION => {
            let v: Box<CodeActionResponse> = unmarshal_value::<CodeActionResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CODE_ACTION_RESOLVE => {
            let v: Box<CodeActionResolveResponse> =
                unmarshal_value::<CodeActionResolveResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_SYMBOL => {
            let v: Box<WorkspaceSymbolResponse> =
                unmarshal_value::<WorkspaceSymbolResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_SYMBOL_RESOLVE => {
            let v: Box<WorkspaceSymbolResolveResponse> =
                unmarshal_value::<WorkspaceSymbolResolveResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_CODE_LENS => {
            let v: Box<CodeLensResponse> = unmarshal_value::<CodeLensResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CODE_LENS_RESOLVE => {
            let v: Box<CodeLensResolveResponse> =
                unmarshal_value::<CodeLensResolveResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_CODE_LENS_REFRESH => {
            let v: Box<CodeLensRefreshResponse> =
                unmarshal_value::<CodeLensRefreshResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_DOCUMENT_LINK => {
            let v: Box<DocumentLinkResponse> =
                unmarshal_value::<DocumentLinkResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::DOCUMENT_LINK_RESOLVE => {
            let v: Box<DocumentLinkResolveResponse> =
                unmarshal_value::<DocumentLinkResolveResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_FORMATTING => {
            let v: Box<DocumentFormattingResponse> =
                unmarshal_value::<DocumentFormattingResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_RANGE_FORMATTING => {
            let v: Box<DocumentRangeFormattingResponse> =
                unmarshal_value::<DocumentRangeFormattingResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_RANGES_FORMATTING => {
            let v: Box<DocumentRangesFormattingResponse> =
                unmarshal_value::<DocumentRangesFormattingResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_ON_TYPE_FORMATTING => {
            let v: Box<DocumentOnTypeFormattingResponse> =
                unmarshal_value::<DocumentOnTypeFormattingResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_RENAME => {
            let v: Box<RenameResponse> = unmarshal_value::<RenameResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_PREPARE_RENAME => {
            let v: Box<PrepareRenameResponse> =
                unmarshal_value::<PrepareRenameResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_EXECUTE_COMMAND => {
            let v: Box<ExecuteCommandResponse> =
                unmarshal_value::<ExecuteCommandResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::WORKSPACE_APPLY_EDIT => {
            let v: Box<ApplyWorkspaceEditResponse> =
                unmarshal_value::<ApplyWorkspaceEditResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_RUN_GC => {
            let v: Box<RunGCResponse> = unmarshal_value::<RunGCResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_SAVE_HEAP_PROFILE => {
            let v: Box<SaveHeapProfileResponse> =
                unmarshal_value::<SaveHeapProfileResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_SAVE_ALLOC_PROFILE => {
            let v: Box<SaveAllocProfileResponse> =
                unmarshal_value::<SaveAllocProfileResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_START_CPU_PROFILE => {
            let v: Box<StartCPUProfileResponse> =
                unmarshal_value::<StartCPUProfileResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_STOP_CPU_PROFILE => {
            let v: Box<StopCPUProfileResponse> =
                unmarshal_value::<StopCPUProfileResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_INITIALIZE_API_SESSION => {
            let v: Box<CustomInitializeAPISessionResponse> =
                unmarshal_value::<CustomInitializeAPISessionResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_PROJECT_INFO => {
            let v: Box<CustomProjectInfoResponse> =
                unmarshal_value::<CustomProjectInfoResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_TEXT_DOCUMENT_SOURCE_DEFINITION => {
            let v: Box<CustomTextDocumentSourceDefinitionResponse> =
                unmarshal_value::<CustomTextDocumentSourceDefinitionResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::CUSTOM_TEXT_DOCUMENT_MULTI_DOCUMENT_HIGHLIGHT => {
            let v: Box<CustomMultiDocumentHighlightResponse> =
                unmarshal_value::<CustomMultiDocumentHighlightResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_VS_ON_AUTO_INSERT => {
            let v: Box<VSOnAutoInsertResponse> =
                unmarshal_value::<VSOnAutoInsertResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        m if *m == Method::TEXT_DOCUMENT_VS_REFERENCES => {
            let v: Box<VSReferencesResponse> =
                unmarshal_value::<VSReferencesResponse>(data)?.into();
            Ok(Some(v as Box<dyn AnyValue>))
        }
        _ => unmarshal_any(data),
    }
}
