// Code generated by generate.mts; DO NOT EDIT.
//
// Rust port of microsoft/TypeScript tsc/internal/lsp/lsproto/lsp_generated.go
// (pinned 673a5f17d713), generated from the same meta model by the ported generator.
// Meta model version 3.18.0

use crate::lsp::lsproto::prelude::*;

// Enumerations

// A set of predefined token types. This set is not fixed
// an clients can specify additional token types via the
// corresponding client capabilities.
//
// Since: 3.16.0
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct SemanticTokenType(pub Cow<'static, str>);

impl SemanticTokenType {
    pub const NAMESPACE: SemanticTokenType = SemanticTokenType(Cow::Borrowed("namespace"));
    // Represents a generic type. Acts as a fallback for types which can't be mapped to
    // a specific type like class or enum.
    pub const TYPE: SemanticTokenType = SemanticTokenType(Cow::Borrowed("type"));
    pub const CLASS: SemanticTokenType = SemanticTokenType(Cow::Borrowed("class"));
    pub const ENUM: SemanticTokenType = SemanticTokenType(Cow::Borrowed("enum"));
    pub const INTERFACE: SemanticTokenType = SemanticTokenType(Cow::Borrowed("interface"));
    pub const STRUCT: SemanticTokenType = SemanticTokenType(Cow::Borrowed("struct"));
    pub const TYPE_PARAMETER: SemanticTokenType = SemanticTokenType(Cow::Borrowed("typeParameter"));
    pub const PARAMETER: SemanticTokenType = SemanticTokenType(Cow::Borrowed("parameter"));
    pub const VARIABLE: SemanticTokenType = SemanticTokenType(Cow::Borrowed("variable"));
    pub const PROPERTY: SemanticTokenType = SemanticTokenType(Cow::Borrowed("property"));
    pub const ENUM_MEMBER: SemanticTokenType = SemanticTokenType(Cow::Borrowed("enumMember"));
    pub const EVENT: SemanticTokenType = SemanticTokenType(Cow::Borrowed("event"));
    pub const FUNCTION: SemanticTokenType = SemanticTokenType(Cow::Borrowed("function"));
    pub const METHOD: SemanticTokenType = SemanticTokenType(Cow::Borrowed("method"));
    pub const MACRO: SemanticTokenType = SemanticTokenType(Cow::Borrowed("macro"));
    pub const KEYWORD: SemanticTokenType = SemanticTokenType(Cow::Borrowed("keyword"));
    pub const MODIFIER: SemanticTokenType = SemanticTokenType(Cow::Borrowed("modifier"));
    pub const COMMENT: SemanticTokenType = SemanticTokenType(Cow::Borrowed("comment"));
    pub const STRING: SemanticTokenType = SemanticTokenType(Cow::Borrowed("string"));
    pub const NUMBER: SemanticTokenType = SemanticTokenType(Cow::Borrowed("number"));
    pub const REGEXP: SemanticTokenType = SemanticTokenType(Cow::Borrowed("regexp"));
    pub const OPERATOR: SemanticTokenType = SemanticTokenType(Cow::Borrowed("operator"));
    // Since: 3.17.0
    pub const DECORATOR: SemanticTokenType = SemanticTokenType(Cow::Borrowed("decorator"));
    // Since: 3.18.0
    pub const LABEL: SemanticTokenType = SemanticTokenType(Cow::Borrowed("label"));
}

impl IsZero for SemanticTokenType {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for SemanticTokenType {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for SemanticTokenType {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

// A set of predefined token modifiers. This set is not fixed
// an clients can specify additional token types via the
// corresponding client capabilities.
//
// Since: 3.16.0
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct SemanticTokenModifier(pub Cow<'static, str>);

impl SemanticTokenModifier {
    pub const DECLARATION: SemanticTokenModifier =
        SemanticTokenModifier(Cow::Borrowed("declaration"));
    pub const DEFINITION: SemanticTokenModifier =
        SemanticTokenModifier(Cow::Borrowed("definition"));
    pub const READONLY: SemanticTokenModifier = SemanticTokenModifier(Cow::Borrowed("readonly"));
    pub const STATIC: SemanticTokenModifier = SemanticTokenModifier(Cow::Borrowed("static"));
    pub const DEPRECATED: SemanticTokenModifier =
        SemanticTokenModifier(Cow::Borrowed("deprecated"));
    pub const ABSTRACT: SemanticTokenModifier = SemanticTokenModifier(Cow::Borrowed("abstract"));
    pub const ASYNC: SemanticTokenModifier = SemanticTokenModifier(Cow::Borrowed("async"));
    pub const MODIFICATION: SemanticTokenModifier =
        SemanticTokenModifier(Cow::Borrowed("modification"));
    pub const DOCUMENTATION: SemanticTokenModifier =
        SemanticTokenModifier(Cow::Borrowed("documentation"));
    pub const DEFAULT_LIBRARY: SemanticTokenModifier =
        SemanticTokenModifier(Cow::Borrowed("defaultLibrary"));
}

impl IsZero for SemanticTokenModifier {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for SemanticTokenModifier {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for SemanticTokenModifier {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

// The document diagnostic report kinds.
//
// Since: 3.17.0
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct DocumentDiagnosticReportKind(pub Cow<'static, str>);

impl DocumentDiagnosticReportKind {
    // A diagnostic report with a full
    // set of problems.
    pub const FULL: DocumentDiagnosticReportKind =
        DocumentDiagnosticReportKind(Cow::Borrowed("full"));
    // A report indicating that the last
    // returned report is still accurate.
    pub const UNCHANGED: DocumentDiagnosticReportKind =
        DocumentDiagnosticReportKind(Cow::Borrowed("unchanged"));
}

impl IsZero for DocumentDiagnosticReportKind {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for DocumentDiagnosticReportKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for DocumentDiagnosticReportKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

// Predefined error codes.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ErrorCode(pub i32);

impl ErrorCode {
    pub const PARSE_ERROR: ErrorCode = ErrorCode(-32700);
    pub const INVALID_REQUEST: ErrorCode = ErrorCode(-32600);
    pub const METHOD_NOT_FOUND: ErrorCode = ErrorCode(-32601);
    pub const INVALID_PARAMS: ErrorCode = ErrorCode(-32602);
    pub const INTERNAL_ERROR: ErrorCode = ErrorCode(-32603);
    // Error code indicating that a server received a notification or
    // request before the server has received the `initialize` request.
    pub const SERVER_NOT_INITIALIZED: ErrorCode = ErrorCode(-32002);
    pub const UNKNOWN_ERROR_CODE: ErrorCode = ErrorCode(-32001);
    // A request failed but it was syntactically correct, e.g the
    // method name was known and the parameters were valid. The error
    // message should contain human readable information about why
    // the request failed.
    //
    // Since: 3.17.0
    pub const REQUEST_FAILED: ErrorCode = ErrorCode(-32803);
    // The server cancelled the request. This error code should
    // only be used for requests that explicitly support being
    // server cancellable.
    //
    // Since: 3.17.0
    pub const SERVER_CANCELLED: ErrorCode = ErrorCode(-32802);
    // The server detected that the content of a document got
    // modified outside normal conditions. A server should
    // NOT send this error code if it detects a content change
    // in it unprocessed messages. The result even computed
    // on an older state might still be useful for the client.
    //
    // If a client decides that a result is not of any use anymore
    // the client should cancel the request.
    pub const CONTENT_MODIFIED: ErrorCode = ErrorCode(-32801);
    // The client has canceled a request and a server has detected
    // the cancel.
    pub const REQUEST_CANCELLED: ErrorCode = ErrorCode(-32800);
}

impl IsZero for ErrorCode {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for ErrorCode {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for ErrorCode {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _ERROR_CODE_NAME: &str = "RequestFailedServerCancelledContentModifiedRequestCancelledParseErrorInternalErrorInvalidParamsMethodNotFoundInvalidRequestServerNotInitializedUnknownErrorCode";

const _ERROR_CODE_INDEX_0: [u16; 5] = [0, 13, 28, 43, 59];
const _ERROR_CODE_INDEX_2: [u16; 5] = [0, 13, 26, 40, 54];
const _ERROR_CODE_INDEX_3: [u16; 3] = [0, 20, 36];

impl ErrorCode {
    // Go: (e ErrorCode) String
    pub fn string(&self) -> String {
        let e = self.0;
        if -32803 <= e && e <= -32800 {
            let i = (e as i64 - (-32803)) as usize;
            _ERROR_CODE_NAME
                [0 + _ERROR_CODE_INDEX_0[i] as usize..0 + _ERROR_CODE_INDEX_0[i + 1] as usize]
                .to_string()
        } else if e == -32700 {
            _ERROR_CODE_NAME[59..69].to_string()
        } else if -32603 <= e && e <= -32600 {
            let i = (e as i64 - (-32603)) as usize;
            _ERROR_CODE_NAME
                [69 + _ERROR_CODE_INDEX_2[i] as usize..69 + _ERROR_CODE_INDEX_2[i + 1] as usize]
                .to_string()
        } else if -32002 <= e && e <= -32001 {
            let i = (e as i64 - (-32002)) as usize;
            _ERROR_CODE_NAME
                [123 + _ERROR_CODE_INDEX_3[i] as usize..123 + _ERROR_CODE_INDEX_3[i + 1] as usize]
                .to_string()
        } else {
            format!("ErrorCode({})", self.0)
        }
    }
}

impl std::fmt::Display for ErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

impl ErrorCode {
    // Go: (e ErrorCode) Error
    pub fn error(&self) -> String {
        self.string()
    }
}

impl std::error::Error for ErrorCode {}

// A set of predefined range kinds.
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct FoldingRangeKind(pub Cow<'static, str>);

impl FoldingRangeKind {
    // Folding range for a comment
    pub const COMMENT: FoldingRangeKind = FoldingRangeKind(Cow::Borrowed("comment"));
    // Folding range for an import or include
    pub const IMPORTS: FoldingRangeKind = FoldingRangeKind(Cow::Borrowed("imports"));
    // Folding range for a region (e.g. `#region`)
    pub const REGION: FoldingRangeKind = FoldingRangeKind(Cow::Borrowed("region"));
}

impl IsZero for FoldingRangeKind {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for FoldingRangeKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for FoldingRangeKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

// A symbol kind.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct SymbolKind(pub u32);

impl SymbolKind {
    pub const FILE: SymbolKind = SymbolKind(1);
    pub const MODULE: SymbolKind = SymbolKind(2);
    pub const NAMESPACE: SymbolKind = SymbolKind(3);
    pub const PACKAGE: SymbolKind = SymbolKind(4);
    pub const CLASS: SymbolKind = SymbolKind(5);
    pub const METHOD: SymbolKind = SymbolKind(6);
    pub const PROPERTY: SymbolKind = SymbolKind(7);
    pub const FIELD: SymbolKind = SymbolKind(8);
    pub const CONSTRUCTOR: SymbolKind = SymbolKind(9);
    pub const ENUM: SymbolKind = SymbolKind(10);
    pub const INTERFACE: SymbolKind = SymbolKind(11);
    pub const FUNCTION: SymbolKind = SymbolKind(12);
    pub const VARIABLE: SymbolKind = SymbolKind(13);
    pub const CONSTANT: SymbolKind = SymbolKind(14);
    pub const STRING: SymbolKind = SymbolKind(15);
    pub const NUMBER: SymbolKind = SymbolKind(16);
    pub const BOOLEAN: SymbolKind = SymbolKind(17);
    pub const ARRAY: SymbolKind = SymbolKind(18);
    pub const OBJECT: SymbolKind = SymbolKind(19);
    pub const KEY: SymbolKind = SymbolKind(20);
    pub const NULL: SymbolKind = SymbolKind(21);
    pub const ENUM_MEMBER: SymbolKind = SymbolKind(22);
    pub const STRUCT: SymbolKind = SymbolKind(23);
    pub const EVENT: SymbolKind = SymbolKind(24);
    pub const OPERATOR: SymbolKind = SymbolKind(25);
    pub const TYPE_PARAMETER: SymbolKind = SymbolKind(26);
}

impl IsZero for SymbolKind {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for SymbolKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for SymbolKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _SYMBOL_KIND_NAME: &str = "FileModuleNamespacePackageClassMethodPropertyFieldConstructorEnumInterfaceFunctionVariableConstantStringNumberBooleanArrayObjectKeyNullEnumMemberStructEventOperatorTypeParameter";
const _SYMBOL_KIND_INDEX: [u16; 27] = [
    0, 4, 10, 19, 26, 31, 37, 45, 50, 61, 65, 74, 82, 90, 98, 104, 110, 117, 122, 128, 131, 135,
    145, 151, 156, 164, 177,
];

impl SymbolKind {
    // Go: (e SymbolKind) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _SYMBOL_KIND_INDEX.len() as i64 - 1 {
            return format!("SymbolKind({})", self.0);
        }
        let i = i as usize;
        _SYMBOL_KIND_NAME[_SYMBOL_KIND_INDEX[i] as usize.._SYMBOL_KIND_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for SymbolKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// Symbol tags are extra annotations that tweak the rendering of a symbol.
//
// Since: 3.16
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct SymbolTag(pub u32);

impl SymbolTag {
    // Render a symbol as obsolete, usually using a strike-out.
    pub const DEPRECATED: SymbolTag = SymbolTag(1);
}

impl IsZero for SymbolTag {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for SymbolTag {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for SymbolTag {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _SYMBOL_TAG_NAME: &str = "Deprecated";
const _SYMBOL_TAG_INDEX: [u16; 2] = [0, 10];

impl SymbolTag {
    // Go: (e SymbolTag) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _SYMBOL_TAG_INDEX.len() as i64 - 1 {
            return format!("SymbolTag({})", self.0);
        }
        let i = i as usize;
        _SYMBOL_TAG_NAME[_SYMBOL_TAG_INDEX[i] as usize.._SYMBOL_TAG_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for SymbolTag {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// Moniker uniqueness level to define scope of the moniker.
//
// Since: 3.16.0
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct UniquenessLevel(pub Cow<'static, str>);

impl UniquenessLevel {
    // The moniker is only unique inside a document
    pub const DOCUMENT: UniquenessLevel = UniquenessLevel(Cow::Borrowed("document"));
    // The moniker is unique inside a project for which a dump got created
    pub const PROJECT: UniquenessLevel = UniquenessLevel(Cow::Borrowed("project"));
    // The moniker is unique inside the group to which a project belongs
    pub const GROUP: UniquenessLevel = UniquenessLevel(Cow::Borrowed("group"));
    // The moniker is unique inside the moniker scheme.
    pub const SCHEME: UniquenessLevel = UniquenessLevel(Cow::Borrowed("scheme"));
    // The moniker is globally unique
    pub const GLOBAL: UniquenessLevel = UniquenessLevel(Cow::Borrowed("global"));
}

impl IsZero for UniquenessLevel {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for UniquenessLevel {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for UniquenessLevel {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

// The moniker kind.
//
// Since: 3.16.0
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct MonikerKind(pub Cow<'static, str>);

impl MonikerKind {
    // The moniker represent a symbol that is imported into a project
    pub const IMPORT: MonikerKind = MonikerKind(Cow::Borrowed("import"));
    // The moniker represents a symbol that is exported from a project
    pub const EXPORT: MonikerKind = MonikerKind(Cow::Borrowed("export"));
    // The moniker represents a symbol that is local to a project (e.g. a local
    // variable of a function, a class not visible outside the project, ...)
    pub const LOCAL: MonikerKind = MonikerKind(Cow::Borrowed("local"));
}

impl IsZero for MonikerKind {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for MonikerKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for MonikerKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

// Inlay hint kinds.
//
// Since: 3.17.0
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct InlayHintKind(pub u32);

impl InlayHintKind {
    // An inlay hint that for a type annotation.
    pub const TYPE: InlayHintKind = InlayHintKind(1);
    // An inlay hint that is for a parameter.
    pub const PARAMETER: InlayHintKind = InlayHintKind(2);
}

impl IsZero for InlayHintKind {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for InlayHintKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for InlayHintKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _INLAY_HINT_KIND_NAME: &str = "TypeParameter";
const _INLAY_HINT_KIND_INDEX: [u16; 3] = [0, 4, 13];

impl InlayHintKind {
    // Go: (e InlayHintKind) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _INLAY_HINT_KIND_INDEX.len() as i64 - 1 {
            return format!("InlayHintKind({})", self.0);
        }
        let i = i as usize;
        _INLAY_HINT_KIND_NAME
            [_INLAY_HINT_KIND_INDEX[i] as usize.._INLAY_HINT_KIND_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for InlayHintKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// The message type
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct MessageType(pub u32);

impl MessageType {
    // An error message.
    pub const ERROR: MessageType = MessageType(1);
    // A warning message.
    pub const WARNING: MessageType = MessageType(2);
    // An information message.
    pub const INFO: MessageType = MessageType(3);
    // A log message.
    pub const LOG: MessageType = MessageType(4);
    // A debug message.
    //
    // Since: 3.18.0
    pub const DEBUG: MessageType = MessageType(5);
}

impl IsZero for MessageType {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for MessageType {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for MessageType {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _MESSAGE_TYPE_NAME: &str = "ErrorWarningInfoLogDebug";
const _MESSAGE_TYPE_INDEX: [u16; 6] = [0, 5, 12, 16, 19, 24];

impl MessageType {
    // Go: (e MessageType) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _MESSAGE_TYPE_INDEX.len() as i64 - 1 {
            return format!("MessageType({})", self.0);
        }
        let i = i as usize;
        _MESSAGE_TYPE_NAME[_MESSAGE_TYPE_INDEX[i] as usize.._MESSAGE_TYPE_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for MessageType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// Defines how the host (editor) should sync
// document changes to the language server.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct TextDocumentSyncKind(pub u32);

impl TextDocumentSyncKind {
    // Documents should not be synced at all.
    pub const NONE: TextDocumentSyncKind = TextDocumentSyncKind(0);
    // Documents are synced by always sending the full content
    // of the document.
    pub const FULL: TextDocumentSyncKind = TextDocumentSyncKind(1);
    // Documents are synced by sending the full content on open.
    // After that only incremental updates to the document are
    // send.
    pub const INCREMENTAL: TextDocumentSyncKind = TextDocumentSyncKind(2);
}

impl IsZero for TextDocumentSyncKind {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for TextDocumentSyncKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for TextDocumentSyncKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _TEXT_DOCUMENT_SYNC_KIND_NAME: &str = "NoneFullIncremental";
const _TEXT_DOCUMENT_SYNC_KIND_INDEX: [u16; 4] = [0, 4, 8, 19];

impl TextDocumentSyncKind {
    // Go: (e TextDocumentSyncKind) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (0);
        if i < 0 || i >= _TEXT_DOCUMENT_SYNC_KIND_INDEX.len() as i64 - 1 {
            return format!("TextDocumentSyncKind({})", self.0);
        }
        let i = i as usize;
        _TEXT_DOCUMENT_SYNC_KIND_NAME[_TEXT_DOCUMENT_SYNC_KIND_INDEX[i] as usize
            .._TEXT_DOCUMENT_SYNC_KIND_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for TextDocumentSyncKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// Represents reasons why a text document is saved.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct TextDocumentSaveReason(pub u32);

impl TextDocumentSaveReason {
    // Manually triggered, e.g. by the user pressing save, by starting debugging,
    // or by an API call.
    pub const MANUAL: TextDocumentSaveReason = TextDocumentSaveReason(1);
    // Automatic after a delay.
    pub const AFTER_DELAY: TextDocumentSaveReason = TextDocumentSaveReason(2);
    // When the editor lost focus.
    pub const FOCUS_OUT: TextDocumentSaveReason = TextDocumentSaveReason(3);
}

impl IsZero for TextDocumentSaveReason {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for TextDocumentSaveReason {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for TextDocumentSaveReason {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _TEXT_DOCUMENT_SAVE_REASON_NAME: &str = "ManualAfterDelayFocusOut";
const _TEXT_DOCUMENT_SAVE_REASON_INDEX: [u16; 4] = [0, 6, 16, 24];

impl TextDocumentSaveReason {
    // Go: (e TextDocumentSaveReason) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _TEXT_DOCUMENT_SAVE_REASON_INDEX.len() as i64 - 1 {
            return format!("TextDocumentSaveReason({})", self.0);
        }
        let i = i as usize;
        _TEXT_DOCUMENT_SAVE_REASON_NAME[_TEXT_DOCUMENT_SAVE_REASON_INDEX[i] as usize
            .._TEXT_DOCUMENT_SAVE_REASON_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for TextDocumentSaveReason {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// The kind of a completion entry.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CompletionItemKind(pub u32);

impl CompletionItemKind {
    pub const TEXT: CompletionItemKind = CompletionItemKind(1);
    pub const METHOD: CompletionItemKind = CompletionItemKind(2);
    pub const FUNCTION: CompletionItemKind = CompletionItemKind(3);
    pub const CONSTRUCTOR: CompletionItemKind = CompletionItemKind(4);
    pub const FIELD: CompletionItemKind = CompletionItemKind(5);
    pub const VARIABLE: CompletionItemKind = CompletionItemKind(6);
    pub const CLASS: CompletionItemKind = CompletionItemKind(7);
    pub const INTERFACE: CompletionItemKind = CompletionItemKind(8);
    pub const MODULE: CompletionItemKind = CompletionItemKind(9);
    pub const PROPERTY: CompletionItemKind = CompletionItemKind(10);
    pub const UNIT: CompletionItemKind = CompletionItemKind(11);
    pub const VALUE: CompletionItemKind = CompletionItemKind(12);
    pub const ENUM: CompletionItemKind = CompletionItemKind(13);
    pub const KEYWORD: CompletionItemKind = CompletionItemKind(14);
    pub const SNIPPET: CompletionItemKind = CompletionItemKind(15);
    pub const COLOR: CompletionItemKind = CompletionItemKind(16);
    pub const FILE: CompletionItemKind = CompletionItemKind(17);
    pub const REFERENCE: CompletionItemKind = CompletionItemKind(18);
    pub const FOLDER: CompletionItemKind = CompletionItemKind(19);
    pub const ENUM_MEMBER: CompletionItemKind = CompletionItemKind(20);
    pub const CONSTANT: CompletionItemKind = CompletionItemKind(21);
    pub const STRUCT: CompletionItemKind = CompletionItemKind(22);
    pub const EVENT: CompletionItemKind = CompletionItemKind(23);
    pub const OPERATOR: CompletionItemKind = CompletionItemKind(24);
    pub const TYPE_PARAMETER: CompletionItemKind = CompletionItemKind(25);
}

impl IsZero for CompletionItemKind {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for CompletionItemKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for CompletionItemKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _COMPLETION_ITEM_KIND_NAME: &str = "TextMethodFunctionConstructorFieldVariableClassInterfaceModulePropertyUnitValueEnumKeywordSnippetColorFileReferenceFolderEnumMemberConstantStructEventOperatorTypeParameter";
const _COMPLETION_ITEM_KIND_INDEX: [u16; 26] = [
    0, 4, 10, 18, 29, 34, 42, 47, 56, 62, 70, 74, 79, 83, 90, 97, 102, 106, 115, 121, 131, 139,
    145, 150, 158, 171,
];

impl CompletionItemKind {
    // Go: (e CompletionItemKind) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _COMPLETION_ITEM_KIND_INDEX.len() as i64 - 1 {
            return format!("CompletionItemKind({})", self.0);
        }
        let i = i as usize;
        _COMPLETION_ITEM_KIND_NAME
            [_COMPLETION_ITEM_KIND_INDEX[i] as usize.._COMPLETION_ITEM_KIND_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for CompletionItemKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// Completion item tags are extra annotations that tweak the rendering of a completion
// item.
//
// Since: 3.15.0
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CompletionItemTag(pub u32);

impl CompletionItemTag {
    // Render a completion as obsolete, usually using a strike-out.
    pub const DEPRECATED: CompletionItemTag = CompletionItemTag(1);
}

impl IsZero for CompletionItemTag {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for CompletionItemTag {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for CompletionItemTag {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _COMPLETION_ITEM_TAG_NAME: &str = "Deprecated";
const _COMPLETION_ITEM_TAG_INDEX: [u16; 2] = [0, 10];

impl CompletionItemTag {
    // Go: (e CompletionItemTag) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _COMPLETION_ITEM_TAG_INDEX.len() as i64 - 1 {
            return format!("CompletionItemTag({})", self.0);
        }
        let i = i as usize;
        _COMPLETION_ITEM_TAG_NAME
            [_COMPLETION_ITEM_TAG_INDEX[i] as usize.._COMPLETION_ITEM_TAG_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for CompletionItemTag {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// Defines whether the insert text in a completion item should be interpreted as
// plain text or a snippet.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct InsertTextFormat(pub u32);

impl InsertTextFormat {
    // The primary text to be inserted is treated as a plain string.
    pub const PLAIN_TEXT: InsertTextFormat = InsertTextFormat(1);
    // The primary text to be inserted is treated as a snippet.
    //
    // A snippet can define tab stops and placeholders with `$1`, `$2`
    // and `${3:foo}`. `$0` defines the final tab stop, it defaults to
    // the end of the snippet. Placeholders with equal identifiers are linked,
    // that is typing in one will update others too.
    //
    // See also: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#snippet_syntax
    pub const SNIPPET: InsertTextFormat = InsertTextFormat(2);
}

impl IsZero for InsertTextFormat {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for InsertTextFormat {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for InsertTextFormat {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _INSERT_TEXT_FORMAT_NAME: &str = "PlainTextSnippet";
const _INSERT_TEXT_FORMAT_INDEX: [u16; 3] = [0, 9, 16];

impl InsertTextFormat {
    // Go: (e InsertTextFormat) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _INSERT_TEXT_FORMAT_INDEX.len() as i64 - 1 {
            return format!("InsertTextFormat({})", self.0);
        }
        let i = i as usize;
        _INSERT_TEXT_FORMAT_NAME
            [_INSERT_TEXT_FORMAT_INDEX[i] as usize.._INSERT_TEXT_FORMAT_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for InsertTextFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// How whitespace and indentation is handled during completion
// item insertion.
//
// Since: 3.16.0
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct InsertTextMode(pub u32);

impl InsertTextMode {
    // The insertion or replace strings is taken as it is. If the
    // value is multi line the lines below the cursor will be
    // inserted using the indentation defined in the string value.
    // The client will not apply any kind of adjustments to the
    // string.
    pub const AS_IS: InsertTextMode = InsertTextMode(1);
    // The editor adjusts leading whitespace of new lines so that
    // they match the indentation up to the cursor of the line for
    // which the item is accepted.
    //
    // Consider a line like this: <2tabs><cursor><3tabs>foo. Accepting a
    // multi line completion item is indented using 2 tabs and all
    // following lines inserted will be indented using 2 tabs as well.
    pub const ADJUST_INDENTATION: InsertTextMode = InsertTextMode(2);
}

impl IsZero for InsertTextMode {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for InsertTextMode {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for InsertTextMode {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _INSERT_TEXT_MODE_NAME: &str = "asIsadjustIndentation";
const _INSERT_TEXT_MODE_INDEX: [u16; 3] = [0, 4, 21];

impl InsertTextMode {
    // Go: (e InsertTextMode) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _INSERT_TEXT_MODE_INDEX.len() as i64 - 1 {
            return format!("InsertTextMode({})", self.0);
        }
        let i = i as usize;
        _INSERT_TEXT_MODE_NAME
            [_INSERT_TEXT_MODE_INDEX[i] as usize.._INSERT_TEXT_MODE_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for InsertTextMode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// A document highlight kind.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct DocumentHighlightKind(pub u32);

impl DocumentHighlightKind {
    // A textual occurrence.
    pub const TEXT: DocumentHighlightKind = DocumentHighlightKind(1);
    // Read-access of a symbol, like reading a variable.
    pub const READ: DocumentHighlightKind = DocumentHighlightKind(2);
    // Write-access of a symbol, like writing to a variable.
    pub const WRITE: DocumentHighlightKind = DocumentHighlightKind(3);
}

impl IsZero for DocumentHighlightKind {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for DocumentHighlightKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for DocumentHighlightKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _DOCUMENT_HIGHLIGHT_KIND_NAME: &str = "TextReadWrite";
const _DOCUMENT_HIGHLIGHT_KIND_INDEX: [u16; 4] = [0, 4, 8, 13];

impl DocumentHighlightKind {
    // Go: (e DocumentHighlightKind) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _DOCUMENT_HIGHLIGHT_KIND_INDEX.len() as i64 - 1 {
            return format!("DocumentHighlightKind({})", self.0);
        }
        let i = i as usize;
        _DOCUMENT_HIGHLIGHT_KIND_NAME[_DOCUMENT_HIGHLIGHT_KIND_INDEX[i] as usize
            .._DOCUMENT_HIGHLIGHT_KIND_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for DocumentHighlightKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// A set of predefined code action kinds
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CodeActionKind(pub Cow<'static, str>);

impl CodeActionKind {
    // Empty kind.
    pub const EMPTY: CodeActionKind = CodeActionKind(Cow::Borrowed(""));
    // Base kind for quickfix actions: 'quickfix'
    pub const QUICK_FIX: CodeActionKind = CodeActionKind(Cow::Borrowed("quickfix"));
    // Base kind for refactoring actions: 'refactor'
    pub const REFACTOR: CodeActionKind = CodeActionKind(Cow::Borrowed("refactor"));
    // Base kind for refactoring extraction actions: 'refactor.extract'
    //
    // Example extract actions:
    //
    // - Extract method
    // - Extract function
    // - Extract variable
    // - Extract interface from class
    // - ...
    pub const REFACTOR_EXTRACT: CodeActionKind = CodeActionKind(Cow::Borrowed("refactor.extract"));
    // Base kind for refactoring inline actions: 'refactor.inline'
    //
    // Example inline actions:
    //
    // - Inline function
    // - Inline variable
    // - Inline constant
    // - ...
    pub const REFACTOR_INLINE: CodeActionKind = CodeActionKind(Cow::Borrowed("refactor.inline"));
    // Base kind for refactoring move actions: `refactor.move`
    //
    // Example move actions:
    //
    // - Move a function to a new file
    // - Move a property between classes
    // - Move method to base class
    // - ...
    //
    // Since: 3.18.0
    pub const REFACTOR_MOVE: CodeActionKind = CodeActionKind(Cow::Borrowed("refactor.move"));
    // Base kind for refactoring rewrite actions: 'refactor.rewrite'
    //
    // Example rewrite actions:
    //
    // - Convert JavaScript function to class
    // - Add or remove parameter
    // - Encapsulate field
    // - Make method static
    // - Move method to base class
    // - ...
    pub const REFACTOR_REWRITE: CodeActionKind = CodeActionKind(Cow::Borrowed("refactor.rewrite"));
    // Base kind for source actions: `source`
    //
    // Source code actions apply to the entire file.
    pub const SOURCE: CodeActionKind = CodeActionKind(Cow::Borrowed("source"));
    // Base kind for an organize imports source action: `source.organizeImports`
    pub const SOURCE_ORGANIZE_IMPORTS: CodeActionKind =
        CodeActionKind(Cow::Borrowed("source.organizeImports"));
    // Base kind for auto-fix source actions: `source.fixAll`.
    //
    // Fix all actions automatically fix errors that have a clear fix that do not require user input.
    // They should not suppress errors or perform unsafe fixes such as generating new types or classes.
    //
    // Since: 3.15.0
    pub const SOURCE_FIX_ALL: CodeActionKind = CodeActionKind(Cow::Borrowed("source.fixAll"));
}

impl IsZero for CodeActionKind {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for CodeActionKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for CodeActionKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

// Code action tags are extra annotations that tweak the behavior of a code action.
//
// Since: 3.18.0
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CodeActionTag(pub u32);

impl CodeActionTag {
    // Marks the code action as LLM-generated.
    pub const LLM_GENERATED: CodeActionTag = CodeActionTag(1);
}

impl IsZero for CodeActionTag {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for CodeActionTag {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for CodeActionTag {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _CODE_ACTION_TAG_NAME: &str = "LLMGenerated";
const _CODE_ACTION_TAG_INDEX: [u16; 2] = [0, 12];

impl CodeActionTag {
    // Go: (e CodeActionTag) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _CODE_ACTION_TAG_INDEX.len() as i64 - 1 {
            return format!("CodeActionTag({})", self.0);
        }
        let i = i as usize;
        _CODE_ACTION_TAG_NAME
            [_CODE_ACTION_TAG_INDEX[i] as usize.._CODE_ACTION_TAG_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for CodeActionTag {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct TraceValue(pub Cow<'static, str>);

impl TraceValue {
    // Turn tracing off.
    pub const OFF: TraceValue = TraceValue(Cow::Borrowed("off"));
    // Trace messages only.
    pub const MESSAGES: TraceValue = TraceValue(Cow::Borrowed("messages"));
    // Verbose message tracing.
    pub const VERBOSE: TraceValue = TraceValue(Cow::Borrowed("verbose"));
}

impl IsZero for TraceValue {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for TraceValue {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for TraceValue {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

// Describes the content type that a client supports in various
// result literals like `Hover`, `ParameterInfo` or `CompletionItem`.
//
// Please note that `MarkupKinds` must not start with a `$`. This kinds
// are reserved for internal usage.
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct MarkupKind(pub Cow<'static, str>);

impl MarkupKind {
    // Plain text is supported as a content format
    pub const PLAIN_TEXT: MarkupKind = MarkupKind(Cow::Borrowed("plaintext"));
    // Markdown is supported as a content format
    pub const MARKDOWN: MarkupKind = MarkupKind(Cow::Borrowed("markdown"));
}

impl IsZero for MarkupKind {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for MarkupKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for MarkupKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

// Predefined Language kinds
//
// Since: 3.18.0
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct LanguageKind(pub Cow<'static, str>);

impl LanguageKind {
    pub const ABAP: LanguageKind = LanguageKind(Cow::Borrowed("abap"));
    pub const WINDOWS_BAT: LanguageKind = LanguageKind(Cow::Borrowed("bat"));
    pub const BIB_TE_X: LanguageKind = LanguageKind(Cow::Borrowed("bibtex"));
    pub const CLOJURE: LanguageKind = LanguageKind(Cow::Borrowed("clojure"));
    pub const COFFEESCRIPT: LanguageKind = LanguageKind(Cow::Borrowed("coffeescript"));
    pub const C: LanguageKind = LanguageKind(Cow::Borrowed("c"));
    pub const CPP: LanguageKind = LanguageKind(Cow::Borrowed("cpp"));
    pub const C_SHARP: LanguageKind = LanguageKind(Cow::Borrowed("csharp"));
    pub const CSS: LanguageKind = LanguageKind(Cow::Borrowed("css"));
    // Since: 3.18.0
    pub const D: LanguageKind = LanguageKind(Cow::Borrowed("d"));
    // Since: 3.18.0
    pub const DELPHI: LanguageKind = LanguageKind(Cow::Borrowed("pascal"));
    pub const DIFF: LanguageKind = LanguageKind(Cow::Borrowed("diff"));
    pub const DART: LanguageKind = LanguageKind(Cow::Borrowed("dart"));
    pub const DOCKERFILE: LanguageKind = LanguageKind(Cow::Borrowed("dockerfile"));
    pub const ELIXIR: LanguageKind = LanguageKind(Cow::Borrowed("elixir"));
    pub const ERLANG: LanguageKind = LanguageKind(Cow::Borrowed("erlang"));
    pub const F_SHARP: LanguageKind = LanguageKind(Cow::Borrowed("fsharp"));
    pub const GIT_COMMIT: LanguageKind = LanguageKind(Cow::Borrowed("git-commit"));
    pub const GIT_REBASE: LanguageKind = LanguageKind(Cow::Borrowed("git-rebase"));
    pub const GO: LanguageKind = LanguageKind(Cow::Borrowed("go"));
    pub const GROOVY: LanguageKind = LanguageKind(Cow::Borrowed("groovy"));
    pub const HANDLEBARS: LanguageKind = LanguageKind(Cow::Borrowed("handlebars"));
    pub const HASKELL: LanguageKind = LanguageKind(Cow::Borrowed("haskell"));
    pub const HTML: LanguageKind = LanguageKind(Cow::Borrowed("html"));
    pub const INI: LanguageKind = LanguageKind(Cow::Borrowed("ini"));
    pub const JAVA: LanguageKind = LanguageKind(Cow::Borrowed("java"));
    pub const JAVA_SCRIPT: LanguageKind = LanguageKind(Cow::Borrowed("javascript"));
    pub const JAVA_SCRIPT_REACT: LanguageKind = LanguageKind(Cow::Borrowed("javascriptreact"));
    pub const JSON: LanguageKind = LanguageKind(Cow::Borrowed("json"));
    pub const LA_TE_X: LanguageKind = LanguageKind(Cow::Borrowed("latex"));
    pub const LESS: LanguageKind = LanguageKind(Cow::Borrowed("less"));
    pub const LUA: LanguageKind = LanguageKind(Cow::Borrowed("lua"));
    pub const MAKEFILE: LanguageKind = LanguageKind(Cow::Borrowed("makefile"));
    pub const MARKDOWN: LanguageKind = LanguageKind(Cow::Borrowed("markdown"));
    pub const OBJECTIVE_C: LanguageKind = LanguageKind(Cow::Borrowed("objective-c"));
    pub const OBJECTIVE_CPP: LanguageKind = LanguageKind(Cow::Borrowed("objective-cpp"));
    // Since: 3.18.0
    pub const PASCAL: LanguageKind = LanguageKind(Cow::Borrowed("pascal"));
    pub const PERL: LanguageKind = LanguageKind(Cow::Borrowed("perl"));
    pub const PERL6: LanguageKind = LanguageKind(Cow::Borrowed("perl6"));
    pub const PHP: LanguageKind = LanguageKind(Cow::Borrowed("php"));
    pub const PLAINTEXT: LanguageKind = LanguageKind(Cow::Borrowed("plaintext"));
    pub const POWERSHELL: LanguageKind = LanguageKind(Cow::Borrowed("powershell"));
    pub const PUG: LanguageKind = LanguageKind(Cow::Borrowed("jade"));
    pub const PYTHON: LanguageKind = LanguageKind(Cow::Borrowed("python"));
    pub const R: LanguageKind = LanguageKind(Cow::Borrowed("r"));
    pub const RAZOR: LanguageKind = LanguageKind(Cow::Borrowed("razor"));
    pub const RUBY: LanguageKind = LanguageKind(Cow::Borrowed("ruby"));
    pub const RUST: LanguageKind = LanguageKind(Cow::Borrowed("rust"));
    pub const SCSS: LanguageKind = LanguageKind(Cow::Borrowed("scss"));
    pub const SASS: LanguageKind = LanguageKind(Cow::Borrowed("sass"));
    pub const SCALA: LanguageKind = LanguageKind(Cow::Borrowed("scala"));
    pub const SHADER_LAB: LanguageKind = LanguageKind(Cow::Borrowed("shaderlab"));
    pub const SHELL_SCRIPT: LanguageKind = LanguageKind(Cow::Borrowed("shellscript"));
    pub const SQL: LanguageKind = LanguageKind(Cow::Borrowed("sql"));
    pub const SWIFT: LanguageKind = LanguageKind(Cow::Borrowed("swift"));
    pub const TYPE_SCRIPT: LanguageKind = LanguageKind(Cow::Borrowed("typescript"));
    pub const TYPE_SCRIPT_REACT: LanguageKind = LanguageKind(Cow::Borrowed("typescriptreact"));
    pub const TE_X: LanguageKind = LanguageKind(Cow::Borrowed("tex"));
    pub const VISUAL_BASIC: LanguageKind = LanguageKind(Cow::Borrowed("vb"));
    pub const XML: LanguageKind = LanguageKind(Cow::Borrowed("xml"));
    pub const XSL: LanguageKind = LanguageKind(Cow::Borrowed("xsl"));
    pub const YAML: LanguageKind = LanguageKind(Cow::Borrowed("yaml"));
}

impl IsZero for LanguageKind {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for LanguageKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for LanguageKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

// Describes how an provider was triggered.
//
// Since: 3.18.0
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct InlineCompletionTriggerKind(pub u32);

impl InlineCompletionTriggerKind {
    // Completion was triggered explicitly by a user gesture.
    pub const INVOKED: InlineCompletionTriggerKind = InlineCompletionTriggerKind(1);
    // Completion was triggered automatically while editing.
    pub const AUTOMATIC: InlineCompletionTriggerKind = InlineCompletionTriggerKind(2);
}

impl IsZero for InlineCompletionTriggerKind {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for InlineCompletionTriggerKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for InlineCompletionTriggerKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _INLINE_COMPLETION_TRIGGER_KIND_NAME: &str = "InvokedAutomatic";
const _INLINE_COMPLETION_TRIGGER_KIND_INDEX: [u16; 3] = [0, 7, 16];

impl InlineCompletionTriggerKind {
    // Go: (e InlineCompletionTriggerKind) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _INLINE_COMPLETION_TRIGGER_KIND_INDEX.len() as i64 - 1 {
            return format!("InlineCompletionTriggerKind({})", self.0);
        }
        let i = i as usize;
        _INLINE_COMPLETION_TRIGGER_KIND_NAME[_INLINE_COMPLETION_TRIGGER_KIND_INDEX[i] as usize
            .._INLINE_COMPLETION_TRIGGER_KIND_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for InlineCompletionTriggerKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// A set of predefined position encoding kinds.
//
// Since: 3.17.0
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct PositionEncodingKind(pub Cow<'static, str>);

impl PositionEncodingKind {
    // Character offsets count UTF-8 code units (e.g. bytes).
    pub const UTF8: PositionEncodingKind = PositionEncodingKind(Cow::Borrowed("utf-8"));
    // Character offsets count UTF-16 code units.
    //
    // This is the default and must always be supported
    // by servers
    pub const UTF16: PositionEncodingKind = PositionEncodingKind(Cow::Borrowed("utf-16"));
    // Character offsets count UTF-32 code units.
    //
    // Implementation note: these are the same as Unicode codepoints,
    // so this `PositionEncodingKind` may also be used for an
    // encoding-agnostic representation of character offsets.
    pub const UTF32: PositionEncodingKind = PositionEncodingKind(Cow::Borrowed("utf-32"));
}

impl IsZero for PositionEncodingKind {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for PositionEncodingKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for PositionEncodingKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

// The file event type
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct FileChangeType(pub u32);

impl FileChangeType {
    // The file got created.
    pub const CREATED: FileChangeType = FileChangeType(1);
    // The file got changed.
    pub const CHANGED: FileChangeType = FileChangeType(2);
    // The file got deleted.
    pub const DELETED: FileChangeType = FileChangeType(3);
}

impl IsZero for FileChangeType {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for FileChangeType {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for FileChangeType {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _FILE_CHANGE_TYPE_NAME: &str = "CreatedChangedDeleted";
const _FILE_CHANGE_TYPE_INDEX: [u16; 4] = [0, 7, 14, 21];

impl FileChangeType {
    // Go: (e FileChangeType) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _FILE_CHANGE_TYPE_INDEX.len() as i64 - 1 {
            return format!("FileChangeType({})", self.0);
        }
        let i = i as usize;
        _FILE_CHANGE_TYPE_NAME
            [_FILE_CHANGE_TYPE_INDEX[i] as usize.._FILE_CHANGE_TYPE_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for FileChangeType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct WatchKind(pub u32);

impl WatchKind {
    // Interested in create events.
    pub const CREATE: WatchKind = WatchKind(1);
    // Interested in change events
    pub const CHANGE: WatchKind = WatchKind(2);
    // Interested in delete events
    pub const DELETE: WatchKind = WatchKind(4);
}

impl IsZero for WatchKind {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for WatchKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for WatchKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _WATCH_KIND_NAME: &str = "CreateChangeDelete";
const _WATCH_KIND_INDEX: [u16; 4] = [0, 6, 12, 18];

impl WatchKind {
    // Go: (e WatchKind) String
    pub fn string(&self) -> String {
        if self.0 == 0 {
            return "0".to_string();
        }
        let mut parts: Vec<&str> = Vec::new();
        if self.0 & 1 != 0 {
            parts.push(
                &_WATCH_KIND_NAME[_WATCH_KIND_INDEX[0] as usize.._WATCH_KIND_INDEX[1] as usize],
            );
        }
        if self.0 & 2 != 0 {
            parts.push(
                &_WATCH_KIND_NAME[_WATCH_KIND_INDEX[1] as usize.._WATCH_KIND_INDEX[2] as usize],
            );
        }
        if self.0 & 4 != 0 {
            parts.push(
                &_WATCH_KIND_NAME[_WATCH_KIND_INDEX[2] as usize.._WATCH_KIND_INDEX[3] as usize],
            );
        }
        if parts.is_empty() {
            return format!("WatchKind({})", self.0);
        }
        parts.join("|")
    }
}

impl std::fmt::Display for WatchKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// The diagnostic's severity.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct DiagnosticSeverity(pub u32);

impl DiagnosticSeverity {
    // Reports an error.
    pub const ERROR: DiagnosticSeverity = DiagnosticSeverity(1);
    // Reports a warning.
    pub const WARNING: DiagnosticSeverity = DiagnosticSeverity(2);
    // Reports an information.
    pub const INFORMATION: DiagnosticSeverity = DiagnosticSeverity(3);
    // Reports a hint.
    pub const HINT: DiagnosticSeverity = DiagnosticSeverity(4);
}

impl IsZero for DiagnosticSeverity {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for DiagnosticSeverity {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for DiagnosticSeverity {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _DIAGNOSTIC_SEVERITY_NAME: &str = "ErrorWarningInformationHint";
const _DIAGNOSTIC_SEVERITY_INDEX: [u16; 5] = [0, 5, 12, 23, 27];

impl DiagnosticSeverity {
    // Go: (e DiagnosticSeverity) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _DIAGNOSTIC_SEVERITY_INDEX.len() as i64 - 1 {
            return format!("DiagnosticSeverity({})", self.0);
        }
        let i = i as usize;
        _DIAGNOSTIC_SEVERITY_NAME
            [_DIAGNOSTIC_SEVERITY_INDEX[i] as usize.._DIAGNOSTIC_SEVERITY_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for DiagnosticSeverity {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// The diagnostic tags.
//
// Since: 3.15.0
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct DiagnosticTag(pub u32);

impl DiagnosticTag {
    // Unused or unnecessary code.
    //
    // Clients are allowed to render diagnostics with this tag faded out instead of having
    // an error squiggle.
    pub const UNNECESSARY: DiagnosticTag = DiagnosticTag(1);
    // Deprecated or obsolete code.
    //
    // Clients are allowed to rendered diagnostics with this tag strike through.
    pub const DEPRECATED: DiagnosticTag = DiagnosticTag(2);
}

impl IsZero for DiagnosticTag {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for DiagnosticTag {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for DiagnosticTag {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _DIAGNOSTIC_TAG_NAME: &str = "UnnecessaryDeprecated";
const _DIAGNOSTIC_TAG_INDEX: [u16; 3] = [0, 11, 21];

impl DiagnosticTag {
    // Go: (e DiagnosticTag) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _DIAGNOSTIC_TAG_INDEX.len() as i64 - 1 {
            return format!("DiagnosticTag({})", self.0);
        }
        let i = i as usize;
        _DIAGNOSTIC_TAG_NAME
            [_DIAGNOSTIC_TAG_INDEX[i] as usize.._DIAGNOSTIC_TAG_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for DiagnosticTag {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// How a completion was triggered
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CompletionTriggerKind(pub u32);

impl CompletionTriggerKind {
    // Completion was triggered by typing an identifier (24x7 code
    // complete), manual invocation (e.g Ctrl+Space) or via API.
    pub const INVOKED: CompletionTriggerKind = CompletionTriggerKind(1);
    // Completion was triggered by a trigger character specified by
    // the `triggerCharacters` properties of the `CompletionRegistrationOptions`.
    pub const TRIGGER_CHARACTER: CompletionTriggerKind = CompletionTriggerKind(2);
    // Completion was re-triggered as current completion list is incomplete
    pub const TRIGGER_FOR_INCOMPLETE_COMPLETIONS: CompletionTriggerKind = CompletionTriggerKind(3);
}

impl IsZero for CompletionTriggerKind {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for CompletionTriggerKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for CompletionTriggerKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _COMPLETION_TRIGGER_KIND_NAME: &str =
    "InvokedTriggerCharacterTriggerForIncompleteCompletions";
const _COMPLETION_TRIGGER_KIND_INDEX: [u16; 4] = [0, 7, 23, 54];

impl CompletionTriggerKind {
    // Go: (e CompletionTriggerKind) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _COMPLETION_TRIGGER_KIND_INDEX.len() as i64 - 1 {
            return format!("CompletionTriggerKind({})", self.0);
        }
        let i = i as usize;
        _COMPLETION_TRIGGER_KIND_NAME[_COMPLETION_TRIGGER_KIND_INDEX[i] as usize
            .._COMPLETION_TRIGGER_KIND_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for CompletionTriggerKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// Defines how values from a set of defaults and an individual item will be
// merged.
//
// Since: 3.18.0
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ApplyKind(pub u32);

impl ApplyKind {
    // The value from the individual item (if provided and not `null`) will be
    // used instead of the default.
    pub const REPLACE: ApplyKind = ApplyKind(1);
    // The value from the item will be merged with the default.
    //
    // The specific rules for mergeing values are defined against each field
    // that supports merging.
    pub const MERGE: ApplyKind = ApplyKind(2);
}

impl IsZero for ApplyKind {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for ApplyKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for ApplyKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _APPLY_KIND_NAME: &str = "ReplaceMerge";
const _APPLY_KIND_INDEX: [u16; 3] = [0, 7, 12];

impl ApplyKind {
    // Go: (e ApplyKind) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _APPLY_KIND_INDEX.len() as i64 - 1 {
            return format!("ApplyKind({})", self.0);
        }
        let i = i as usize;
        _APPLY_KIND_NAME[_APPLY_KIND_INDEX[i] as usize.._APPLY_KIND_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for ApplyKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// How a signature help was triggered.
//
// Since: 3.15.0
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct SignatureHelpTriggerKind(pub u32);

impl SignatureHelpTriggerKind {
    // Signature help was invoked manually by the user or by a command.
    pub const INVOKED: SignatureHelpTriggerKind = SignatureHelpTriggerKind(1);
    // Signature help was triggered by a trigger character.
    pub const TRIGGER_CHARACTER: SignatureHelpTriggerKind = SignatureHelpTriggerKind(2);
    // Signature help was triggered by the cursor moving or by the document content changing.
    pub const CONTENT_CHANGE: SignatureHelpTriggerKind = SignatureHelpTriggerKind(3);
}

impl IsZero for SignatureHelpTriggerKind {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for SignatureHelpTriggerKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for SignatureHelpTriggerKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _SIGNATURE_HELP_TRIGGER_KIND_NAME: &str = "InvokedTriggerCharacterContentChange";
const _SIGNATURE_HELP_TRIGGER_KIND_INDEX: [u16; 4] = [0, 7, 23, 36];

impl SignatureHelpTriggerKind {
    // Go: (e SignatureHelpTriggerKind) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _SIGNATURE_HELP_TRIGGER_KIND_INDEX.len() as i64 - 1 {
            return format!("SignatureHelpTriggerKind({})", self.0);
        }
        let i = i as usize;
        _SIGNATURE_HELP_TRIGGER_KIND_NAME[_SIGNATURE_HELP_TRIGGER_KIND_INDEX[i] as usize
            .._SIGNATURE_HELP_TRIGGER_KIND_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for SignatureHelpTriggerKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// The reason why code actions were requested.
//
// Since: 3.17.0
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CodeActionTriggerKind(pub u32);

impl CodeActionTriggerKind {
    // Code actions were explicitly requested by the user or by an extension.
    pub const INVOKED: CodeActionTriggerKind = CodeActionTriggerKind(1);
    // Code actions were requested automatically.
    //
    // This typically happens when current selection in a file changes, but can
    // also be triggered when file content changes.
    pub const AUTOMATIC: CodeActionTriggerKind = CodeActionTriggerKind(2);
}

impl IsZero for CodeActionTriggerKind {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for CodeActionTriggerKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for CodeActionTriggerKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _CODE_ACTION_TRIGGER_KIND_NAME: &str = "InvokedAutomatic";
const _CODE_ACTION_TRIGGER_KIND_INDEX: [u16; 3] = [0, 7, 16];

impl CodeActionTriggerKind {
    // Go: (e CodeActionTriggerKind) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _CODE_ACTION_TRIGGER_KIND_INDEX.len() as i64 - 1 {
            return format!("CodeActionTriggerKind({})", self.0);
        }
        let i = i as usize;
        _CODE_ACTION_TRIGGER_KIND_NAME[_CODE_ACTION_TRIGGER_KIND_INDEX[i] as usize
            .._CODE_ACTION_TRIGGER_KIND_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for CodeActionTriggerKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// A pattern kind describing if a glob pattern matches a file a folder or
// both.
//
// Since: 3.16.0
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct FileOperationPatternKind(pub Cow<'static, str>);

impl FileOperationPatternKind {
    // The pattern matches a file only.
    pub const FILE: FileOperationPatternKind = FileOperationPatternKind(Cow::Borrowed("file"));
    // The pattern matches a folder only.
    pub const FOLDER: FileOperationPatternKind = FileOperationPatternKind(Cow::Borrowed("folder"));
}

impl IsZero for FileOperationPatternKind {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for FileOperationPatternKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for FileOperationPatternKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ResourceOperationKind(pub Cow<'static, str>);

impl ResourceOperationKind {
    // Supports creating new files and folders.
    pub const CREATE: ResourceOperationKind = ResourceOperationKind(Cow::Borrowed("create"));
    // Supports renaming existing files and folders.
    pub const RENAME: ResourceOperationKind = ResourceOperationKind(Cow::Borrowed("rename"));
    // Supports deleting existing files and folders.
    pub const DELETE: ResourceOperationKind = ResourceOperationKind(Cow::Borrowed("delete"));
}

impl IsZero for ResourceOperationKind {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for ResourceOperationKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for ResourceOperationKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct FailureHandlingKind(pub Cow<'static, str>);

impl FailureHandlingKind {
    // Applying the workspace change is simply aborted if one of the changes provided
    // fails. All operations executed before the failing operation stay executed.
    pub const ABORT: FailureHandlingKind = FailureHandlingKind(Cow::Borrowed("abort"));
    // All operations are executed transactional. That means they either all
    // succeed or no changes at all are applied to the workspace.
    pub const TRANSACTIONAL: FailureHandlingKind =
        FailureHandlingKind(Cow::Borrowed("transactional"));
    // If the workspace edit contains only textual file changes they are executed transactional.
    // If resource changes (create, rename or delete file) are part of the change the failure
    // handling strategy is abort.
    pub const TEXT_ONLY_TRANSACTIONAL: FailureHandlingKind =
        FailureHandlingKind(Cow::Borrowed("textOnlyTransactional"));
    // The client tries to undo the operations already executed. But there is no
    // guarantee that this is succeeding.
    pub const UNDO: FailureHandlingKind = FailureHandlingKind(Cow::Borrowed("undo"));
}

impl IsZero for FailureHandlingKind {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for FailureHandlingKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for FailureHandlingKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct PrepareSupportDefaultBehavior(pub u32);

impl PrepareSupportDefaultBehavior {
    // The client's default behavior is to select the identifier
    // according the to language's syntax rule.
    pub const IDENTIFIER: PrepareSupportDefaultBehavior = PrepareSupportDefaultBehavior(1);
}

impl IsZero for PrepareSupportDefaultBehavior {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for PrepareSupportDefaultBehavior {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for PrepareSupportDefaultBehavior {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _PREPARE_SUPPORT_DEFAULT_BEHAVIOR_NAME: &str = "Identifier";
const _PREPARE_SUPPORT_DEFAULT_BEHAVIOR_INDEX: [u16; 2] = [0, 10];

impl PrepareSupportDefaultBehavior {
    // Go: (e PrepareSupportDefaultBehavior) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (1);
        if i < 0 || i >= _PREPARE_SUPPORT_DEFAULT_BEHAVIOR_INDEX.len() as i64 - 1 {
            return format!("PrepareSupportDefaultBehavior({})", self.0);
        }
        let i = i as usize;
        _PREPARE_SUPPORT_DEFAULT_BEHAVIOR_NAME[_PREPARE_SUPPORT_DEFAULT_BEHAVIOR_INDEX[i] as usize
            .._PREPARE_SUPPORT_DEFAULT_BEHAVIOR_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for PrepareSupportDefaultBehavior {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct TokenFormat(pub Cow<'static, str>);

impl TokenFormat {
    pub const RELATIVE: TokenFormat = TokenFormat(Cow::Borrowed("relative"));
}

impl IsZero for TokenFormat {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for TokenFormat {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for TokenFormat {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

// Layout style for a VSContainerElement's children, mirroring VS's Microsoft.VisualStudio.Text.Adornments.ContainerElementStyle.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct VSContainerElementStyle(pub i32);

impl VSContainerElementStyle {
    // Child elements are laid out inline, wrapping as needed (e.g. an icon next to a signature line).
    pub const WRAPPED: VSContainerElementStyle = VSContainerElementStyle(0);
    // Child elements are stacked vertically, each on its own line (e.g. a signature line followed by documentation).
    pub const STACKED: VSContainerElementStyle = VSContainerElementStyle(1);
}

impl IsZero for VSContainerElementStyle {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for VSContainerElementStyle {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for VSContainerElementStyle {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _VS_CONTAINER_ELEMENT_STYLE_NAME: &str = "WrappedStacked";
const _VS_CONTAINER_ELEMENT_STYLE_INDEX: [u16; 3] = [0, 7, 14];

impl VSContainerElementStyle {
    // Go: (e VSContainerElementStyle) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (0);
        if i < 0 || i >= _VS_CONTAINER_ELEMENT_STYLE_INDEX.len() as i64 - 1 {
            return format!("VSContainerElementStyle({})", self.0);
        }
        let i = i as usize;
        _VS_CONTAINER_ELEMENT_STYLE_NAME[_VS_CONTAINER_ELEMENT_STYLE_INDEX[i] as usize
            .._VS_CONTAINER_ELEMENT_STYLE_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for VSContainerElementStyle {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// Log verbosity level, mirroring the VS Code LogLevel enum values.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct LogVerbosity(pub i32);

impl LogVerbosity {
    // All logging disabled.
    pub const OFF: LogVerbosity = LogVerbosity(0);
    // Most verbose; includes LSP request/response traces.
    pub const TRACE: LogVerbosity = LogVerbosity(1);
    // Verbose server logs.
    pub const DEBUG: LogVerbosity = LogVerbosity(2);
    // Normal server logs.
    pub const INFO: LogVerbosity = LogVerbosity(3);
    // Warnings only.
    pub const WARNING: LogVerbosity = LogVerbosity(4);
    // Errors only.
    pub const ERROR: LogVerbosity = LogVerbosity(5);
}

impl IsZero for LogVerbosity {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for LogVerbosity {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for LogVerbosity {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _LOG_VERBOSITY_NAME: &str = "OffTraceDebugInfoWarningError";
const _LOG_VERBOSITY_INDEX: [u16; 7] = [0, 3, 8, 13, 17, 24, 29];

impl LogVerbosity {
    // Go: (e LogVerbosity) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (0);
        if i < 0 || i >= _LOG_VERBOSITY_INDEX.len() as i64 - 1 {
            return format!("LogVerbosity({})", self.0);
        }
        let i = i as usize;
        _LOG_VERBOSITY_NAME[_LOG_VERBOSITY_INDEX[i] as usize.._LOG_VERBOSITY_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for LogVerbosity {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// Behavior for tracking and logging flaky diagnostics.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct DiagnosticFlakeLogLevel(pub i32);

impl DiagnosticFlakeLogLevel {
    // All flake logging disabled.
    pub const OFF: DiagnosticFlakeLogLevel = DiagnosticFlakeLogLevel(0);
    // Log flaky diagnostics to the error log.
    pub const LOG: DiagnosticFlakeLogLevel = DiagnosticFlakeLogLevel(1);
    // Panic on flaky diagnostics.
    pub const PANIC: DiagnosticFlakeLogLevel = DiagnosticFlakeLogLevel(2);
}

impl IsZero for DiagnosticFlakeLogLevel {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for DiagnosticFlakeLogLevel {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for DiagnosticFlakeLogLevel {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _DIAGNOSTIC_FLAKE_LOG_LEVEL_NAME: &str = "OffLogPanic";
const _DIAGNOSTIC_FLAKE_LOG_LEVEL_INDEX: [u16; 4] = [0, 3, 6, 11];

impl DiagnosticFlakeLogLevel {
    // Go: (e DiagnosticFlakeLogLevel) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (0);
        if i < 0 || i >= _DIAGNOSTIC_FLAKE_LOG_LEVEL_INDEX.len() as i64 - 1 {
            return format!("DiagnosticFlakeLogLevel({})", self.0);
        }
        let i = i as usize;
        _DIAGNOSTIC_FLAKE_LOG_LEVEL_NAME[_DIAGNOSTIC_FLAKE_LOG_LEVEL_INDEX[i] as usize
            .._DIAGNOSTIC_FLAKE_LOG_LEVEL_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for DiagnosticFlakeLogLevel {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct VSReferenceKind(pub i32);

impl VSReferenceKind {
    pub const INACTIVE: VSReferenceKind = VSReferenceKind(0);
    pub const COMMENT: VSReferenceKind = VSReferenceKind(1);
    pub const STRING: VSReferenceKind = VSReferenceKind(2);
    pub const READ: VSReferenceKind = VSReferenceKind(3);
    pub const WRITE: VSReferenceKind = VSReferenceKind(4);
    pub const REFERENCE: VSReferenceKind = VSReferenceKind(5);
    pub const NAME: VSReferenceKind = VSReferenceKind(6);
    pub const QUALIFIED: VSReferenceKind = VSReferenceKind(7);
    pub const TYPE_ARGUMENT: VSReferenceKind = VSReferenceKind(8);
    pub const TYPE_CONSTRAINT: VSReferenceKind = VSReferenceKind(9);
    pub const BASE_TYPE: VSReferenceKind = VSReferenceKind(10);
    pub const CONSTRUCTOR: VSReferenceKind = VSReferenceKind(11);
    pub const DESTRUCTOR: VSReferenceKind = VSReferenceKind(12);
    pub const IMPORT: VSReferenceKind = VSReferenceKind(13);
    pub const DECLARATION: VSReferenceKind = VSReferenceKind(14);
    pub const ADDRESS_OF: VSReferenceKind = VSReferenceKind(15);
    pub const NOT_REFERENCE: VSReferenceKind = VSReferenceKind(16);
    pub const UNKNOWN: VSReferenceKind = VSReferenceKind(17);
}

impl IsZero for VSReferenceKind {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for VSReferenceKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for VSReferenceKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _VS_REFERENCE_KIND_NAME: &str = "InactiveCommentStringReadWriteReferenceNameQualifiedTypeArgumentTypeConstraintBaseTypeConstructorDestructorImportDeclarationAddressOfNotReferenceUnknown";
const _VS_REFERENCE_KIND_INDEX: [u16; 19] = [
    0, 8, 15, 21, 25, 30, 39, 43, 52, 64, 78, 86, 97, 107, 113, 124, 133, 145, 152,
];

impl VSReferenceKind {
    // Go: (e VSReferenceKind) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (0);
        if i < 0 || i >= _VS_REFERENCE_KIND_INDEX.len() as i64 - 1 {
            return format!("VSReferenceKind({})", self.0);
        }
        let i = i as usize;
        _VS_REFERENCE_KIND_NAME
            [_VS_REFERENCE_KIND_INDEX[i] as usize.._VS_REFERENCE_KIND_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for VSReferenceKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CodeLensKind(pub Cow<'static, str>);

impl CodeLensKind {
    pub const REFERENCES: CodeLensKind = CodeLensKind(Cow::Borrowed("references"));
    pub const IMPLEMENTATIONS: CodeLensKind = CodeLensKind(Cow::Borrowed("implementations"));
}

impl IsZero for CodeLensKind {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for CodeLensKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for CodeLensKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct AutoImportFixKind(pub i32);

impl AutoImportFixKind {
    // Augment an existing namespace import.
    pub const USE_NAMESPACE: AutoImportFixKind = AutoImportFixKind(0);
    // Add a JSDoc-only type import.
    pub const JSDOC_TYPE_IMPORT: AutoImportFixKind = AutoImportFixKind(1);
    // Insert into an existing import declaration.
    pub const ADD_TO_EXISTING: AutoImportFixKind = AutoImportFixKind(2);
    // Create a fresh import statement.
    pub const ADD_NEW: AutoImportFixKind = AutoImportFixKind(3);
    // Promote a type-only import when necessary.
    pub const PROMOTE_TYPE_ONLY: AutoImportFixKind = AutoImportFixKind(4);
}

impl IsZero for AutoImportFixKind {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for AutoImportFixKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for AutoImportFixKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _AUTO_IMPORT_FIX_KIND_NAME: &str =
    "UseNamespaceJsdocTypeImportAddToExistingAddNewPromoteTypeOnly";
const _AUTO_IMPORT_FIX_KIND_INDEX: [u16; 6] = [0, 12, 27, 40, 46, 61];

impl AutoImportFixKind {
    // Go: (e AutoImportFixKind) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (0);
        if i < 0 || i >= _AUTO_IMPORT_FIX_KIND_INDEX.len() as i64 - 1 {
            return format!("AutoImportFixKind({})", self.0);
        }
        let i = i as usize;
        _AUTO_IMPORT_FIX_KIND_NAME
            [_AUTO_IMPORT_FIX_KIND_INDEX[i] as usize.._AUTO_IMPORT_FIX_KIND_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for AutoImportFixKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ImportKind(pub i32);

impl ImportKind {
    // Adds a named import.
    pub const NAMED: ImportKind = ImportKind(0);
    // Adds a default import.
    pub const DEFAULT: ImportKind = ImportKind(1);
    // Adds a namespace import.
    pub const NAMESPACE: ImportKind = ImportKind(2);
    // Adds a CommonJS import assignment.
    pub const COMMON_JS: ImportKind = ImportKind(3);
}

impl IsZero for ImportKind {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for ImportKind {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for ImportKind {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _IMPORT_KIND_NAME: &str = "NamedDefaultNamespaceCommonJS";
const _IMPORT_KIND_INDEX: [u16; 5] = [0, 5, 12, 21, 29];

impl ImportKind {
    // Go: (e ImportKind) String
    pub fn string(&self) -> String {
        let i = self.0 as i64 - (0);
        if i < 0 || i >= _IMPORT_KIND_INDEX.len() as i64 - 1 {
            return format!("ImportKind({})", self.0);
        }
        let i = i as usize;
        _IMPORT_KIND_NAME[_IMPORT_KIND_INDEX[i] as usize.._IMPORT_KIND_INDEX[i + 1] as usize]
            .to_string()
    }
}

impl std::fmt::Display for ImportKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct AddAsTypeOnly(pub i32);

impl AddAsTypeOnly {
    // Import may be marked type-only if needed.
    pub const ALLOWED: AddAsTypeOnly = AddAsTypeOnly(1);
    // Import must be marked type-only.
    pub const REQUIRED: AddAsTypeOnly = AddAsTypeOnly(2);
    // Import cannot be marked type-only.
    pub const NOT_ALLOWED: AddAsTypeOnly = AddAsTypeOnly(4);
}

impl IsZero for AddAsTypeOnly {
    fn is_zero(&self) -> bool {
        self.0 == 0
    }
}

impl MarshalerTo for AddAsTypeOnly {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        self.0.marshal_json_to(enc)
    }
}

impl UnmarshalerFrom for AddAsTypeOnly {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        self.0.unmarshal_json_from(dec)
    }
}

const _ADD_AS_TYPE_ONLY_NAME: &str = "AllowedRequiredNotAllowed";

const _ADD_AS_TYPE_ONLY_INDEX_0: [u16; 3] = [0, 7, 15];

impl AddAsTypeOnly {
    // Go: (e AddAsTypeOnly) String
    pub fn string(&self) -> String {
        let e = self.0;
        if 1 <= e && e <= 2 {
            let i = (e as i64 - (1)) as usize;
            _ADD_AS_TYPE_ONLY_NAME[0 + _ADD_AS_TYPE_ONLY_INDEX_0[i] as usize
                ..0 + _ADD_AS_TYPE_ONLY_INDEX_0[i + 1] as usize]
                .to_string()
        } else if e == 4 {
            _ADD_AS_TYPE_ONLY_NAME[15..25].to_string()
        } else {
            format!("AddAsTypeOnly({})", self.0)
        }
    }
}

impl std::fmt::Display for AddAsTypeOnly {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.string())
    }
}

// Roslyn classification type names used by VS for syntax coloring in tooltips and other UI elements.
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ClassificationTypeName(pub Cow<'static, str>);

impl ClassificationTypeName {
    // Language keyword (e.g., function, const, class).
    pub const KEYWORD: ClassificationTypeName = ClassificationTypeName(Cow::Borrowed("keyword"));
    // Punctuation characters (e.g., parentheses, commas, semicolons).
    pub const PUNCTUATION: ClassificationTypeName =
        ClassificationTypeName(Cow::Borrowed("punctuation"));
    // Operators (e.g., =, +, ?).
    pub const OPERATOR: ClassificationTypeName = ClassificationTypeName(Cow::Borrowed("operator"));
    // Whitespace including spaces and line breaks.
    pub const WHITE_SPACE: ClassificationTypeName =
        ClassificationTypeName(Cow::Borrowed("whitespace"));
    // Plain text with no special classification.
    pub const TEXT: ClassificationTypeName = ClassificationTypeName(Cow::Borrowed("text"));
    // String and literal values.
    pub const STRING: ClassificationTypeName = ClassificationTypeName(Cow::Borrowed("string"));
    // Numeric literal values.
    pub const NUMBER: ClassificationTypeName = ClassificationTypeName(Cow::Borrowed("number"));
    // Comment text.
    pub const COMMENT: ClassificationTypeName = ClassificationTypeName(Cow::Borrowed("comment"));
    // Class names.
    pub const CLASS_NAME: ClassificationTypeName =
        ClassificationTypeName(Cow::Borrowed("class name"));
    // Interface names.
    pub const INTERFACE_NAME: ClassificationTypeName =
        ClassificationTypeName(Cow::Borrowed("interface name"));
    // Enum names.
    pub const ENUM_NAME: ClassificationTypeName =
        ClassificationTypeName(Cow::Borrowed("enum name"));
    // Module/namespace names.
    pub const MODULE_NAME: ClassificationTypeName =
        ClassificationTypeName(Cow::Borrowed("module name"));
    // Method and function names.
    pub const METHOD_NAME: ClassificationTypeName =
        ClassificationTypeName(Cow::Borrowed("method name"));
    // Parameter names.
    pub const PARAMETER_NAME: ClassificationTypeName =
        ClassificationTypeName(Cow::Borrowed("parameter name"));
    // Property and accessor names.
    pub const PROPERTY_NAME: ClassificationTypeName =
        ClassificationTypeName(Cow::Borrowed("property name"));
    // Field names (e.g., enum members).
    pub const FIELD_NAME: ClassificationTypeName =
        ClassificationTypeName(Cow::Borrowed("field name"));
    // Local variable names.
    pub const LOCAL_NAME: ClassificationTypeName =
        ClassificationTypeName(Cow::Borrowed("local name"));
    // Type parameter names.
    pub const TYPE_PARAMETER_NAME: ClassificationTypeName =
        ClassificationTypeName(Cow::Borrowed("type parameter name"));
    // General identifiers (e.g., type aliases, imports).
    pub const IDENTIFIER: ClassificationTypeName =
        ClassificationTypeName(Cow::Borrowed("identifier"));
}

impl IsZero for ClassificationTypeName {
    fn is_zero(&self) -> bool {
        self.0.is_empty()
    }
}

impl MarshalerTo for ClassificationTypeName {
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        <str as MarshalerTo>::marshal_json_to(&self.0, enc)
    }
}

impl UnmarshalerFrom for ClassificationTypeName {
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let mut v = String::new();
        v.unmarshal_json_from(dec)?;
        self.0 = Cow::Owned(v);
        Ok(())
    }
}
