// Code generated by generate.mts; DO NOT EDIT.
//
// Rust port of typescript-go internal/lsp/lsproto/lsp_generated.go (pinned
// dc37b5249), generated from the same meta model by the ported generator.
// Meta model version 3.17.0

use crate::lsp::lsproto::prelude::*;

// Literal types

// StringLiteralBegin is a literal type for "begin"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralBegin;

impl MarshalerTo for StringLiteralBegin {
    // Go: (o StringLiteralBegin) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"begin\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralBegin {
    // Go: (o *StringLiteralBegin) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"begin\"" {
            return Err(err_literal_mismatch("StringLiteralBegin", "\"begin\"", v));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralBegin {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// StringLiteralReport is a literal type for "report"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralReport;

impl MarshalerTo for StringLiteralReport {
    // Go: (o StringLiteralReport) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"report\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralReport {
    // Go: (o *StringLiteralReport) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"report\"" {
            return Err(err_literal_mismatch("StringLiteralReport", "\"report\"", v));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralReport {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// StringLiteralEnd is a literal type for "end"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralEnd;

impl MarshalerTo for StringLiteralEnd {
    // Go: (o StringLiteralEnd) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"end\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralEnd {
    // Go: (o *StringLiteralEnd) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"end\"" {
            return Err(err_literal_mismatch("StringLiteralEnd", "\"end\"", v));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralEnd {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// StringLiteralCreate is a literal type for "create"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralCreate;

impl MarshalerTo for StringLiteralCreate {
    // Go: (o StringLiteralCreate) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"create\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralCreate {
    // Go: (o *StringLiteralCreate) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"create\"" {
            return Err(err_literal_mismatch("StringLiteralCreate", "\"create\"", v));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralCreate {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// StringLiteralRename is a literal type for "rename"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralRename;

impl MarshalerTo for StringLiteralRename {
    // Go: (o StringLiteralRename) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"rename\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralRename {
    // Go: (o *StringLiteralRename) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"rename\"" {
            return Err(err_literal_mismatch("StringLiteralRename", "\"rename\"", v));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralRename {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// StringLiteralDelete is a literal type for "delete"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralDelete;

impl MarshalerTo for StringLiteralDelete {
    // Go: (o StringLiteralDelete) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"delete\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralDelete {
    // Go: (o *StringLiteralDelete) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"delete\"" {
            return Err(err_literal_mismatch("StringLiteralDelete", "\"delete\"", v));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralDelete {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// StringLiteralFull is a literal type for "full"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralFull;

impl MarshalerTo for StringLiteralFull {
    // Go: (o StringLiteralFull) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"full\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralFull {
    // Go: (o *StringLiteralFull) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"full\"" {
            return Err(err_literal_mismatch("StringLiteralFull", "\"full\"", v));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralFull {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// StringLiteralUnchanged is a literal type for "unchanged"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralUnchanged;

impl MarshalerTo for StringLiteralUnchanged {
    // Go: (o StringLiteralUnchanged) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"unchanged\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralUnchanged {
    // Go: (o *StringLiteralUnchanged) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"unchanged\"" {
            return Err(err_literal_mismatch(
                "StringLiteralUnchanged",
                "\"unchanged\"",
                v,
            ));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralUnchanged {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// StringLiteralSnippet is a literal type for "snippet"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralSnippet;

impl MarshalerTo for StringLiteralSnippet {
    // Go: (o StringLiteralSnippet) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"snippet\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralSnippet {
    // Go: (o *StringLiteralSnippet) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"snippet\"" {
            return Err(err_literal_mismatch(
                "StringLiteralSnippet",
                "\"snippet\"",
                v,
            ));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralSnippet {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// StringLiteralLanguageServerErrorResponse is a literal type for "languageServer.errorResponse"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralLanguageServerErrorResponse;

impl MarshalerTo for StringLiteralLanguageServerErrorResponse {
    // Go: (o StringLiteralLanguageServerErrorResponse) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"languageServer.errorResponse\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralLanguageServerErrorResponse {
    // Go: (o *StringLiteralLanguageServerErrorResponse) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"languageServer.errorResponse\"" {
            return Err(err_literal_mismatch(
                "StringLiteralLanguageServerErrorResponse",
                "\"languageServer.errorResponse\"",
                v,
            ));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralLanguageServerErrorResponse {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// StringLiteralError is a literal type for "error"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralError;

impl MarshalerTo for StringLiteralError {
    // Go: (o StringLiteralError) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"error\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralError {
    // Go: (o *StringLiteralError) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"error\"" {
            return Err(err_literal_mismatch("StringLiteralError", "\"error\"", v));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralError {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// StringLiteralLanguageServerPerformanceStats is a literal type for "languageServer.performanceStats"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralLanguageServerPerformanceStats;

impl MarshalerTo for StringLiteralLanguageServerPerformanceStats {
    // Go: (o StringLiteralLanguageServerPerformanceStats) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"languageServer.performanceStats\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralLanguageServerPerformanceStats {
    // Go: (o *StringLiteralLanguageServerPerformanceStats) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"languageServer.performanceStats\"" {
            return Err(err_literal_mismatch(
                "StringLiteralLanguageServerPerformanceStats",
                "\"languageServer.performanceStats\"",
                v,
            ));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralLanguageServerPerformanceStats {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// StringLiteralUsage is a literal type for "usage"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralUsage;

impl MarshalerTo for StringLiteralUsage {
    // Go: (o StringLiteralUsage) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"usage\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralUsage {
    // Go: (o *StringLiteralUsage) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"usage\"" {
            return Err(err_literal_mismatch("StringLiteralUsage", "\"usage\"", v));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralUsage {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// StringLiteralLanguageServerProjectInfo is a literal type for "languageServer.projectInfo"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralLanguageServerProjectInfo;

impl MarshalerTo for StringLiteralLanguageServerProjectInfo {
    // Go: (o StringLiteralLanguageServerProjectInfo) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"languageServer.projectInfo\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralLanguageServerProjectInfo {
    // Go: (o *StringLiteralLanguageServerProjectInfo) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"languageServer.projectInfo\"" {
            return Err(err_literal_mismatch(
                "StringLiteralLanguageServerProjectInfo",
                "\"languageServer.projectInfo\"",
                v,
            ));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralLanguageServerProjectInfo {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// StringLiteralClassifiedTextRun is a literal type for "ClassifiedTextRun"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralClassifiedTextRun;

impl MarshalerTo for StringLiteralClassifiedTextRun {
    // Go: (o StringLiteralClassifiedTextRun) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"ClassifiedTextRun\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralClassifiedTextRun {
    // Go: (o *StringLiteralClassifiedTextRun) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"ClassifiedTextRun\"" {
            return Err(err_literal_mismatch(
                "StringLiteralClassifiedTextRun",
                "\"ClassifiedTextRun\"",
                v,
            ));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralClassifiedTextRun {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// StringLiteralClassifiedTextElement is a literal type for "ClassifiedTextElement"
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct StringLiteralClassifiedTextElement;

impl MarshalerTo for StringLiteralClassifiedTextElement {
    // Go: (o StringLiteralClassifiedTextElement) MarshalJSONTo
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        enc.push_str("\"ClassifiedTextElement\"");
        Ok(())
    }
}

impl UnmarshalerFrom for StringLiteralClassifiedTextElement {
    // Go: (o *StringLiteralClassifiedTextElement) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        let v = dec.read_value()?;
        if v != b"\"ClassifiedTextElement\"" {
            return Err(err_literal_mismatch(
                "StringLiteralClassifiedTextElement",
                "\"ClassifiedTextElement\"",
                v,
            ));
        }
        Ok(())
    }
}

impl IsZero for StringLiteralClassifiedTextElement {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}

// EmptyObject is Go `struct{}`: the empty object literal type `{}`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct EmptyObject;

impl MarshalerTo for EmptyObject {
    // PORT: Go marshals struct{} with the JSON v2 default struct arshaler.
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        write_object_start(enc);
        write_object_end(enc);
        Ok(())
    }
}

impl UnmarshalerFrom for EmptyObject {
    // PORT: Go has no UnmarshalJSONFrom for EmptyObject; this is the JSON v2
    // default struct arshaler.
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        match dec.peek_kind() {
            b'n' => {
                dec.read_token()?;
                *self = EmptyObject::default();
                Ok(())
            }
            b'{' => {
                dec.read_token()?;
                while dec.peek_kind() != b'}' {
                    let mut name = String::new();
                    json_unmarshal_decode(dec, &mut name)?;
                    dec.skip_value()?;
                }
                dec.read_token()?;
                Ok(())
            }
            _ => {
                dec.skip_value()?;
                Err(JsonError {
                    message: "cannot unmarshal JSON value into Go lsproto.EmptyObject".to_string(),
                })
            }
        }
    }
}

impl IsZero for EmptyObject {
    // PORT: Go reflect.Value.IsZero of struct{}.
    fn is_zero(&self) -> bool {
        true
    }
}
