// Code generated by generate.mts; DO NOT EDIT.
//
// Rust port of microsoft/TypeScript tsc/internal/lsp/lsproto/lsp_generated.go
// (pinned 673a5f17d713), generated from the same meta model by the ported generator.
// Meta model version 3.18.0

use crate::lsp::lsproto::prelude::*;

// Methods
impl Method {
    // A request to resolve the implementation locations of a symbol at a given text
    // document position. The request's parameter is of type TextDocumentPositionParams
    // the response is of type Definition or a Thenable that resolves to such.
    pub const TEXT_DOCUMENT_IMPLEMENTATION: Method =
        Method(Cow::Borrowed("textDocument/implementation"));
    // A request to resolve the type definition locations of a symbol at a given text
    // document position. The request's parameter is of type TextDocumentPositionParams
    // the response is of type Definition or a Thenable that resolves to such.
    pub const TEXT_DOCUMENT_TYPE_DEFINITION: Method =
        Method(Cow::Borrowed("textDocument/typeDefinition"));
    // The `workspace/workspaceFolders` is sent from the server to the client to fetch the open workspace folders.
    pub const WORKSPACE_WORKSPACE_FOLDERS: Method =
        Method(Cow::Borrowed("workspace/workspaceFolders"));
    // The 'workspace/configuration' request is sent from the server to the client to fetch a certain
    // configuration setting.
    //
    // This pull model replaces the old push model were the client signaled configuration change via an
    // event. If the server still needs to react to configuration changes (since the server caches the
    // result of `workspace/configuration` requests) the server should register for an empty configuration
    // change event and empty the cache if such an event is received.
    pub const WORKSPACE_CONFIGURATION: Method = Method(Cow::Borrowed("workspace/configuration"));
    // A request to list all color symbols found in a given text document. The request's
    // parameter is of type DocumentColorParams the
    // response is of type ColorInformation[] or a Thenable
    // that resolves to such.
    pub const TEXT_DOCUMENT_DOCUMENT_COLOR: Method =
        Method(Cow::Borrowed("textDocument/documentColor"));
    // A request to list all presentation for a color. The request's
    // parameter is of type ColorPresentationParams the
    // response is of type ColorPresentation[] or a Thenable
    // that resolves to such.
    pub const TEXT_DOCUMENT_COLOR_PRESENTATION: Method =
        Method(Cow::Borrowed("textDocument/colorPresentation"));
    // A request to provide folding ranges in a document. The request's
    // parameter is of type FoldingRangeParams, the
    // response is of type FoldingRangeList or a Thenable
    // that resolves to such.
    pub const TEXT_DOCUMENT_FOLDING_RANGE: Method =
        Method(Cow::Borrowed("textDocument/foldingRange"));
    // A request to refresh the folding ranges in a document.
    //
    // Since: 3.18.0
    pub const WORKSPACE_FOLDING_RANGE_REFRESH: Method =
        Method(Cow::Borrowed("workspace/foldingRange/refresh"));
    // A request to resolve the type definition locations of a symbol at a given text
    // document position. The request's parameter is of type TextDocumentPositionParams
    // the response is of type Declaration or a typed array of DeclarationLink
    // or a Thenable that resolves to such.
    pub const TEXT_DOCUMENT_DECLARATION: Method = Method(Cow::Borrowed("textDocument/declaration"));
    // A request to provide selection ranges in a document. The request's
    // parameter is of type SelectionRangeParams, the
    // response is of type SelectionRange[] or a Thenable
    // that resolves to such.
    pub const TEXT_DOCUMENT_SELECTION_RANGE: Method =
        Method(Cow::Borrowed("textDocument/selectionRange"));
    // The `window/workDoneProgress/create` request is sent from the server to the client to initiate progress
    // reporting from the server.
    pub const WINDOW_WORK_DONE_PROGRESS_CREATE: Method =
        Method(Cow::Borrowed("window/workDoneProgress/create"));
    // A request to result a `CallHierarchyItem` in a document at a given position.
    // Can be used as an input to an incoming or outgoing call hierarchy.
    //
    // Since: 3.16.0
    pub const TEXT_DOCUMENT_PREPARE_CALL_HIERARCHY: Method =
        Method(Cow::Borrowed("textDocument/prepareCallHierarchy"));
    // A request to resolve the incoming calls for a given `CallHierarchyItem`.
    //
    // Since: 3.16.0
    pub const CALL_HIERARCHY_INCOMING_CALLS: Method =
        Method(Cow::Borrowed("callHierarchy/incomingCalls"));
    // A request to resolve the outgoing calls for a given `CallHierarchyItem`.
    //
    // Since: 3.16.0
    pub const CALL_HIERARCHY_OUTGOING_CALLS: Method =
        Method(Cow::Borrowed("callHierarchy/outgoingCalls"));
    // Since: 3.16.0
    pub const TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL: Method =
        Method(Cow::Borrowed("textDocument/semanticTokens/full"));
    // Since: 3.16.0
    pub const TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL_DELTA: Method =
        Method(Cow::Borrowed("textDocument/semanticTokens/full/delta"));
    // Since: 3.16.0
    pub const TEXT_DOCUMENT_SEMANTIC_TOKENS_RANGE: Method =
        Method(Cow::Borrowed("textDocument/semanticTokens/range"));
    // Since: 3.16.0
    pub const WORKSPACE_SEMANTIC_TOKENS_REFRESH: Method =
        Method(Cow::Borrowed("workspace/semanticTokens/refresh"));
    // A request to show a document. This request might open an
    // external program depending on the value of the URI to open.
    // For example a request to open `https://code.visualstudio.com/`
    // will very likely open the URI in a WEB browser.
    //
    // Since: 3.16.0
    pub const WINDOW_SHOW_DOCUMENT: Method = Method(Cow::Borrowed("window/showDocument"));
    // A request to provide ranges that can be edited together.
    //
    // Since: 3.16.0
    pub const TEXT_DOCUMENT_LINKED_EDITING_RANGE: Method =
        Method(Cow::Borrowed("textDocument/linkedEditingRange"));
    // The will create files request is sent from the client to the server before files are actually
    // created as long as the creation is triggered from within the client.
    //
    // The request can return a `WorkspaceEdit` which will be applied to workspace before the
    // files are created. Hence the `WorkspaceEdit` can not manipulate the content of the file
    // to be created.
    //
    // Since: 3.16.0
    pub const WORKSPACE_WILL_CREATE_FILES: Method =
        Method(Cow::Borrowed("workspace/willCreateFiles"));
    // The will rename files request is sent from the client to the server before files are actually
    // renamed as long as the rename is triggered from within the client.
    //
    // Since: 3.16.0
    pub const WORKSPACE_WILL_RENAME_FILES: Method =
        Method(Cow::Borrowed("workspace/willRenameFiles"));
    // The did delete files notification is sent from the client to the server when
    // files were deleted from within the client.
    //
    // Since: 3.16.0
    pub const WORKSPACE_WILL_DELETE_FILES: Method =
        Method(Cow::Borrowed("workspace/willDeleteFiles"));
    // A request to get the moniker of a symbol at a given text document position.
    // The request parameter is of type TextDocumentPositionParams.
    // The response is of type Moniker[] or `null`.
    pub const TEXT_DOCUMENT_MONIKER: Method = Method(Cow::Borrowed("textDocument/moniker"));
    // A request to result a `TypeHierarchyItem` in a document at a given position.
    // Can be used as an input to a subtypes or supertypes type hierarchy.
    //
    // Since: 3.17.0
    pub const TEXT_DOCUMENT_PREPARE_TYPE_HIERARCHY: Method =
        Method(Cow::Borrowed("textDocument/prepareTypeHierarchy"));
    // A request to resolve the supertypes for a given `TypeHierarchyItem`.
    //
    // Since: 3.17.0
    pub const TYPE_HIERARCHY_SUPERTYPES: Method = Method(Cow::Borrowed("typeHierarchy/supertypes"));
    // A request to resolve the subtypes for a given `TypeHierarchyItem`.
    //
    // Since: 3.17.0
    pub const TYPE_HIERARCHY_SUBTYPES: Method = Method(Cow::Borrowed("typeHierarchy/subtypes"));
    // A request to provide inline values in a document. The request's parameter is of
    // type InlineValueParams, the response is of type
    // InlineValue[] or a Thenable that resolves to such.
    //
    // Since: 3.17.0
    pub const TEXT_DOCUMENT_INLINE_VALUE: Method =
        Method(Cow::Borrowed("textDocument/inlineValue"));
    // Since: 3.17.0
    pub const WORKSPACE_INLINE_VALUE_REFRESH: Method =
        Method(Cow::Borrowed("workspace/inlineValue/refresh"));
    // A request to provide inlay hints in a document. The request's parameter is of
    // type InlayHintsParams, the response is of type
    // InlayHint[] or a Thenable that resolves to such.
    //
    // Since: 3.17.0
    pub const TEXT_DOCUMENT_INLAY_HINT: Method = Method(Cow::Borrowed("textDocument/inlayHint"));
    // A request to resolve additional properties for an inlay hint.
    // The request's parameter is of type InlayHint, the response is
    // of type InlayHint or a Thenable that resolves to such.
    //
    // Since: 3.17.0
    pub const INLAY_HINT_RESOLVE: Method = Method(Cow::Borrowed("inlayHint/resolve"));
    // Since: 3.17.0
    pub const WORKSPACE_INLAY_HINT_REFRESH: Method =
        Method(Cow::Borrowed("workspace/inlayHint/refresh"));
    // The document diagnostic request definition.
    //
    // Since: 3.17.0
    pub const TEXT_DOCUMENT_DIAGNOSTIC: Method = Method(Cow::Borrowed("textDocument/diagnostic"));
    // The workspace diagnostic request definition.
    //
    // Since: 3.17.0
    pub const WORKSPACE_DIAGNOSTIC: Method = Method(Cow::Borrowed("workspace/diagnostic"));
    // The diagnostic refresh request definition.
    //
    // Since: 3.17.0
    pub const WORKSPACE_DIAGNOSTIC_REFRESH: Method =
        Method(Cow::Borrowed("workspace/diagnostic/refresh"));
    // A request to provide inline completions in a document. The request's parameter is of
    // type InlineCompletionParams, the response is of type
    // InlineCompletion[] or a Thenable that resolves to such.
    //
    // Since: 3.18.0
    pub const TEXT_DOCUMENT_INLINE_COMPLETION: Method =
        Method(Cow::Borrowed("textDocument/inlineCompletion"));
    // The `workspace/textDocumentContent` request is sent from the client to the
    // server to request the content of a text document.
    //
    // Since: 3.18.0
    pub const WORKSPACE_TEXT_DOCUMENT_CONTENT: Method =
        Method(Cow::Borrowed("workspace/textDocumentContent"));
    // The `workspace/textDocumentContent` request is sent from the server to the client to refresh
    // the content of a specific text document.
    //
    // Since: 3.18.0
    pub const WORKSPACE_TEXT_DOCUMENT_CONTENT_REFRESH: Method =
        Method(Cow::Borrowed("workspace/textDocumentContent/refresh"));
    // The `client/registerCapability` request is sent from the server to the client to register a new capability
    // handler on the client side.
    pub const CLIENT_REGISTER_CAPABILITY: Method =
        Method(Cow::Borrowed("client/registerCapability"));
    // The `client/unregisterCapability` request is sent from the server to the client to unregister a previously registered capability
    // handler on the client side.
    pub const CLIENT_UNREGISTER_CAPABILITY: Method =
        Method(Cow::Borrowed("client/unregisterCapability"));
    // The initialize request is sent from the client to the server.
    // It is sent once as the request after starting up the server.
    // The requests parameter is of type InitializeParams
    // the response if of type InitializeResult of a Thenable that
    // resolves to such.
    pub const INITIALIZE: Method = Method(Cow::Borrowed("initialize"));
    // A shutdown request is sent from the client to the server.
    // It is sent once when the client decides to shutdown the
    // server. The only notification that is sent after a shutdown request
    // is the exit event.
    pub const SHUTDOWN: Method = Method(Cow::Borrowed("shutdown"));
    // The show message request is sent from the server to the client to show a message
    // and a set of options actions to the user.
    pub const WINDOW_SHOW_MESSAGE_REQUEST: Method =
        Method(Cow::Borrowed("window/showMessageRequest"));
    // A document will save request is sent from the client to the server before
    // the document is actually saved. The request can return an array of TextEdits
    // which will be applied to the text document before it is saved. Please note that
    // clients might drop results if computing the text edits took too long or if a
    // server constantly fails on this request. This is done to keep the save fast and
    // reliable.
    pub const TEXT_DOCUMENT_WILL_SAVE_WAIT_UNTIL: Method =
        Method(Cow::Borrowed("textDocument/willSaveWaitUntil"));
    // Request to request completion at a given text document position. The request's
    // parameter is of type TextDocumentPosition the response
    // is of type CompletionItem[] or CompletionList
    // or a Thenable that resolves to such.
    //
    // The request can delay the computation of the `detail`
    // and `documentation` properties to the `completionItem/resolve`
    // request. However, properties that are needed for the initial sorting and filtering, like `sortText`,
    // `filterText`, `insertText`, and `textEdit`, must not be changed during resolve.
    pub const TEXT_DOCUMENT_COMPLETION: Method = Method(Cow::Borrowed("textDocument/completion"));
    // Request to resolve additional information for a given completion item.The request's
    // parameter is of type CompletionItem the response
    // is of type CompletionItem or a Thenable that resolves to such.
    pub const COMPLETION_ITEM_RESOLVE: Method = Method(Cow::Borrowed("completionItem/resolve"));
    // Request to request hover information at a given text document position. The request's
    // parameter is of type TextDocumentPosition the response is of
    // type Hover or a Thenable that resolves to such.
    pub const TEXT_DOCUMENT_HOVER: Method = Method(Cow::Borrowed("textDocument/hover"));
    pub const TEXT_DOCUMENT_SIGNATURE_HELP: Method =
        Method(Cow::Borrowed("textDocument/signatureHelp"));
    // A request to resolve the definition location of a symbol at a given text
    // document position. The request's parameter is of type TextDocumentPosition
    // the response is of either type Definition or a typed array of
    // DefinitionLink or a Thenable that resolves to such.
    pub const TEXT_DOCUMENT_DEFINITION: Method = Method(Cow::Borrowed("textDocument/definition"));
    // A request to resolve project-wide references for the symbol denoted
    // by the given text document position. The request's parameter is of
    // type ReferenceParams the response is of type
    // Location[] or a Thenable that resolves to such.
    pub const TEXT_DOCUMENT_REFERENCES: Method = Method(Cow::Borrowed("textDocument/references"));
    // Request to resolve a DocumentHighlight for a given
    // text document position. The request's parameter is of type TextDocumentPosition
    // the request response is an array of type DocumentHighlight
    // or a Thenable that resolves to such.
    pub const TEXT_DOCUMENT_DOCUMENT_HIGHLIGHT: Method =
        Method(Cow::Borrowed("textDocument/documentHighlight"));
    // A request to list all symbols found in a given text document. The request's
    // parameter is of type TextDocumentIdentifier the
    // response is of type SymbolInformation[] or a Thenable
    // that resolves to such.
    pub const TEXT_DOCUMENT_DOCUMENT_SYMBOL: Method =
        Method(Cow::Borrowed("textDocument/documentSymbol"));
    // A request to provide commands for the given text document and range.
    pub const TEXT_DOCUMENT_CODE_ACTION: Method = Method(Cow::Borrowed("textDocument/codeAction"));
    // Request to resolve additional information for a given code action.The request's
    // parameter is of type CodeAction the response
    // is of type CodeAction or a Thenable that resolves to such.
    pub const CODE_ACTION_RESOLVE: Method = Method(Cow::Borrowed("codeAction/resolve"));
    // A request to list project-wide symbols matching the query string given
    // by the WorkspaceSymbolParams. The response is
    // of type SymbolInformation[] or a Thenable that
    // resolves to such.
    //
    // Since: 3.17.0 - support for WorkspaceSymbol in the returned data. Clients
    //  need to advertise support for WorkspaceSymbols via the client capability
    //  `workspace.symbol.resolveSupport`.
    pub const WORKSPACE_SYMBOL: Method = Method(Cow::Borrowed("workspace/symbol"));
    // A request to resolve the range inside the workspace
    // symbol's location.
    //
    // Since: 3.17.0
    pub const WORKSPACE_SYMBOL_RESOLVE: Method = Method(Cow::Borrowed("workspaceSymbol/resolve"));
    // A request to provide code lens for the given text document.
    pub const TEXT_DOCUMENT_CODE_LENS: Method = Method(Cow::Borrowed("textDocument/codeLens"));
    // A request to resolve a command for a given code lens.
    pub const CODE_LENS_RESOLVE: Method = Method(Cow::Borrowed("codeLens/resolve"));
    // A request to refresh all code actions
    //
    // Since: 3.16.0
    pub const WORKSPACE_CODE_LENS_REFRESH: Method =
        Method(Cow::Borrowed("workspace/codeLens/refresh"));
    // A request to provide document links
    pub const TEXT_DOCUMENT_DOCUMENT_LINK: Method =
        Method(Cow::Borrowed("textDocument/documentLink"));
    // Request to resolve additional information for a given document link. The request's
    // parameter is of type DocumentLink the response
    // is of type DocumentLink or a Thenable that resolves to such.
    pub const DOCUMENT_LINK_RESOLVE: Method = Method(Cow::Borrowed("documentLink/resolve"));
    // A request to format a whole document.
    pub const TEXT_DOCUMENT_FORMATTING: Method = Method(Cow::Borrowed("textDocument/formatting"));
    // A request to format a range in a document.
    pub const TEXT_DOCUMENT_RANGE_FORMATTING: Method =
        Method(Cow::Borrowed("textDocument/rangeFormatting"));
    // A request to format ranges in a document.
    //
    // Since: 3.18.0
    pub const TEXT_DOCUMENT_RANGES_FORMATTING: Method =
        Method(Cow::Borrowed("textDocument/rangesFormatting"));
    // A request to format a document on type.
    pub const TEXT_DOCUMENT_ON_TYPE_FORMATTING: Method =
        Method(Cow::Borrowed("textDocument/onTypeFormatting"));
    // A request to rename a symbol.
    pub const TEXT_DOCUMENT_RENAME: Method = Method(Cow::Borrowed("textDocument/rename"));
    // A request to test and perform the setup necessary for a rename.
    //
    // Since: 3.16 - support for default behavior
    pub const TEXT_DOCUMENT_PREPARE_RENAME: Method =
        Method(Cow::Borrowed("textDocument/prepareRename"));
    // A request send from the client to the server to execute a command. The request might return
    // a workspace edit which the client will apply to the workspace.
    pub const WORKSPACE_EXECUTE_COMMAND: Method = Method(Cow::Borrowed("workspace/executeCommand"));
    // A request sent from the server to the client to modified certain resources.
    pub const WORKSPACE_APPLY_EDIT: Method = Method(Cow::Borrowed("workspace/applyEdit"));
    // Triggers garbage collection in the language server.
    pub const CUSTOM_RUN_GC: Method = Method(Cow::Borrowed("custom/runGC"));
    // Saves a heap profile to the specified directory.
    pub const CUSTOM_SAVE_HEAP_PROFILE: Method = Method(Cow::Borrowed("custom/saveHeapProfile"));
    // Saves an allocation profile to the specified directory.
    pub const CUSTOM_SAVE_ALLOC_PROFILE: Method = Method(Cow::Borrowed("custom/saveAllocProfile"));
    // Starts CPU profiling, writing to the specified directory when stopped.
    pub const CUSTOM_START_CPU_PROFILE: Method = Method(Cow::Borrowed("custom/startCPUProfile"));
    // Stops CPU profiling and saves the profile.
    pub const CUSTOM_STOP_CPU_PROFILE: Method = Method(Cow::Borrowed("custom/stopCPUProfile"));
    // Custom request to initialize an API session.
    pub const CUSTOM_INITIALIZE_API_SESSION: Method =
        Method(Cow::Borrowed("custom/initializeAPISession"));
    // Returns project information (e.g. the tsconfig.json path) for a given text document.
    pub const CUSTOM_PROJECT_INFO: Method = Method(Cow::Borrowed("custom/projectInfo"));
    // Replaces extension content mapper contributions and discovers configured mappers for matching open documents.
    pub const CUSTOM_SET_CONTENT_MAPPER_CONTRIBUTIONS: Method =
        Method(Cow::Borrowed("custom/setContentMapperContributions"));
    // Request to get source definitions for a position.
    pub const CUSTOM_TEXT_DOCUMENT_SOURCE_DEFINITION: Method =
        Method(Cow::Borrowed("custom/textDocument/sourceDefinition"));
    // Request to get document highlights across multiple files.
    pub const CUSTOM_TEXT_DOCUMENT_MULTI_DOCUMENT_HIGHLIGHT: Method =
        Method(Cow::Borrowed("custom/textDocument/multiDocumentHighlight"));
    // Request for auto-insert when a trigger character is typed (VS-specific).
    pub const TEXT_DOCUMENT_VS_ON_AUTO_INSERT: Method =
        Method(Cow::Borrowed("textDocument/_vs_onAutoInsert"));
    // VS-specific request for Find All References with grouped reference items.
    pub const TEXT_DOCUMENT_VS_REFERENCES: Method =
        Method(Cow::Borrowed("textDocument/_vs_references"));
    // The `workspace/didChangeWorkspaceFolders` notification is sent from the client to the server when the workspace
    // folder configuration changes.
    pub const WORKSPACE_DID_CHANGE_WORKSPACE_FOLDERS: Method =
        Method(Cow::Borrowed("workspace/didChangeWorkspaceFolders"));
    // The `window/workDoneProgress/cancel` notification is sent from the client to the server to cancel a progress
    // initiated on the server side.
    pub const WINDOW_WORK_DONE_PROGRESS_CANCEL: Method =
        Method(Cow::Borrowed("window/workDoneProgress/cancel"));
    // The did create files notification is sent from the client to the server when
    // files were created from within the client.
    //
    // Since: 3.16.0
    pub const WORKSPACE_DID_CREATE_FILES: Method =
        Method(Cow::Borrowed("workspace/didCreateFiles"));
    // The did rename files notification is sent from the client to the server when
    // files were renamed from within the client.
    //
    // Since: 3.16.0
    pub const WORKSPACE_DID_RENAME_FILES: Method =
        Method(Cow::Borrowed("workspace/didRenameFiles"));
    // The will delete files request is sent from the client to the server before files are actually
    // deleted as long as the deletion is triggered from within the client.
    //
    // Since: 3.16.0
    pub const WORKSPACE_DID_DELETE_FILES: Method =
        Method(Cow::Borrowed("workspace/didDeleteFiles"));
    // The initialized notification is sent from the client to the
    // server after the client is fully initialized and the server
    // is allowed to send requests from the server to the client.
    pub const INITIALIZED: Method = Method(Cow::Borrowed("initialized"));
    // The exit event is sent from the client to the server to
    // ask the server to exit its process.
    pub const EXIT: Method = Method(Cow::Borrowed("exit"));
    // The configuration change notification is sent from the client to the server
    // when the client's configuration has changed. The notification contains
    // the changed configuration as defined by the language client.
    pub const WORKSPACE_DID_CHANGE_CONFIGURATION: Method =
        Method(Cow::Borrowed("workspace/didChangeConfiguration"));
    // The show message notification is sent from a server to a client to ask
    // the client to display a particular message in the user interface.
    pub const WINDOW_SHOW_MESSAGE: Method = Method(Cow::Borrowed("window/showMessage"));
    // The log message notification is sent from the server to the client to ask
    // the client to log a particular message.
    pub const WINDOW_LOG_MESSAGE: Method = Method(Cow::Borrowed("window/logMessage"));
    // The telemetry event notification is sent from the server to the client to ask
    // the client to log telemetry data.
    pub const TELEMETRY_EVENT: Method = Method(Cow::Borrowed("telemetry/event"));
    // The document open notification is sent from the client to the server to signal
    // newly opened text documents. The document's truth is now managed by the client
    // and the server must not try to read the document's truth using the document's
    // uri. Open in this sense means it is managed by the client. It doesn't necessarily
    // mean that its content is presented in an editor. An open notification must not
    // be sent more than once without a corresponding close notification send before.
    // This means open and close notification must be balanced and the max open count
    // is one.
    pub const TEXT_DOCUMENT_DID_OPEN: Method = Method(Cow::Borrowed("textDocument/didOpen"));
    // The document change notification is sent from the client to the server to signal
    // changes to a text document.
    pub const TEXT_DOCUMENT_DID_CHANGE: Method = Method(Cow::Borrowed("textDocument/didChange"));
    // The document close notification is sent from the client to the server when
    // the document got closed in the client. The document's truth now exists where
    // the document's uri points to (e.g. if the document's uri is a file uri the
    // truth now exists on disk). As with the open notification the close notification
    // is about managing the document's content. Receiving a close notification
    // doesn't mean that the document was open in an editor before. A close
    // notification requires a previous open notification to be sent.
    pub const TEXT_DOCUMENT_DID_CLOSE: Method = Method(Cow::Borrowed("textDocument/didClose"));
    // The document save notification is sent from the client to the server when
    // the document got saved in the client.
    pub const TEXT_DOCUMENT_DID_SAVE: Method = Method(Cow::Borrowed("textDocument/didSave"));
    // A document will save notification is sent from the client to the server before
    // the document is actually saved.
    pub const TEXT_DOCUMENT_WILL_SAVE: Method = Method(Cow::Borrowed("textDocument/willSave"));
    // The watched files notification is sent from the client to the server when
    // the client detects changes to file watched by the language client.
    pub const WORKSPACE_DID_CHANGE_WATCHED_FILES: Method =
        Method(Cow::Borrowed("workspace/didChangeWatchedFiles"));
    // Diagnostics notification are sent from the server to the client to signal
    // results of validation runs.
    pub const TEXT_DOCUMENT_PUBLISH_DIAGNOSTICS: Method =
        Method(Cow::Borrowed("textDocument/publishDiagnostics"));
    pub const SET_TRACE: Method = Method(Cow::Borrowed("$/setTrace"));
    pub const LOG_TRACE: Method = Method(Cow::Borrowed("$/logTrace"));
    pub const CANCEL_REQUEST: Method = Method(Cow::Borrowed("$/cancelRequest"));
    pub const PROGRESS: Method = Method(Cow::Borrowed("$/progress"));
    // Notification to set the server's log verbosity level based on the output channel's log level.
    pub const CUSTOM_SET_LOG_VERBOSITY: Method = Method(Cow::Borrowed("custom/setLogVerbosity"));
    // Registration-only method for textDocument/semanticTokens.
    pub const TEXT_DOCUMENT_SEMANTIC_TOKENS: Method =
        Method(Cow::Borrowed("textDocument/semanticTokens"));
}

// Request response types

// Response type for `textDocument/implementation`
pub type ImplementationResponse = LocationOrLocationsOrDefinitionLinksOrNull;

// Type mapping info for `textDocument/implementation`
pub const TEXT_DOCUMENT_IMPLEMENTATION_INFO: RequestInfo<
    ImplementationParams,
    ImplementationResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_IMPLEMENTATION);

// Response type for `textDocument/typeDefinition`
pub type TypeDefinitionResponse = LocationOrLocationsOrDefinitionLinksOrNull;

// Type mapping info for `textDocument/typeDefinition`
pub const TEXT_DOCUMENT_TYPE_DEFINITION_INFO: RequestInfo<
    TypeDefinitionParams,
    TypeDefinitionResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_TYPE_DEFINITION);

// Response type for `workspace/workspaceFolders`
pub type WorkspaceFoldersResponse = WorkspaceFoldersOrNull;

// Type mapping info for `workspace/workspaceFolders`
pub const WORKSPACE_WORKSPACE_FOLDERS_INFO: RequestInfo<NoParams, WorkspaceFoldersResponse> =
    RequestInfo::new(Method::WORKSPACE_WORKSPACE_FOLDERS);

// Response type for `workspace/configuration`
pub type ConfigurationResponse = Vec<LspAny>;

// Type mapping info for `workspace/configuration`
pub const WORKSPACE_CONFIGURATION_INFO: RequestInfo<ConfigurationParams, ConfigurationResponse> =
    RequestInfo::new(Method::WORKSPACE_CONFIGURATION);

// Response type for `textDocument/documentColor`
pub type DocumentColorResponse = Vec<ColorInformation>;

// Type mapping info for `textDocument/documentColor`
pub const TEXT_DOCUMENT_DOCUMENT_COLOR_INFO: RequestInfo<
    DocumentColorParams,
    DocumentColorResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_DOCUMENT_COLOR);

// Response type for `textDocument/colorPresentation`
pub type ColorPresentationResponse = Vec<ColorPresentation>;

// Type mapping info for `textDocument/colorPresentation`
pub const TEXT_DOCUMENT_COLOR_PRESENTATION_INFO: RequestInfo<
    ColorPresentationParams,
    ColorPresentationResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_COLOR_PRESENTATION);

// Response type for `textDocument/foldingRange`
pub type FoldingRangeResponse = FoldingRangesOrNull;

// Type mapping info for `textDocument/foldingRange`
pub const TEXT_DOCUMENT_FOLDING_RANGE_INFO: RequestInfo<FoldingRangeParams, FoldingRangeResponse> =
    RequestInfo::new(Method::TEXT_DOCUMENT_FOLDING_RANGE);

// Response type for `workspace/foldingRange/refresh`
pub type FoldingRangeRefreshResponse = Null;

// Type mapping info for `workspace/foldingRange/refresh`
pub const WORKSPACE_FOLDING_RANGE_REFRESH_INFO: RequestInfo<NoParams, FoldingRangeRefreshResponse> =
    RequestInfo::new(Method::WORKSPACE_FOLDING_RANGE_REFRESH);

// Response type for `textDocument/declaration`
pub type DeclarationResponse = LocationOrLocationsOrDeclarationLinksOrNull;

// Type mapping info for `textDocument/declaration`
pub const TEXT_DOCUMENT_DECLARATION_INFO: RequestInfo<DeclarationParams, DeclarationResponse> =
    RequestInfo::new(Method::TEXT_DOCUMENT_DECLARATION);

// Response type for `textDocument/selectionRange`
pub type SelectionRangeResponse = SelectionRangesOrNull;

// Type mapping info for `textDocument/selectionRange`
pub const TEXT_DOCUMENT_SELECTION_RANGE_INFO: RequestInfo<
    SelectionRangeParams,
    SelectionRangeResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_SELECTION_RANGE);

// Response type for `window/workDoneProgress/create`
pub type WorkDoneProgressCreateResponse = Null;

// Type mapping info for `window/workDoneProgress/create`
pub const WINDOW_WORK_DONE_PROGRESS_CREATE_INFO: RequestInfo<
    WorkDoneProgressCreateParams,
    WorkDoneProgressCreateResponse,
> = RequestInfo::new(Method::WINDOW_WORK_DONE_PROGRESS_CREATE);

// Response type for `textDocument/prepareCallHierarchy`
pub type CallHierarchyPrepareResponse = CallHierarchyItemsOrNull;

// Type mapping info for `textDocument/prepareCallHierarchy`
pub const TEXT_DOCUMENT_PREPARE_CALL_HIERARCHY_INFO: RequestInfo<
    CallHierarchyPrepareParams,
    CallHierarchyPrepareResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_PREPARE_CALL_HIERARCHY);

// Response type for `callHierarchy/incomingCalls`
pub type CallHierarchyIncomingCallsResponse = CallHierarchyIncomingCallsOrNull;

// Type mapping info for `callHierarchy/incomingCalls`
pub const CALL_HIERARCHY_INCOMING_CALLS_INFO: RequestInfo<
    CallHierarchyIncomingCallsParams,
    CallHierarchyIncomingCallsResponse,
> = RequestInfo::new(Method::CALL_HIERARCHY_INCOMING_CALLS);

// Response type for `callHierarchy/outgoingCalls`
pub type CallHierarchyOutgoingCallsResponse = CallHierarchyOutgoingCallsOrNull;

// Type mapping info for `callHierarchy/outgoingCalls`
pub const CALL_HIERARCHY_OUTGOING_CALLS_INFO: RequestInfo<
    CallHierarchyOutgoingCallsParams,
    CallHierarchyOutgoingCallsResponse,
> = RequestInfo::new(Method::CALL_HIERARCHY_OUTGOING_CALLS);

// Response type for `textDocument/semanticTokens/full`
pub type SemanticTokensResponse = SemanticTokensOrNull;

// Type mapping info for `textDocument/semanticTokens/full`
pub const TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL_INFO: RequestInfo<
    SemanticTokensParams,
    SemanticTokensResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL);

// Response type for `textDocument/semanticTokens/full/delta`
pub type SemanticTokensDeltaResponse = SemanticTokensOrSemanticTokensDeltaOrNull;

// Type mapping info for `textDocument/semanticTokens/full/delta`
pub const TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL_DELTA_INFO: RequestInfo<
    SemanticTokensDeltaParams,
    SemanticTokensDeltaResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_SEMANTIC_TOKENS_FULL_DELTA);

// Response type for `textDocument/semanticTokens/range`
pub type SemanticTokensRangeResponse = SemanticTokensOrNull;

// Type mapping info for `textDocument/semanticTokens/range`
pub const TEXT_DOCUMENT_SEMANTIC_TOKENS_RANGE_INFO: RequestInfo<
    SemanticTokensRangeParams,
    SemanticTokensRangeResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_SEMANTIC_TOKENS_RANGE);

// Response type for `workspace/semanticTokens/refresh`
pub type SemanticTokensRefreshResponse = Null;

// Type mapping info for `workspace/semanticTokens/refresh`
pub const WORKSPACE_SEMANTIC_TOKENS_REFRESH_INFO: RequestInfo<
    NoParams,
    SemanticTokensRefreshResponse,
> = RequestInfo::new(Method::WORKSPACE_SEMANTIC_TOKENS_REFRESH);

// Response type for `window/showDocument`
pub type ShowDocumentResponse = Option<ShowDocumentResult>;

// Type mapping info for `window/showDocument`
pub const WINDOW_SHOW_DOCUMENT_INFO: RequestInfo<ShowDocumentParams, ShowDocumentResponse> =
    RequestInfo::new(Method::WINDOW_SHOW_DOCUMENT);

// Response type for `textDocument/linkedEditingRange`
pub type LinkedEditingRangeResponse = LinkedEditingRangesOrNull;

// Type mapping info for `textDocument/linkedEditingRange`
pub const TEXT_DOCUMENT_LINKED_EDITING_RANGE_INFO: RequestInfo<
    LinkedEditingRangeParams,
    LinkedEditingRangeResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_LINKED_EDITING_RANGE);

// Response type for `workspace/willCreateFiles`
pub type WillCreateFilesResponse = WorkspaceEditOrNull;

// Type mapping info for `workspace/willCreateFiles`
pub const WORKSPACE_WILL_CREATE_FILES_INFO: RequestInfo<
    CreateFilesParams,
    WillCreateFilesResponse,
> = RequestInfo::new(Method::WORKSPACE_WILL_CREATE_FILES);

// Response type for `workspace/willRenameFiles`
pub type WillRenameFilesResponse = WorkspaceEditOrNull;

// Type mapping info for `workspace/willRenameFiles`
pub const WORKSPACE_WILL_RENAME_FILES_INFO: RequestInfo<
    RenameFilesParams,
    WillRenameFilesResponse,
> = RequestInfo::new(Method::WORKSPACE_WILL_RENAME_FILES);

// Response type for `workspace/willDeleteFiles`
pub type WillDeleteFilesResponse = WorkspaceEditOrNull;

// Type mapping info for `workspace/willDeleteFiles`
pub const WORKSPACE_WILL_DELETE_FILES_INFO: RequestInfo<
    DeleteFilesParams,
    WillDeleteFilesResponse,
> = RequestInfo::new(Method::WORKSPACE_WILL_DELETE_FILES);

// Response type for `textDocument/moniker`
pub type MonikerResponse = MonikersOrNull;

// Type mapping info for `textDocument/moniker`
pub const TEXT_DOCUMENT_MONIKER_INFO: RequestInfo<MonikerParams, MonikerResponse> =
    RequestInfo::new(Method::TEXT_DOCUMENT_MONIKER);

// Response type for `textDocument/prepareTypeHierarchy`
pub type TypeHierarchyPrepareResponse = TypeHierarchyItemsOrNull;

// Type mapping info for `textDocument/prepareTypeHierarchy`
pub const TEXT_DOCUMENT_PREPARE_TYPE_HIERARCHY_INFO: RequestInfo<
    TypeHierarchyPrepareParams,
    TypeHierarchyPrepareResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_PREPARE_TYPE_HIERARCHY);

// Response type for `typeHierarchy/supertypes`
pub type TypeHierarchySupertypesResponse = TypeHierarchyItemsOrNull;

// Type mapping info for `typeHierarchy/supertypes`
pub const TYPE_HIERARCHY_SUPERTYPES_INFO: RequestInfo<
    TypeHierarchySupertypesParams,
    TypeHierarchySupertypesResponse,
> = RequestInfo::new(Method::TYPE_HIERARCHY_SUPERTYPES);

// Response type for `typeHierarchy/subtypes`
pub type TypeHierarchySubtypesResponse = TypeHierarchyItemsOrNull;

// Type mapping info for `typeHierarchy/subtypes`
pub const TYPE_HIERARCHY_SUBTYPES_INFO: RequestInfo<
    TypeHierarchySubtypesParams,
    TypeHierarchySubtypesResponse,
> = RequestInfo::new(Method::TYPE_HIERARCHY_SUBTYPES);

// Response type for `textDocument/inlineValue`
pub type InlineValueResponse = InlineValuesOrNull;

// Type mapping info for `textDocument/inlineValue`
pub const TEXT_DOCUMENT_INLINE_VALUE_INFO: RequestInfo<InlineValueParams, InlineValueResponse> =
    RequestInfo::new(Method::TEXT_DOCUMENT_INLINE_VALUE);

// Response type for `workspace/inlineValue/refresh`
pub type InlineValueRefreshResponse = Null;

// Type mapping info for `workspace/inlineValue/refresh`
pub const WORKSPACE_INLINE_VALUE_REFRESH_INFO: RequestInfo<NoParams, InlineValueRefreshResponse> =
    RequestInfo::new(Method::WORKSPACE_INLINE_VALUE_REFRESH);

// Response type for `textDocument/inlayHint`
pub type InlayHintResponse = InlayHintsOrNull;

// Type mapping info for `textDocument/inlayHint`
pub const TEXT_DOCUMENT_INLAY_HINT_INFO: RequestInfo<InlayHintParams, InlayHintResponse> =
    RequestInfo::new(Method::TEXT_DOCUMENT_INLAY_HINT);

// Response type for `inlayHint/resolve`
pub type InlayHintResolveResponse = Option<InlayHint>;

// Type mapping info for `inlayHint/resolve`
pub const INLAY_HINT_RESOLVE_INFO: RequestInfo<InlayHint, InlayHintResolveResponse> =
    RequestInfo::new(Method::INLAY_HINT_RESOLVE);

// Response type for `workspace/inlayHint/refresh`
pub type InlayHintRefreshResponse = Null;

// Type mapping info for `workspace/inlayHint/refresh`
pub const WORKSPACE_INLAY_HINT_REFRESH_INFO: RequestInfo<NoParams, InlayHintRefreshResponse> =
    RequestInfo::new(Method::WORKSPACE_INLAY_HINT_REFRESH);

// Response type for `textDocument/diagnostic`
pub type DocumentDiagnosticResponse =
    RelatedFullDocumentDiagnosticReportOrUnchangedDocumentDiagnosticReport;

// Type mapping info for `textDocument/diagnostic`
pub const TEXT_DOCUMENT_DIAGNOSTIC_INFO: RequestInfo<
    DocumentDiagnosticParams,
    DocumentDiagnosticResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_DIAGNOSTIC);

// Response type for `workspace/diagnostic`
pub type WorkspaceDiagnosticResponse = Option<WorkspaceDiagnosticReport>;

// Type mapping info for `workspace/diagnostic`
pub const WORKSPACE_DIAGNOSTIC_INFO: RequestInfo<
    WorkspaceDiagnosticParams,
    WorkspaceDiagnosticResponse,
> = RequestInfo::new(Method::WORKSPACE_DIAGNOSTIC);

// Response type for `workspace/diagnostic/refresh`
pub type DiagnosticRefreshResponse = Null;

// Type mapping info for `workspace/diagnostic/refresh`
pub const WORKSPACE_DIAGNOSTIC_REFRESH_INFO: RequestInfo<NoParams, DiagnosticRefreshResponse> =
    RequestInfo::new(Method::WORKSPACE_DIAGNOSTIC_REFRESH);

// Response type for `textDocument/inlineCompletion`
pub type InlineCompletionResponse = InlineCompletionListOrItemsOrNull;

// Type mapping info for `textDocument/inlineCompletion`
pub const TEXT_DOCUMENT_INLINE_COMPLETION_INFO: RequestInfo<
    InlineCompletionParams,
    InlineCompletionResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_INLINE_COMPLETION);

// Response type for `workspace/textDocumentContent`
pub type TextDocumentContentResponse = Option<TextDocumentContentResult>;

// Type mapping info for `workspace/textDocumentContent`
pub const WORKSPACE_TEXT_DOCUMENT_CONTENT_INFO: RequestInfo<
    TextDocumentContentParams,
    TextDocumentContentResponse,
> = RequestInfo::new(Method::WORKSPACE_TEXT_DOCUMENT_CONTENT);

// Response type for `workspace/textDocumentContent/refresh`
pub type TextDocumentContentRefreshResponse = Null;

// Type mapping info for `workspace/textDocumentContent/refresh`
pub const WORKSPACE_TEXT_DOCUMENT_CONTENT_REFRESH_INFO: RequestInfo<
    TextDocumentContentRefreshParams,
    TextDocumentContentRefreshResponse,
> = RequestInfo::new(Method::WORKSPACE_TEXT_DOCUMENT_CONTENT_REFRESH);

// Response type for `client/registerCapability`
pub type RegistrationResponse = Null;

// Type mapping info for `client/registerCapability`
pub const CLIENT_REGISTER_CAPABILITY_INFO: RequestInfo<RegistrationParams, RegistrationResponse> =
    RequestInfo::new(Method::CLIENT_REGISTER_CAPABILITY);

// Response type for `client/unregisterCapability`
pub type UnregistrationResponse = Null;

// Type mapping info for `client/unregisterCapability`
pub const CLIENT_UNREGISTER_CAPABILITY_INFO: RequestInfo<
    UnregistrationParams,
    UnregistrationResponse,
> = RequestInfo::new(Method::CLIENT_UNREGISTER_CAPABILITY);

// Response type for `initialize`
pub type InitializeResponse = Option<InitializeResult>;

// Type mapping info for `initialize`
pub const INITIALIZE_INFO: RequestInfo<InitializeParams, InitializeResponse> =
    RequestInfo::new(Method::INITIALIZE);

// Response type for `shutdown`
pub type ShutdownResponse = Null;

// Type mapping info for `shutdown`
pub const SHUTDOWN_INFO: RequestInfo<NoParams, ShutdownResponse> =
    RequestInfo::new(Method::SHUTDOWN);

// Response type for `window/showMessageRequest`
pub type ShowMessageResponse = MessageActionItemOrNull;

// Type mapping info for `window/showMessageRequest`
pub const WINDOW_SHOW_MESSAGE_REQUEST_INFO: RequestInfo<
    ShowMessageRequestParams,
    ShowMessageResponse,
> = RequestInfo::new(Method::WINDOW_SHOW_MESSAGE_REQUEST);

// Response type for `textDocument/willSaveWaitUntil`
pub type WillSaveTextDocumentWaitUntilResponse = TextEditsOrNull;

// Type mapping info for `textDocument/willSaveWaitUntil`
pub const TEXT_DOCUMENT_WILL_SAVE_WAIT_UNTIL_INFO: RequestInfo<
    WillSaveTextDocumentParams,
    WillSaveTextDocumentWaitUntilResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_WILL_SAVE_WAIT_UNTIL);

// Response type for `textDocument/completion`
pub type CompletionResponse = CompletionItemsOrListOrNull;

// Type mapping info for `textDocument/completion`
pub const TEXT_DOCUMENT_COMPLETION_INFO: RequestInfo<CompletionParams, CompletionResponse> =
    RequestInfo::new(Method::TEXT_DOCUMENT_COMPLETION);

// Response type for `completionItem/resolve`
pub type CompletionResolveResponse = Option<CompletionItem>;

// Type mapping info for `completionItem/resolve`
pub const COMPLETION_ITEM_RESOLVE_INFO: RequestInfo<CompletionItem, CompletionResolveResponse> =
    RequestInfo::new(Method::COMPLETION_ITEM_RESOLVE);

// Response type for `textDocument/hover`
pub type HoverResponse = HoverOrNull;

// Type mapping info for `textDocument/hover`
pub const TEXT_DOCUMENT_HOVER_INFO: RequestInfo<HoverParams, HoverResponse> =
    RequestInfo::new(Method::TEXT_DOCUMENT_HOVER);

// Response type for `textDocument/signatureHelp`
pub type SignatureHelpResponse = SignatureHelpOrNull;

// Type mapping info for `textDocument/signatureHelp`
pub const TEXT_DOCUMENT_SIGNATURE_HELP_INFO: RequestInfo<
    SignatureHelpParams,
    SignatureHelpResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_SIGNATURE_HELP);

// Response type for `textDocument/definition`
pub type DefinitionResponse = LocationOrLocationsOrDefinitionLinksOrNull;

// Type mapping info for `textDocument/definition`
pub const TEXT_DOCUMENT_DEFINITION_INFO: RequestInfo<DefinitionParams, DefinitionResponse> =
    RequestInfo::new(Method::TEXT_DOCUMENT_DEFINITION);

// Response type for `textDocument/references`
pub type ReferencesResponse = LocationsOrNull;

// Type mapping info for `textDocument/references`
pub const TEXT_DOCUMENT_REFERENCES_INFO: RequestInfo<ReferenceParams, ReferencesResponse> =
    RequestInfo::new(Method::TEXT_DOCUMENT_REFERENCES);

// Response type for `textDocument/documentHighlight`
pub type DocumentHighlightResponse = DocumentHighlightsOrNull;

// Type mapping info for `textDocument/documentHighlight`
pub const TEXT_DOCUMENT_DOCUMENT_HIGHLIGHT_INFO: RequestInfo<
    DocumentHighlightParams,
    DocumentHighlightResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_DOCUMENT_HIGHLIGHT);

// Response type for `textDocument/documentSymbol`
pub type DocumentSymbolResponse = SymbolInformationsOrDocumentSymbolsOrNull;

// Type mapping info for `textDocument/documentSymbol`
pub const TEXT_DOCUMENT_DOCUMENT_SYMBOL_INFO: RequestInfo<
    DocumentSymbolParams,
    DocumentSymbolResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_DOCUMENT_SYMBOL);

// Response type for `textDocument/codeAction`
pub type CodeActionResponse = CommandOrCodeActionArrayOrNull;

// Type mapping info for `textDocument/codeAction`
pub const TEXT_DOCUMENT_CODE_ACTION_INFO: RequestInfo<CodeActionParams, CodeActionResponse> =
    RequestInfo::new(Method::TEXT_DOCUMENT_CODE_ACTION);

// Response type for `codeAction/resolve`
pub type CodeActionResolveResponse = Option<CodeAction>;

// Type mapping info for `codeAction/resolve`
pub const CODE_ACTION_RESOLVE_INFO: RequestInfo<CodeAction, CodeActionResolveResponse> =
    RequestInfo::new(Method::CODE_ACTION_RESOLVE);

// Response type for `workspace/symbol`
pub type WorkspaceSymbolResponse = SymbolInformationsOrWorkspaceSymbolsOrNull;

// Type mapping info for `workspace/symbol`
pub const WORKSPACE_SYMBOL_INFO: RequestInfo<WorkspaceSymbolParams, WorkspaceSymbolResponse> =
    RequestInfo::new(Method::WORKSPACE_SYMBOL);

// Response type for `workspaceSymbol/resolve`
pub type WorkspaceSymbolResolveResponse = Option<WorkspaceSymbol>;

// Type mapping info for `workspaceSymbol/resolve`
pub const WORKSPACE_SYMBOL_RESOLVE_INFO: RequestInfo<
    WorkspaceSymbol,
    WorkspaceSymbolResolveResponse,
> = RequestInfo::new(Method::WORKSPACE_SYMBOL_RESOLVE);

// Response type for `textDocument/codeLens`
pub type CodeLensResponse = CodeLensesOrNull;

// Type mapping info for `textDocument/codeLens`
pub const TEXT_DOCUMENT_CODE_LENS_INFO: RequestInfo<CodeLensParams, CodeLensResponse> =
    RequestInfo::new(Method::TEXT_DOCUMENT_CODE_LENS);

// Response type for `codeLens/resolve`
pub type CodeLensResolveResponse = Option<CodeLens>;

// Type mapping info for `codeLens/resolve`
pub const CODE_LENS_RESOLVE_INFO: RequestInfo<CodeLens, CodeLensResolveResponse> =
    RequestInfo::new(Method::CODE_LENS_RESOLVE);

// Response type for `workspace/codeLens/refresh`
pub type CodeLensRefreshResponse = Null;

// Type mapping info for `workspace/codeLens/refresh`
pub const WORKSPACE_CODE_LENS_REFRESH_INFO: RequestInfo<NoParams, CodeLensRefreshResponse> =
    RequestInfo::new(Method::WORKSPACE_CODE_LENS_REFRESH);

// Response type for `textDocument/documentLink`
pub type DocumentLinkResponse = DocumentLinksOrNull;

// Type mapping info for `textDocument/documentLink`
pub const TEXT_DOCUMENT_DOCUMENT_LINK_INFO: RequestInfo<DocumentLinkParams, DocumentLinkResponse> =
    RequestInfo::new(Method::TEXT_DOCUMENT_DOCUMENT_LINK);

// Response type for `documentLink/resolve`
pub type DocumentLinkResolveResponse = Option<DocumentLink>;

// Type mapping info for `documentLink/resolve`
pub const DOCUMENT_LINK_RESOLVE_INFO: RequestInfo<DocumentLink, DocumentLinkResolveResponse> =
    RequestInfo::new(Method::DOCUMENT_LINK_RESOLVE);

// Response type for `textDocument/formatting`
pub type DocumentFormattingResponse = TextEditsOrNull;

// Type mapping info for `textDocument/formatting`
pub const TEXT_DOCUMENT_FORMATTING_INFO: RequestInfo<
    DocumentFormattingParams,
    DocumentFormattingResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_FORMATTING);

// Response type for `textDocument/rangeFormatting`
pub type DocumentRangeFormattingResponse = TextEditsOrNull;

// Type mapping info for `textDocument/rangeFormatting`
pub const TEXT_DOCUMENT_RANGE_FORMATTING_INFO: RequestInfo<
    DocumentRangeFormattingParams,
    DocumentRangeFormattingResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_RANGE_FORMATTING);

// Response type for `textDocument/rangesFormatting`
pub type DocumentRangesFormattingResponse = TextEditsOrNull;

// Type mapping info for `textDocument/rangesFormatting`
pub const TEXT_DOCUMENT_RANGES_FORMATTING_INFO: RequestInfo<
    DocumentRangesFormattingParams,
    DocumentRangesFormattingResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_RANGES_FORMATTING);

// Response type for `textDocument/onTypeFormatting`
pub type DocumentOnTypeFormattingResponse = TextEditsOrNull;

// Type mapping info for `textDocument/onTypeFormatting`
pub const TEXT_DOCUMENT_ON_TYPE_FORMATTING_INFO: RequestInfo<
    DocumentOnTypeFormattingParams,
    DocumentOnTypeFormattingResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_ON_TYPE_FORMATTING);

// Response type for `textDocument/rename`
pub type RenameResponse = WorkspaceEditOrNull;

// Type mapping info for `textDocument/rename`
pub const TEXT_DOCUMENT_RENAME_INFO: RequestInfo<RenameParams, RenameResponse> =
    RequestInfo::new(Method::TEXT_DOCUMENT_RENAME);

// Response type for `textDocument/prepareRename`
pub type PrepareRenameResponse =
    RangeOrPrepareRenamePlaceholderOrPrepareRenameDefaultBehaviorOrNull;

// Type mapping info for `textDocument/prepareRename`
pub const TEXT_DOCUMENT_PREPARE_RENAME_INFO: RequestInfo<
    PrepareRenameParams,
    PrepareRenameResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_PREPARE_RENAME);

// Response type for `workspace/executeCommand`
pub type ExecuteCommandResponse = LSPAnyOrNull;

// Type mapping info for `workspace/executeCommand`
pub const WORKSPACE_EXECUTE_COMMAND_INFO: RequestInfo<
    ExecuteCommandParams,
    ExecuteCommandResponse,
> = RequestInfo::new(Method::WORKSPACE_EXECUTE_COMMAND);

// Response type for `workspace/applyEdit`
pub type ApplyWorkspaceEditResponse = Option<ApplyWorkspaceEditResult>;

// Type mapping info for `workspace/applyEdit`
pub const WORKSPACE_APPLY_EDIT_INFO: RequestInfo<
    ApplyWorkspaceEditParams,
    ApplyWorkspaceEditResponse,
> = RequestInfo::new(Method::WORKSPACE_APPLY_EDIT);

// Response type for `custom/runGC`
pub type RunGCResponse = Null;

// Type mapping info for `custom/runGC`
pub const CUSTOM_RUN_GC_INFO: RequestInfo<NoParams, RunGCResponse> =
    RequestInfo::new(Method::CUSTOM_RUN_GC);

// Response type for `custom/saveHeapProfile`
pub type SaveHeapProfileResponse = Option<ProfileResult>;

// Type mapping info for `custom/saveHeapProfile`
pub const CUSTOM_SAVE_HEAP_PROFILE_INFO: RequestInfo<ProfileParams, SaveHeapProfileResponse> =
    RequestInfo::new(Method::CUSTOM_SAVE_HEAP_PROFILE);

// Response type for `custom/saveAllocProfile`
pub type SaveAllocProfileResponse = Option<ProfileResult>;

// Type mapping info for `custom/saveAllocProfile`
pub const CUSTOM_SAVE_ALLOC_PROFILE_INFO: RequestInfo<ProfileParams, SaveAllocProfileResponse> =
    RequestInfo::new(Method::CUSTOM_SAVE_ALLOC_PROFILE);

// Response type for `custom/startCPUProfile`
pub type StartCPUProfileResponse = Null;

// Type mapping info for `custom/startCPUProfile`
pub const CUSTOM_START_CPU_PROFILE_INFO: RequestInfo<ProfileParams, StartCPUProfileResponse> =
    RequestInfo::new(Method::CUSTOM_START_CPU_PROFILE);

// Response type for `custom/stopCPUProfile`
pub type StopCPUProfileResponse = Option<ProfileResult>;

// Type mapping info for `custom/stopCPUProfile`
pub const CUSTOM_STOP_CPU_PROFILE_INFO: RequestInfo<NoParams, StopCPUProfileResponse> =
    RequestInfo::new(Method::CUSTOM_STOP_CPU_PROFILE);

// Response type for `custom/initializeAPISession`
pub type CustomInitializeAPISessionResponse = Option<InitializeAPISessionResult>;

// Type mapping info for `custom/initializeAPISession`
pub const CUSTOM_INITIALIZE_API_SESSION_INFO: RequestInfo<
    InitializeAPISessionParams,
    CustomInitializeAPISessionResponse,
> = RequestInfo::new(Method::CUSTOM_INITIALIZE_API_SESSION);

// Response type for `custom/projectInfo`
pub type CustomProjectInfoResponse = Option<ProjectInfoResult>;

// Type mapping info for `custom/projectInfo`
pub const CUSTOM_PROJECT_INFO_INFO: RequestInfo<ProjectInfoParams, CustomProjectInfoResponse> =
    RequestInfo::new(Method::CUSTOM_PROJECT_INFO);

// Response type for `custom/setContentMapperContributions`
pub type CustomSetContentMapperContributionsResponse = Null;

// Type mapping info for `custom/setContentMapperContributions`
pub const CUSTOM_SET_CONTENT_MAPPER_CONTRIBUTIONS_INFO: RequestInfo<
    SetContentMapperContributionsParams,
    CustomSetContentMapperContributionsResponse,
> = RequestInfo::new(Method::CUSTOM_SET_CONTENT_MAPPER_CONTRIBUTIONS);

// Response type for `custom/textDocument/sourceDefinition`
pub type CustomTextDocumentSourceDefinitionResponse =
    Option<LocationOrLocationsOrDefinitionLinksOrNull>;

// Type mapping info for `custom/textDocument/sourceDefinition`
pub const CUSTOM_TEXT_DOCUMENT_SOURCE_DEFINITION_INFO: RequestInfo<
    TextDocumentPositionParams,
    CustomTextDocumentSourceDefinitionResponse,
> = RequestInfo::new(Method::CUSTOM_TEXT_DOCUMENT_SOURCE_DEFINITION);

// Response type for `custom/textDocument/multiDocumentHighlight`
pub type CustomMultiDocumentHighlightResponse = MultiDocumentHighlightsOrNull;

// Type mapping info for `custom/textDocument/multiDocumentHighlight`
pub const CUSTOM_TEXT_DOCUMENT_MULTI_DOCUMENT_HIGHLIGHT_INFO: RequestInfo<
    MultiDocumentHighlightParams,
    CustomMultiDocumentHighlightResponse,
> = RequestInfo::new(Method::CUSTOM_TEXT_DOCUMENT_MULTI_DOCUMENT_HIGHLIGHT);

// Response type for `textDocument/_vs_onAutoInsert`
pub type VSOnAutoInsertResponse = VSOnAutoInsertResponseItemOrNull;

// Type mapping info for `textDocument/_vs_onAutoInsert`
pub const TEXT_DOCUMENT_VS_ON_AUTO_INSERT_INFO: RequestInfo<
    VSOnAutoInsertParams,
    VSOnAutoInsertResponse,
> = RequestInfo::new(Method::TEXT_DOCUMENT_VS_ON_AUTO_INSERT);

// Response type for `textDocument/_vs_references`
pub type VSReferencesResponse = VSReferenceItemsOrNull;

// Type mapping info for `textDocument/_vs_references`
pub const TEXT_DOCUMENT_VS_REFERENCES_INFO: RequestInfo<ReferenceParams, VSReferencesResponse> =
    RequestInfo::new(Method::TEXT_DOCUMENT_VS_REFERENCES);

// Type mapping info for `workspace/didChangeWorkspaceFolders`
pub const WORKSPACE_DID_CHANGE_WORKSPACE_FOLDERS_INFO: NotificationInfo<
    DidChangeWorkspaceFoldersParams,
> = NotificationInfo::new(Method::WORKSPACE_DID_CHANGE_WORKSPACE_FOLDERS);

// Type mapping info for `window/workDoneProgress/cancel`
pub const WINDOW_WORK_DONE_PROGRESS_CANCEL_INFO: NotificationInfo<WorkDoneProgressCancelParams> =
    NotificationInfo::new(Method::WINDOW_WORK_DONE_PROGRESS_CANCEL);

// Type mapping info for `workspace/didCreateFiles`
pub const WORKSPACE_DID_CREATE_FILES_INFO: NotificationInfo<CreateFilesParams> =
    NotificationInfo::new(Method::WORKSPACE_DID_CREATE_FILES);

// Type mapping info for `workspace/didRenameFiles`
pub const WORKSPACE_DID_RENAME_FILES_INFO: NotificationInfo<RenameFilesParams> =
    NotificationInfo::new(Method::WORKSPACE_DID_RENAME_FILES);

// Type mapping info for `workspace/didDeleteFiles`
pub const WORKSPACE_DID_DELETE_FILES_INFO: NotificationInfo<DeleteFilesParams> =
    NotificationInfo::new(Method::WORKSPACE_DID_DELETE_FILES);

// Type mapping info for `initialized`
pub const INITIALIZED_INFO: NotificationInfo<InitializedParams> =
    NotificationInfo::new(Method::INITIALIZED);

// Type mapping info for `exit`
pub const EXIT_INFO: NotificationInfo<NoParams> = NotificationInfo::new(Method::EXIT);

// Type mapping info for `workspace/didChangeConfiguration`
pub const WORKSPACE_DID_CHANGE_CONFIGURATION_INFO: NotificationInfo<DidChangeConfigurationParams> =
    NotificationInfo::new(Method::WORKSPACE_DID_CHANGE_CONFIGURATION);

// Type mapping info for `window/showMessage`
pub const WINDOW_SHOW_MESSAGE_INFO: NotificationInfo<ShowMessageParams> =
    NotificationInfo::new(Method::WINDOW_SHOW_MESSAGE);

// Type mapping info for `window/logMessage`
pub const WINDOW_LOG_MESSAGE_INFO: NotificationInfo<LogMessageParams> =
    NotificationInfo::new(Method::WINDOW_LOG_MESSAGE);

// Type mapping info for `telemetry/event`
pub const TELEMETRY_EVENT_INFO: NotificationInfo<TelemetryEvent> =
    NotificationInfo::new(Method::TELEMETRY_EVENT);

// Type mapping info for `textDocument/didOpen`
pub const TEXT_DOCUMENT_DID_OPEN_INFO: NotificationInfo<DidOpenTextDocumentParams> =
    NotificationInfo::new(Method::TEXT_DOCUMENT_DID_OPEN);

// Type mapping info for `textDocument/didChange`
pub const TEXT_DOCUMENT_DID_CHANGE_INFO: NotificationInfo<DidChangeTextDocumentParams> =
    NotificationInfo::new(Method::TEXT_DOCUMENT_DID_CHANGE);

// Type mapping info for `textDocument/didClose`
pub const TEXT_DOCUMENT_DID_CLOSE_INFO: NotificationInfo<DidCloseTextDocumentParams> =
    NotificationInfo::new(Method::TEXT_DOCUMENT_DID_CLOSE);

// Type mapping info for `textDocument/didSave`
pub const TEXT_DOCUMENT_DID_SAVE_INFO: NotificationInfo<DidSaveTextDocumentParams> =
    NotificationInfo::new(Method::TEXT_DOCUMENT_DID_SAVE);

// Type mapping info for `textDocument/willSave`
pub const TEXT_DOCUMENT_WILL_SAVE_INFO: NotificationInfo<WillSaveTextDocumentParams> =
    NotificationInfo::new(Method::TEXT_DOCUMENT_WILL_SAVE);

// Type mapping info for `workspace/didChangeWatchedFiles`
pub const WORKSPACE_DID_CHANGE_WATCHED_FILES_INFO: NotificationInfo<DidChangeWatchedFilesParams> =
    NotificationInfo::new(Method::WORKSPACE_DID_CHANGE_WATCHED_FILES);

// Type mapping info for `textDocument/publishDiagnostics`
pub const TEXT_DOCUMENT_PUBLISH_DIAGNOSTICS_INFO: NotificationInfo<PublishDiagnosticsParams> =
    NotificationInfo::new(Method::TEXT_DOCUMENT_PUBLISH_DIAGNOSTICS);

// Type mapping info for `$/setTrace`
pub const SET_TRACE_INFO: NotificationInfo<SetTraceParams> =
    NotificationInfo::new(Method::SET_TRACE);

// Type mapping info for `$/logTrace`
pub const LOG_TRACE_INFO: NotificationInfo<LogTraceParams> =
    NotificationInfo::new(Method::LOG_TRACE);

// Type mapping info for `$/cancelRequest`
pub const CANCEL_REQUEST_INFO: NotificationInfo<CancelParams> =
    NotificationInfo::new(Method::CANCEL_REQUEST);

// Type mapping info for `$/progress`
pub const PROGRESS_INFO: NotificationInfo<ProgressParams> = NotificationInfo::new(Method::PROGRESS);

// Type mapping info for `custom/setLogVerbosity`
pub const CUSTOM_SET_LOG_VERBOSITY_INFO: NotificationInfo<SetLogVerbosityParams> =
    NotificationInfo::new(Method::CUSTOM_SET_LOG_VERBOSITY);

// Type aliases

pub type TelemetryEvent =
    RequestFailureTelemetryEventOrPerformanceStatsTelemetryEventOrProjectInfoTelemetryEventOrNull;
