//! Generated by `../_generate/generate.mts` from the pinned `metaModel.json`.
//! Never edit these files by hand.

mod dispatch;
mod enumerations;
mod literals;
mod methods;
mod resolved_capabilities;
mod structures_p1;
mod structures_p2;
mod structures_p3;
mod structures_p4;
mod unions;

pub use dispatch::*;
pub use enumerations::*;
pub use literals::*;
pub use methods::*;
pub use resolved_capabilities::*;
pub use structures_p1::*;
pub use structures_p2::*;
pub use structures_p3::*;
pub use structures_p4::*;
pub use unions::*;
