// Code generated by generate.mts; DO NOT EDIT.
//
// Rust port of typescript-go internal/lsp/lsproto/lsp_generated.go (pinned
// 16c25522e), generated from the same meta model by the ported generator.
// Meta model version 3.17.0

use crate::lsp::lsproto::prelude::*;

// Structures

// DocumentLinkData is a placeholder for custom data preserved on a DocumentLink.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct DocumentLinkData {}

impl UnmarshalerFrom for DocumentLinkData {
    // PORT: Go has no UnmarshalJSONFrom for DocumentLinkData; this is the JSON v2
    // default struct arshaler.
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        match dec.peek_kind() {
            b'n' => {
                dec.read_token()?;
                *self = DocumentLinkData::default();
                Ok(())
            }
            b'{' => {
                dec.read_token()?;
                while dec.peek_kind() != b'}' {
                    let mut name = String::new();
                    json_unmarshal_decode(dec, &mut name)?;
                    dec.skip_value()?;
                }
                dec.read_token()?;
                Ok(())
            }
            _ => {
                dec.skip_value()?;
                Err(JsonError {
                    message: "cannot unmarshal JSON value into Go lsproto.DocumentLinkData"
                        .to_string(),
                })
            }
        }
    }
}

impl MarshalerTo for DocumentLinkData {
    // PORT: Go marshals DocumentLinkData with the JSON v2 default struct arshaler.
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        write_object_start(enc);
        write_object_end(enc);
        Ok(())
    }
}

impl IsZero for DocumentLinkData {
    // PORT: Go reflect.Value.IsZero (omitzero).
    fn is_zero(&self) -> bool {
        true
    }
}

// DiagnosticData is a placeholder for custom data preserved on a Diagnostic.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct DiagnosticData {}

impl UnmarshalerFrom for DiagnosticData {
    // PORT: Go has no UnmarshalJSONFrom for DiagnosticData; this is the JSON v2
    // default struct arshaler.
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        match dec.peek_kind() {
            b'n' => {
                dec.read_token()?;
                *self = DiagnosticData::default();
                Ok(())
            }
            b'{' => {
                dec.read_token()?;
                while dec.peek_kind() != b'}' {
                    let mut name = String::new();
                    json_unmarshal_decode(dec, &mut name)?;
                    dec.skip_value()?;
                }
                dec.read_token()?;
                Ok(())
            }
            _ => {
                dec.skip_value()?;
                Err(JsonError {
                    message: "cannot unmarshal JSON value into Go lsproto.DiagnosticData"
                        .to_string(),
                })
            }
        }
    }
}

impl MarshalerTo for DiagnosticData {
    // PORT: Go marshals DiagnosticData with the JSON v2 default struct arshaler.
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        write_object_start(enc);
        write_object_end(enc);
        Ok(())
    }
}

impl IsZero for DiagnosticData {
    // PORT: Go reflect.Value.IsZero (omitzero).
    fn is_zero(&self) -> bool {
        true
    }
}

// CompletionItemDefaultsData is a placeholder for custom data preserved on a CompletionItemDefaults.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct CompletionItemDefaultsData {}

impl UnmarshalerFrom for CompletionItemDefaultsData {
    // PORT: Go has no UnmarshalJSONFrom for CompletionItemDefaultsData; this is the JSON v2
    // default struct arshaler.
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        match dec.peek_kind() {
            b'n' => {
                dec.read_token()?;
                *self = CompletionItemDefaultsData::default();
                Ok(())
            }
            b'{' => {
                dec.read_token()?;
                while dec.peek_kind() != b'}' {
                    let mut name = String::new();
                    json_unmarshal_decode(dec, &mut name)?;
                    dec.skip_value()?;
                }
                dec.read_token()?;
                Ok(())
            }
            _ => {
                dec.skip_value()?;
                Err(JsonError {
                    message:
                        "cannot unmarshal JSON value into Go lsproto.CompletionItemDefaultsData"
                            .to_string(),
                })
            }
        }
    }
}

impl MarshalerTo for CompletionItemDefaultsData {
    // PORT: Go marshals CompletionItemDefaultsData with the JSON v2 default struct arshaler.
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        write_object_start(enc);
        write_object_end(enc);
        Ok(())
    }
}

impl IsZero for CompletionItemDefaultsData {
    // PORT: Go reflect.Value.IsZero (omitzero).
    fn is_zero(&self) -> bool {
        true
    }
}

// Registration options for textDocument/colorPresentation.
#[derive(Clone, Debug, Default, PartialEq, Eq, Hash)]
pub struct ColorPresentationRegistrationOptions {
    pub work_done_progress: Option<bool>,

    // A document selector to identify the scope of the registration. If set to null
    // the document selector provided on the client side will be used.
    pub document_selector: DocumentSelectorOrNull,
}

impl UnmarshalerFrom for ColorPresentationRegistrationOptions {
    // Go: (s *ColorPresentationRegistrationOptions) UnmarshalJSONFrom
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        const MISSING_DOCUMENT_SELECTOR: u64 = 1 << 0;
        const _MISSING_LAST: u64 = 1 << 1;
        let mut missing = _MISSING_LAST - 1;

        let k = dec.peek_kind();
        if k != b'{' {
            return Err(err_not_object(k));
        }
        dec.read_token()?;

        while dec.peek_kind() != b'}' {
            let name = dec.read_value()?;
            match name {
                b"\"workDoneProgress\"" => {
                    if dec.peek_kind() == b'n' {
                        return Err(err_null("workDoneProgress"));
                    }
                    json_unmarshal_decode(dec, &mut self.work_done_progress)?;
                }
                b"\"documentSelector\"" => {
                    missing &= !MISSING_DOCUMENT_SELECTOR;
                    json_unmarshal_decode(dec, &mut self.document_selector)?;
                }
                _ => {
                    dec.skip_value()?;
                }
            }
        }

        dec.read_token()?;

        if missing != 0 {
            let mut missing_props: Vec<String> = Vec::new();
            if missing & MISSING_DOCUMENT_SELECTOR != 0 {
                missing_props.push("documentSelector".to_string());
            }
            return Err(err_missing(&missing_props));
        }

        Ok(())
    }
}

impl MarshalerTo for ColorPresentationRegistrationOptions {
    // PORT: Go marshals ColorPresentationRegistrationOptions with the JSON v2 default struct arshaler.
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        write_object_start(enc);
        let mut first = true;
        marshal_opt_field(
            enc,
            &mut first,
            "workDoneProgress",
            &self.work_done_progress,
        )?;
        marshal_field(enc, &mut first, "documentSelector", &self.document_selector)?;
        write_object_end(enc);
        Ok(())
    }
}

impl IsZero for ColorPresentationRegistrationOptions {
    // PORT: Go reflect.Value.IsZero (omitzero).
    fn is_zero(&self) -> bool {
        self.work_done_progress.is_none() && self.document_selector.is_zero()
    }
}
