// Code generated by generate.mts; DO NOT EDIT.
//
// Rust port of microsoft/TypeScript tsc/internal/lsp/lsproto/lsp_generated.go
// (pinned 673a5f17d713), generated from the same meta model by the ported generator.
// Meta model version 3.18.0

use crate::lsp::lsproto::prelude::*;

// Structures

// DocumentLinkData is a placeholder for custom data preserved on a DocumentLink.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct DocumentLinkData {}

impl UnmarshalerFrom for DocumentLinkData {
    // PORT: Go has no UnmarshalJSONFrom for DocumentLinkData; this is the JSON v2
    // default struct arshaler.
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        match dec.peek_kind() {
            b'n' => {
                dec.read_token()?;
                *self = DocumentLinkData::default();
                Ok(())
            }
            b'{' => {
                dec.read_token()?;
                while dec.peek_kind() != b'}' {
                    let mut name = String::new();
                    json_unmarshal_decode(dec, &mut name)?;
                    dec.skip_value()?;
                }
                dec.read_token()?;
                Ok(())
            }
            _ => {
                dec.skip_value()?;
                Err(JsonError {
                    message: "cannot unmarshal JSON value into Go lsproto.DocumentLinkData"
                        .to_string(),
                })
            }
        }
    }
}

impl MarshalerTo for DocumentLinkData {
    // PORT: Go marshals DocumentLinkData with the JSON v2 default struct arshaler.
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        write_object_start(enc);
        write_object_end(enc);
        Ok(())
    }
}

impl IsZero for DocumentLinkData {
    // PORT: Go reflect.Value.IsZero (omitzero).
    fn is_zero(&self) -> bool {
        true
    }
}

// DiagnosticData is a placeholder for custom data preserved on a Diagnostic.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct DiagnosticData {}

impl UnmarshalerFrom for DiagnosticData {
    // PORT: Go has no UnmarshalJSONFrom for DiagnosticData; this is the JSON v2
    // default struct arshaler.
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        match dec.peek_kind() {
            b'n' => {
                dec.read_token()?;
                *self = DiagnosticData::default();
                Ok(())
            }
            b'{' => {
                dec.read_token()?;
                while dec.peek_kind() != b'}' {
                    let mut name = String::new();
                    json_unmarshal_decode(dec, &mut name)?;
                    dec.skip_value()?;
                }
                dec.read_token()?;
                Ok(())
            }
            _ => {
                dec.skip_value()?;
                Err(JsonError {
                    message: "cannot unmarshal JSON value into Go lsproto.DiagnosticData"
                        .to_string(),
                })
            }
        }
    }
}

impl MarshalerTo for DiagnosticData {
    // PORT: Go marshals DiagnosticData with the JSON v2 default struct arshaler.
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        write_object_start(enc);
        write_object_end(enc);
        Ok(())
    }
}

impl IsZero for DiagnosticData {
    // PORT: Go reflect.Value.IsZero (omitzero).
    fn is_zero(&self) -> bool {
        true
    }
}

// CompletionItemDefaultsData is a placeholder for custom data preserved on a CompletionItemDefaults.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub struct CompletionItemDefaultsData {}

impl UnmarshalerFrom for CompletionItemDefaultsData {
    // PORT: Go has no UnmarshalJSONFrom for CompletionItemDefaultsData; this is the JSON v2
    // default struct arshaler.
    fn unmarshal_json_from(&mut self, dec: &mut JsonDecoder<'_>) -> Result<(), JsonError> {
        match dec.peek_kind() {
            b'n' => {
                dec.read_token()?;
                *self = CompletionItemDefaultsData::default();
                Ok(())
            }
            b'{' => {
                dec.read_token()?;
                while dec.peek_kind() != b'}' {
                    let mut name = String::new();
                    json_unmarshal_decode(dec, &mut name)?;
                    dec.skip_value()?;
                }
                dec.read_token()?;
                Ok(())
            }
            _ => {
                dec.skip_value()?;
                Err(JsonError {
                    message:
                        "cannot unmarshal JSON value into Go lsproto.CompletionItemDefaultsData"
                            .to_string(),
                })
            }
        }
    }
}

impl MarshalerTo for CompletionItemDefaultsData {
    // PORT: Go marshals CompletionItemDefaultsData with the JSON v2 default struct arshaler.
    fn marshal_json_to(&self, enc: &mut String) -> Result<(), JsonError> {
        write_object_start(enc);
        write_object_end(enc);
        Ok(())
    }
}

impl IsZero for CompletionItemDefaultsData {
    // PORT: Go reflect.Value.IsZero (omitzero).
    fn is_zero(&self) -> bool {
        true
    }
}
