// Code generated by tools/ts_ast_codegen. DO NOT EDIT.

use crate::SyntaxKind;
use ts_core::TextRange;

#[derive(Clone, Copy, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct NodeId(u32);

impl NodeId {
    #[must_use]
    pub const fn new(index: u32) -> Self {
        Self(index)
    }

    #[must_use]
    pub const fn index(self) -> usize {
        self.0 as usize
    }
}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct SymbolId(pub u32);

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct FlowNodeId(pub u32);

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct NodeFlags(pub u32);

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct TokenFlags(pub u32);

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct ModifierFlags(pub u32);

#[derive(Clone, Debug, Default)]
pub struct SymbolTable;

#[derive(Clone, Debug, Default)]
pub struct OpaqueValue;

#[derive(Clone, Debug, Default)]
pub struct NodeList {
    pub range: TextRange,
    pub nodes: Vec<NodeId>,
    pub has_trailing_comma: bool,
}

#[derive(Clone, Debug, Default)]
pub struct ModifierList {
    pub list: NodeList,
    pub flags: ModifierFlags,
}

#[derive(Clone, Debug)]
pub struct Node {
    pub kind: SyntaxKind,
    pub flags: NodeFlags,
    pub range: TextRange,
    pub parent: Option<NodeId>,
    pub data: NodeData,
}

#[derive(Clone, Debug, Default)]
pub struct NodeArena {
    nodes: Vec<Node>,
    source_text: Option<String>,
}

impl NodeArena {
    #[must_use]
    pub const fn new() -> Self {
        Self {
            nodes: Vec::new(),
            source_text: None,
        }
    }

    pub fn set_source_text(&mut self, source_text: impl Into<String>) {
        self.source_text = Some(source_text.into());
    }

    #[must_use]
    pub fn source_text(&self) -> Option<&str> {
        self.source_text.as_deref()
    }

    /// Allocate a node and return its stable arena identifier.
    ///
    /// # Panics
    ///
    /// Panics if the arena contains more than `u32::MAX` nodes.
    pub fn alloc(&mut self, node: Node) -> NodeId {
        let index = u32::try_from(self.nodes.len()).expect("AST node arena exceeds u32::MAX nodes");
        self.nodes.push(node);
        NodeId::new(index)
    }

    #[must_use]
    pub fn get(&self, id: NodeId) -> Option<&Node> {
        self.nodes.get(id.index())
    }

    #[must_use]
    pub fn get_mut(&mut self, id: NodeId) -> Option<&mut Node> {
        self.nodes.get_mut(id.index())
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.nodes.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }

    /// Iterate over nodes in allocation order with their identifiers.
    ///
    /// # Panics
    ///
    /// Panics if the arena invariant limiting it to `u32::MAX` nodes is broken.
    #[must_use]
    pub fn iter(&self) -> impl ExactSizeIterator<Item = (NodeId, &Node)> {
        self.nodes.iter().enumerate().map(|(index, node)| {
            let index = u32::try_from(index).expect("AST node arena exceeds u32::MAX nodes");
            (NodeId::new(index), node)
        })
    }
}

#[derive(Clone, Debug)]
pub struct ArrayLiteralExpressionData {
    pub elements: NodeList,
    pub multi_line: bool,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct ArrayTypeNodeData {
    pub element_type: NodeId,
}

#[derive(Clone, Debug)]
pub struct ArrowFunctionData {
    pub asterisk_token: Option<NodeId>,
    pub body: NodeId,
    pub end_flow_node: Option<FlowNodeId>,
    pub equals_greater_than_token: NodeId,
    pub flow_node: Option<FlowNodeId>,
    pub full_signature: Option<NodeId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub parameters: NodeList,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub type_parameters: Option<NodeList>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
}

#[derive(Clone, Debug)]
pub struct AsExpressionData {
    pub expression: NodeId,
    pub type_: NodeId,
}

#[derive(Clone, Debug)]
pub struct AwaitExpressionData {
    pub expression: NodeId,
}

#[derive(Clone, Debug)]
pub struct BigIntLiteralData {
    pub text: String,
    pub token_flags: TokenFlags,
}

#[derive(Clone, Debug)]
pub struct BinaryExpressionData {
    pub left: NodeId,
    pub operator_token: NodeId,
    pub right: NodeId,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
}

#[derive(Clone, Debug)]
pub struct BindingElementData {
    pub dot_dot_dot_token: Option<NodeId>,
    pub flow_node: Option<FlowNodeId>,
    pub initializer: Option<NodeId>,
    pub local_symbol: Option<SymbolId>,
    pub property_name: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub facts: u32,
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug)]
pub struct BindingPatternData {
    pub elements: NodeList,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct BlockData {
    pub flow_node: Option<FlowNodeId>,
    pub locals: SymbolTable,
    pub multi_line: bool,
    pub next_container: Option<NodeId>,
    pub statements: NodeList,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct BreakStatementData {
    pub flow_node: Option<FlowNodeId>,
    pub label: Option<NodeId>,
}

#[derive(Clone, Debug)]
pub struct CallExpressionData {
    pub arguments: NodeList,
    pub expression: NodeId,
    pub question_dot_token: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub type_arguments: Option<NodeList>,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct CallSignatureDeclarationData {
    pub full_signature: Option<NodeId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub parameters: NodeList,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub type_parameters: Option<NodeList>,
}

#[derive(Clone, Debug)]
pub struct CaseBlockData {
    pub clauses: NodeList,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct CaseOrDefaultClauseData {
    pub expression: NodeId,
    pub fallthrough_flow_node: Option<FlowNodeId>,
    pub statements: NodeList,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct CatchClauseData {
    pub block: NodeId,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub variable_declaration: Option<NodeId>,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct ClassDeclarationData {
    pub flow_node: Option<FlowNodeId>,
    pub heritage_clauses: Option<NodeList>,
    pub local_symbol: Option<SymbolId>,
    pub locals: SymbolTable,
    pub members: NodeList,
    pub next_container: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub type_parameters: Option<NodeList>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug)]
pub struct ClassExpressionData {
    pub heritage_clauses: Option<NodeList>,
    pub local_symbol: Option<SymbolId>,
    pub locals: SymbolTable,
    pub members: NodeList,
    pub next_container: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub type_parameters: Option<NodeList>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug)]
pub struct ClassStaticBlockDeclarationData {
    pub body: NodeId,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub return_flow_node: Option<FlowNodeId>,
    pub symbol: Option<SymbolId>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
}

#[derive(Clone, Debug)]
pub struct ComputedPropertyNameData {
    pub expression: NodeId,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct ConditionalExpressionData {
    pub colon_token: NodeId,
    pub condition: NodeId,
    pub question_token: NodeId,
    pub when_false: NodeId,
    pub when_true: NodeId,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct ConditionalTypeNodeData {
    pub check_type: NodeId,
    pub extends_type: NodeId,
    pub false_type: NodeId,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub true_type: NodeId,
}

#[derive(Clone, Debug)]
pub struct ConstructSignatureDeclarationData {
    pub full_signature: Option<NodeId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub parameters: NodeList,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub type_parameters: Option<NodeList>,
}

#[derive(Clone, Debug)]
pub struct ConstructorDeclarationData {
    pub asterisk_token: Option<NodeId>,
    pub body: Option<NodeId>,
    pub end_flow_node: Option<FlowNodeId>,
    pub full_signature: Option<NodeId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub parameters: NodeList,
    pub return_flow_node: Option<FlowNodeId>,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub type_parameters: Option<NodeList>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
}

#[derive(Clone, Debug)]
pub struct ConstructorTypeNodeData {
    pub full_signature: Option<NodeId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub parameters: NodeList,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub type_parameters: Option<NodeList>,
    pub modifiers: Option<ModifierList>,
}

#[derive(Clone, Debug)]
pub struct ContinueStatementData {
    pub flow_node: Option<FlowNodeId>,
    pub label: Option<NodeId>,
}

#[derive(Clone, Debug)]
pub struct DebuggerStatementData {
    pub flow_node: Option<FlowNodeId>,
}

#[derive(Clone, Debug)]
pub struct DecoratorData {
    pub expression: NodeId,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct DeleteExpressionData {
    pub expression: NodeId,
}

#[derive(Clone, Debug)]
pub struct DoStatementData {
    pub expression: NodeId,
    pub flow_node: Option<FlowNodeId>,
    pub statement: NodeId,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct ElementAccessExpressionData {
    pub argument_expression: NodeId,
    pub expression: NodeId,
    pub flow_node: Option<FlowNodeId>,
    pub question_dot_token: Option<NodeId>,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct EmptyStatementData {
    pub flow_node: Option<FlowNodeId>,
}

#[derive(Clone, Debug)]
pub struct EnumDeclarationData {
    pub flow_node: Option<FlowNodeId>,
    pub local_symbol: Option<SymbolId>,
    pub members: NodeList,
    pub symbol: Option<SymbolId>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct EnumMemberData {
    pub initializer: Option<NodeId>,
    pub postfix_token: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct ExportAssignmentData {
    pub expression: NodeId,
    pub flow_node: Option<FlowNodeId>,
    pub is_export_equals: bool,
    pub symbol: Option<SymbolId>,
    pub type_: NodeId,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
}

#[derive(Clone, Debug)]
pub struct ExportDeclarationData {
    pub attributes: Option<NodeId>,
    pub export_clause: Option<NodeId>,
    pub flow_node: Option<FlowNodeId>,
    pub is_type_only: bool,
    pub module_specifier: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
}

#[derive(Clone, Debug)]
pub struct ExportSpecifierData {
    pub is_type_only: bool,
    pub local_symbol: Option<SymbolId>,
    pub property_name: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub facts: u32,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct ExpressionStatementData {
    pub expression: NodeId,
    pub flow_node: Option<FlowNodeId>,
}

#[derive(Clone, Debug)]
pub struct ExpressionWithTypeArgumentsData {
    pub expression: NodeId,
    pub type_arguments: Option<NodeList>,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct ExternalModuleReferenceData {
    pub expression: NodeId,
}

#[derive(Clone, Debug)]
pub struct ForInOrOfStatementData {
    pub await_modifier: Option<NodeId>,
    pub expression: NodeId,
    pub flow_node: Option<FlowNodeId>,
    pub initializer: NodeId,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub statement: NodeId,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct ForStatementData {
    pub condition: Option<NodeId>,
    pub flow_node: Option<FlowNodeId>,
    pub incrementor: Option<NodeId>,
    pub initializer: Option<NodeId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub statement: NodeId,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct FunctionDeclarationData {
    pub asterisk_token: Option<NodeId>,
    pub body: Option<NodeId>,
    pub end_flow_node: Option<FlowNodeId>,
    pub flow_node: Option<FlowNodeId>,
    pub full_signature: Option<NodeId>,
    pub local_symbol: Option<SymbolId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub parameters: NodeList,
    pub return_flow_node: Option<FlowNodeId>,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub type_parameters: Option<NodeList>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug)]
pub struct FunctionExpressionData {
    pub asterisk_token: Option<NodeId>,
    pub body: NodeId,
    pub end_flow_node: Option<FlowNodeId>,
    pub flow_node: Option<FlowNodeId>,
    pub full_signature: Option<NodeId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub parameters: NodeList,
    pub return_flow_node: Option<FlowNodeId>,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub type_parameters: Option<NodeList>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug)]
pub struct FunctionTypeNodeData {
    pub full_signature: Option<NodeId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub parameters: NodeList,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub type_parameters: Option<NodeList>,
    pub modifiers: Option<ModifierList>,
}

#[derive(Clone, Debug)]
pub struct GetAccessorDeclarationData {
    pub asterisk_token: Option<NodeId>,
    pub body: Option<NodeId>,
    pub end_flow_node: Option<FlowNodeId>,
    pub flow_node: Option<FlowNodeId>,
    pub full_signature: Option<NodeId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub parameters: NodeList,
    pub postfix_token: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub type_parameters: Option<NodeList>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct HeritageClauseData {
    pub token: SyntaxKind,
    pub types: NodeList,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct IdentifierData {
    pub flow_node: Option<FlowNodeId>,
    pub text: String,
}

#[derive(Clone, Debug)]
pub struct IfStatementData {
    pub else_statement: Option<NodeId>,
    pub expression: NodeId,
    pub flow_node: Option<FlowNodeId>,
    pub then_statement: NodeId,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct ImportAttributeData {
    pub value: NodeId,
    pub facts: u32,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct ImportAttributesData {
    pub attributes: NodeList,
    pub multi_line: bool,
    pub token: SyntaxKind,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct ImportClauseData {
    pub local_symbol: Option<SymbolId>,
    pub named_bindings: Option<NodeId>,
    pub phase_modifier: Option<SyntaxKind>,
    pub symbol: Option<SymbolId>,
    pub facts: u32,
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug)]
pub struct ImportDeclarationData {
    pub attributes: Option<NodeId>,
    pub flow_node: Option<FlowNodeId>,
    pub import_clause: Option<NodeId>,
    pub module_specifier: NodeId,
    pub symbol: Option<SymbolId>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
}

#[derive(Clone, Debug)]
pub struct ImportEqualsDeclarationData {
    pub flow_node: Option<FlowNodeId>,
    pub is_type_only: bool,
    pub local_symbol: Option<SymbolId>,
    pub module_reference: NodeId,
    pub symbol: Option<SymbolId>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct ImportSpecifierData {
    pub is_type_only: bool,
    pub local_symbol: Option<SymbolId>,
    pub property_name: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub facts: u32,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct ImportTypeNodeData {
    pub argument: NodeId,
    pub attributes: Option<NodeId>,
    pub is_type_of: bool,
    pub qualifier: Option<NodeId>,
    pub type_arguments: Option<NodeList>,
}

#[derive(Clone, Debug)]
pub struct IndexSignatureDeclarationData {
    pub full_signature: Option<NodeId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub parameters: NodeList,
    pub symbol: Option<SymbolId>,
    pub type_: NodeId,
    pub type_parameters: Option<NodeList>,
    pub modifiers: Option<ModifierList>,
}

#[derive(Clone, Debug)]
pub struct IndexedAccessTypeNodeData {
    pub index_type: NodeId,
    pub object_type: NodeId,
}

#[derive(Clone, Debug)]
pub struct InferTypeNodeData {
    pub type_parameter: NodeId,
}

#[derive(Clone, Debug)]
pub struct InterfaceDeclarationData {
    pub flow_node: Option<FlowNodeId>,
    pub heritage_clauses: Option<NodeList>,
    pub local_symbol: Option<SymbolId>,
    pub members: NodeList,
    pub symbol: Option<SymbolId>,
    pub type_parameters: Option<NodeList>,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct IntersectionTypeNodeData {
    pub types: NodeList,
}

#[derive(Clone, Debug)]
pub struct JsDocData {
    pub comment: NodeList,
    pub tags: Option<NodeList>,
}

#[derive(Clone, Debug)]
pub struct JsDocAllTypeData;

#[derive(Clone, Debug)]
pub struct JsDocAugmentsTagData {
    pub class_name: NodeId,
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocCallbackTagData {
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
    pub type_expression: NodeId,
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug)]
pub struct JsDocDeprecatedTagData {
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocImplementsTagData {
    pub class_name: NodeId,
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocImportTagData {
    pub attributes: Option<NodeId>,
    pub comment: Option<NodeList>,
    pub import_clause: Option<NodeId>,
    pub module_specifier: NodeId,
    pub tag_name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocLinkData {
    pub name: Option<NodeId>,
    pub text: Vec<String>,
}

#[derive(Clone, Debug)]
pub struct JsDocLinkCodeData {
    pub name: Option<NodeId>,
    pub text: Vec<String>,
}

#[derive(Clone, Debug)]
pub struct JsDocLinkPlainData {
    pub name: Option<NodeId>,
    pub text: Vec<String>,
}

#[derive(Clone, Debug)]
pub struct JsDocNameReferenceData {
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocNonNullableTypeData {
    pub type_: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocNullableTypeData {
    pub type_: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocOptionalTypeData {
    pub type_: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocOverloadTagData {
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
    pub type_expression: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocOverrideTagData {
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocParameterOrPropertyTagData {
    pub comment: Option<NodeList>,
    pub is_bracketed: bool,
    pub is_name_first: bool,
    pub tag_name: NodeId,
    pub type_expression: Option<NodeId>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocPrivateTagData {
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocProtectedTagData {
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocPublicTagData {
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocReadonlyTagData {
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocReturnTagData {
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
    pub type_expression: Option<NodeId>,
}

#[derive(Clone, Debug)]
pub struct JsDocSatisfiesTagData {
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
    pub type_expression: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocSeeTagData {
    pub comment: Option<NodeList>,
    pub name_expression: NodeId,
    pub tag_name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocSignatureData {
    pub full_signature: Option<NodeId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub parameters: NodeList,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub type_parameters: Option<NodeList>,
}

#[derive(Clone, Debug)]
pub struct JsDocTemplateTagData {
    pub comment: Option<NodeList>,
    pub constraint: NodeId,
    pub tag_name: NodeId,
    pub type_parameters: NodeList,
}

#[derive(Clone, Debug)]
pub struct JsDocTextData {
    pub text: Vec<String>,
}

#[derive(Clone, Debug)]
pub struct JsDocThisTagData {
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
    pub type_expression: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocThrowsTagData {
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
    pub type_expression: Option<NodeId>,
}

#[derive(Clone, Debug)]
pub struct JsDocTypeExpressionData {
    pub type_: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocTypeLiteralData {
    pub is_array_type: bool,
    pub js_doc_property_tags: Option<Vec<NodeId>>,
    pub symbol: Option<SymbolId>,
}

#[derive(Clone, Debug)]
pub struct JsDocTypeTagData {
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
    pub type_expression: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocTypedefTagData {
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
    pub type_expression: Option<NodeId>,
    pub name: Option<NodeId>,
}

#[derive(Clone, Debug)]
pub struct JsDocUnknownTagData {
    pub comment: Option<NodeList>,
    pub tag_name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsDocVariadicTypeData {
    pub type_: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsxAttributeData {
    pub initializer: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub facts: u32,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsxAttributesData {
    pub properties: NodeList,
    pub symbol: Option<SymbolId>,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct JsxClosingElementData {
    pub tag_name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsxClosingFragmentData;

#[derive(Clone, Debug)]
pub struct JsxElementData {
    pub children: NodeList,
    pub closing_element: NodeId,
    pub opening_element: NodeId,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct JsxExpressionData {
    pub dot_dot_dot_token: Option<NodeId>,
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug)]
pub struct JsxFragmentData {
    pub children: NodeList,
    pub closing_fragment: NodeId,
    pub opening_fragment: NodeId,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct JsxNamespacedNameData {
    pub namespace: NodeId,
    pub facts: u32,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsxOpeningElementData {
    pub attributes: NodeId,
    pub tag_name: NodeId,
    pub type_arguments: Option<NodeList>,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct JsxOpeningFragmentData;

#[derive(Clone, Debug)]
pub struct JsxSelfClosingElementData {
    pub attributes: NodeId,
    pub tag_name: NodeId,
    pub type_arguments: Option<NodeList>,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct JsxSpreadAttributeData {
    pub expression: NodeId,
}

#[derive(Clone, Debug)]
pub struct JsxTextData {
    pub contains_only_trivia_white_spaces: bool,
    pub text: String,
    pub token_flags: TokenFlags,
}

#[derive(Clone, Debug)]
pub struct KeywordExpressionData {
    pub flow_node: Option<FlowNodeId>,
}

#[derive(Clone, Debug)]
pub struct KeywordTypeNodeData;

#[derive(Clone, Debug)]
pub struct LabeledStatementData {
    pub flow_node: Option<FlowNodeId>,
    pub label: NodeId,
    pub statement: NodeId,
}

#[derive(Clone, Debug)]
pub struct LiteralTypeNodeData {
    pub literal: NodeId,
}

#[derive(Clone, Debug)]
pub struct MappedTypeNodeData {
    pub locals: SymbolTable,
    pub members: Option<NodeList>,
    pub name_type: Option<NodeId>,
    pub next_container: Option<NodeId>,
    pub question_token: Option<NodeId>,
    pub readonly_token: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub type_parameter: NodeId,
}

#[derive(Clone, Debug)]
pub struct MetaPropertyData {
    pub flow_node: Option<FlowNodeId>,
    pub keyword_token: SyntaxKind,
    pub facts: u32,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct MethodDeclarationData {
    pub asterisk_token: Option<NodeId>,
    pub body: Option<NodeId>,
    pub end_flow_node: Option<FlowNodeId>,
    pub flow_node: Option<FlowNodeId>,
    pub full_signature: Option<NodeId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub parameters: NodeList,
    pub postfix_token: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub type_parameters: Option<NodeList>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct MethodSignatureDeclarationData {
    pub full_signature: Option<NodeId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub parameters: NodeList,
    pub postfix_token: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub type_parameters: Option<NodeList>,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct MissingDeclarationData {
    pub flow_node: Option<FlowNodeId>,
    pub symbol: Option<SymbolId>,
    pub modifiers: Option<ModifierList>,
}

#[derive(Clone, Debug)]
pub struct ModuleBlockData {
    pub flow_node: Option<FlowNodeId>,
    pub statements: NodeList,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct ModuleDeclarationData {
    pub asterisk_token: Option<NodeId>,
    pub body: Option<NodeId>,
    pub end_flow_node: Option<FlowNodeId>,
    pub flow_node: Option<FlowNodeId>,
    pub keyword: SyntaxKind,
    pub local_symbol: Option<SymbolId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct NamedExportsData {
    pub elements: NodeList,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct NamedImportsData {
    pub elements: NodeList,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct NamedTupleMemberData {
    pub dot_dot_dot_token: Option<NodeId>,
    pub question_token: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub type_: NodeId,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct NamespaceExportData {
    pub symbol: Option<SymbolId>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct NamespaceExportDeclarationData {
    pub flow_node: Option<FlowNodeId>,
    pub symbol: Option<SymbolId>,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct NamespaceImportData {
    pub local_symbol: Option<SymbolId>,
    pub symbol: Option<SymbolId>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct NewExpressionData {
    pub arguments: Option<NodeList>,
    pub expression: NodeId,
    pub type_arguments: Option<NodeList>,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct NoSubstitutionTemplateLiteralData {
    pub raw_text: String,
    pub symbol: Option<SymbolId>,
    pub template_flags: TokenFlags,
    pub text: String,
    pub token_flags: TokenFlags,
}

#[derive(Clone, Debug)]
pub struct NonNullExpressionData {
    pub expression: NodeId,
}

#[derive(Clone, Debug)]
pub struct NotEmittedStatementData {
    pub flow_node: Option<FlowNodeId>,
}

#[derive(Clone, Debug)]
pub struct NotEmittedTypeElementData;

#[derive(Clone, Debug)]
pub struct NumericLiteralData {
    pub text: String,
    pub token_flags: TokenFlags,
}

#[derive(Clone, Debug)]
pub struct ObjectLiteralExpressionData {
    pub multi_line: bool,
    pub properties: NodeList,
    pub symbol: Option<SymbolId>,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct OmittedExpressionData;

#[derive(Clone, Debug)]
pub struct OptionalTypeNodeData {
    pub type_: NodeId,
}

#[derive(Clone, Debug)]
pub struct ParameterDeclarationData {
    pub dot_dot_dot_token: Option<NodeId>,
    pub initializer: Option<NodeId>,
    pub question_token: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct ParenthesizedExpressionData {
    pub expression: NodeId,
}

#[derive(Clone, Debug)]
pub struct ParenthesizedTypeNodeData {
    pub type_: NodeId,
}

#[derive(Clone, Debug)]
pub struct PartiallyEmittedExpressionData {
    pub expression: NodeId,
}

#[derive(Clone, Debug)]
pub struct PostfixUnaryExpressionData {
    pub operand: NodeId,
    pub operator: SyntaxKind,
}

#[derive(Clone, Debug)]
pub struct PrefixUnaryExpressionData {
    pub operand: NodeId,
    pub operator: SyntaxKind,
}

#[derive(Clone, Debug)]
pub struct PrivateIdentifierData {
    pub text: String,
}

#[derive(Clone, Debug)]
pub struct PropertyAccessExpressionData {
    pub expression: NodeId,
    pub flow_node: Option<FlowNodeId>,
    pub question_dot_token: Option<NodeId>,
    pub facts: u32,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct PropertyAssignmentData {
    pub initializer: NodeId,
    pub postfix_token: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub type_: NodeId,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct PropertyDeclarationData {
    pub initializer: Option<NodeId>,
    pub postfix_token: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct PropertySignatureDeclarationData {
    pub initializer: NodeId,
    pub postfix_token: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub type_: NodeId,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct QualifiedNameData {
    pub flow_node: Option<FlowNodeId>,
    pub left: NodeId,
    pub right: NodeId,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct RegularExpressionLiteralData {
    pub text: String,
    pub token_flags: TokenFlags,
}

#[derive(Clone, Debug)]
pub struct RestTypeNodeData {
    pub type_: NodeId,
}

#[derive(Clone, Debug)]
pub struct ReturnStatementData {
    pub expression: Option<NodeId>,
    pub flow_node: Option<FlowNodeId>,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct SatisfiesExpressionData {
    pub expression: NodeId,
    pub type_: NodeId,
}

#[derive(Clone, Debug)]
pub struct SemicolonClassElementData {
    pub symbol: Option<SymbolId>,
}

#[derive(Clone, Debug)]
pub struct SetAccessorDeclarationData {
    pub asterisk_token: Option<NodeId>,
    pub body: Option<NodeId>,
    pub end_flow_node: Option<FlowNodeId>,
    pub flow_node: Option<FlowNodeId>,
    pub full_signature: Option<NodeId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub parameters: NodeList,
    pub postfix_token: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub type_parameters: Option<NodeList>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct ShorthandPropertyAssignmentData {
    pub equals_token: Option<NodeId>,
    pub object_assignment_initializer: Option<NodeId>,
    pub postfix_token: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub type_: NodeId,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct SourceFileData {
    pub end_of_file_token: NodeId,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub statements: NodeList,
    pub symbol: Option<SymbolId>,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct SpreadAssignmentData {
    pub expression: NodeId,
    pub symbol: Option<SymbolId>,
}

#[derive(Clone, Debug)]
pub struct SpreadElementData {
    pub expression: NodeId,
}

#[derive(Clone, Debug)]
pub struct StringLiteralData {
    pub text: String,
    pub token_flags: TokenFlags,
}

#[derive(Clone, Debug)]
pub struct SwitchStatementData {
    pub case_block: NodeId,
    pub expression: NodeId,
    pub flow_node: Option<FlowNodeId>,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct SyntaxListData {
    pub children: Vec<NodeId>,
}

#[derive(Clone, Debug)]
pub struct SyntheticExpressionData {
    pub is_spread: bool,
    pub tuple_name_source: Option<NodeId>,
    pub type_: OpaqueValue,
}

#[derive(Clone, Debug)]
pub struct SyntheticReferenceExpressionData {
    pub expression: NodeId,
    pub this_arg: NodeId,
}

#[derive(Clone, Debug)]
pub struct TaggedTemplateExpressionData {
    pub question_dot_token: Option<NodeId>,
    pub tag: NodeId,
    pub template: NodeId,
    pub type_arguments: Option<NodeList>,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct TemplateExpressionData {
    pub head: NodeId,
    pub template_spans: NodeList,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct TemplateHeadData {
    pub raw_text: String,
    pub template_flags: TokenFlags,
    pub text: String,
    pub token_flags: TokenFlags,
}

#[derive(Clone, Debug)]
pub struct TemplateLiteralTypeNodeData {
    pub head: NodeId,
    pub template_spans: NodeList,
}

#[derive(Clone, Debug)]
pub struct TemplateLiteralTypeSpanData {
    pub literal: NodeId,
    pub type_: NodeId,
}

#[derive(Clone, Debug)]
pub struct TemplateMiddleData {
    pub raw_text: String,
    pub template_flags: TokenFlags,
    pub text: String,
    pub token_flags: TokenFlags,
}

#[derive(Clone, Debug)]
pub struct TemplateSpanData {
    pub expression: NodeId,
    pub literal: NodeId,
}

#[derive(Clone, Debug)]
pub struct TemplateTailData {
    pub raw_text: String,
    pub template_flags: TokenFlags,
    pub text: String,
    pub token_flags: TokenFlags,
}

#[derive(Clone, Debug)]
pub struct ThisTypeNodeData;

#[derive(Clone, Debug)]
pub struct ThrowStatementData {
    pub expression: NodeId,
    pub flow_node: Option<FlowNodeId>,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct TokenData;

#[derive(Clone, Debug)]
pub struct TryStatementData {
    pub catch_clause: Option<NodeId>,
    pub finally_block: Option<NodeId>,
    pub flow_node: Option<FlowNodeId>,
    pub try_block: NodeId,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct TupleTypeNodeData {
    pub elements: NodeList,
}

#[derive(Clone, Debug)]
pub struct TypeAliasDeclarationData {
    pub flow_node: Option<FlowNodeId>,
    pub local_symbol: Option<SymbolId>,
    pub locals: SymbolTable,
    pub next_container: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub type_: NodeId,
    pub type_parameters: Option<NodeList>,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct TypeAssertionData {
    pub expression: NodeId,
    pub type_: NodeId,
}

#[derive(Clone, Debug)]
pub struct TypeLiteralNodeData {
    pub members: NodeList,
    pub symbol: Option<SymbolId>,
}

#[derive(Clone, Debug)]
pub struct TypeOfExpressionData {
    pub expression: NodeId,
}

#[derive(Clone, Debug)]
pub struct TypeOperatorNodeData {
    pub operator: SyntaxKind,
    pub type_: NodeId,
}

#[derive(Clone, Debug)]
pub struct TypeParameterDeclarationData {
    pub constraint: Option<NodeId>,
    pub default_type: Option<NodeId>,
    pub expression: Option<NodeId>,
    pub symbol: Option<SymbolId>,
    pub modifiers: Option<ModifierList>,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct TypePredicateNodeData {
    pub asserts_modifier: Option<NodeId>,
    pub parameter_name: NodeId,
    pub type_: Option<NodeId>,
}

#[derive(Clone, Debug)]
pub struct TypeQueryNodeData {
    pub expr_name: NodeId,
    pub type_arguments: Option<NodeList>,
}

#[derive(Clone, Debug)]
pub struct TypeReferenceNodeData {
    pub type_arguments: Option<NodeList>,
    pub type_name: NodeId,
}

#[derive(Clone, Debug)]
pub struct UnionTypeNodeData {
    pub types: NodeList,
}

#[derive(Clone, Debug)]
pub struct VariableDeclarationData {
    pub exclamation_token: Option<NodeId>,
    pub initializer: Option<NodeId>,
    pub local_symbol: Option<SymbolId>,
    pub symbol: Option<SymbolId>,
    pub type_: Option<NodeId>,
    pub facts: u32,
    pub name: NodeId,
}

#[derive(Clone, Debug)]
pub struct VariableDeclarationListData {
    pub declarations: NodeList,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct VariableStatementData {
    pub declaration_list: NodeId,
    pub flow_node: Option<FlowNodeId>,
    pub facts: u32,
    pub modifiers: Option<ModifierList>,
}

#[derive(Clone, Debug)]
pub struct VoidExpressionData {
    pub expression: NodeId,
}

#[derive(Clone, Debug)]
pub struct WhileStatementData {
    pub expression: NodeId,
    pub flow_node: Option<FlowNodeId>,
    pub statement: NodeId,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct WithStatementData {
    pub expression: NodeId,
    pub flow_node: Option<FlowNodeId>,
    pub statement: NodeId,
    pub facts: u32,
}

#[derive(Clone, Debug)]
pub struct YieldExpressionData {
    pub asterisk_token: Option<NodeId>,
    pub expression: Option<NodeId>,
}

#[derive(Clone, Debug)]
pub enum NodeData {
    ArrayLiteralExpression(Box<ArrayLiteralExpressionData>),
    ArrayTypeNode(Box<ArrayTypeNodeData>),
    ArrowFunction(Box<ArrowFunctionData>),
    AsExpression(Box<AsExpressionData>),
    AwaitExpression(Box<AwaitExpressionData>),
    BigIntLiteral(Box<BigIntLiteralData>),
    BinaryExpression(Box<BinaryExpressionData>),
    BindingElement(Box<BindingElementData>),
    BindingPattern(Box<BindingPatternData>),
    Block(Box<BlockData>),
    BreakStatement(Box<BreakStatementData>),
    CallExpression(Box<CallExpressionData>),
    CallSignatureDeclaration(Box<CallSignatureDeclarationData>),
    CaseBlock(Box<CaseBlockData>),
    CaseOrDefaultClause(Box<CaseOrDefaultClauseData>),
    CatchClause(Box<CatchClauseData>),
    ClassDeclaration(Box<ClassDeclarationData>),
    ClassExpression(Box<ClassExpressionData>),
    ClassStaticBlockDeclaration(Box<ClassStaticBlockDeclarationData>),
    ComputedPropertyName(Box<ComputedPropertyNameData>),
    ConditionalExpression(Box<ConditionalExpressionData>),
    ConditionalTypeNode(Box<ConditionalTypeNodeData>),
    ConstructSignatureDeclaration(Box<ConstructSignatureDeclarationData>),
    ConstructorDeclaration(Box<ConstructorDeclarationData>),
    ConstructorTypeNode(Box<ConstructorTypeNodeData>),
    ContinueStatement(Box<ContinueStatementData>),
    DebuggerStatement(Box<DebuggerStatementData>),
    Decorator(Box<DecoratorData>),
    DeleteExpression(Box<DeleteExpressionData>),
    DoStatement(Box<DoStatementData>),
    ElementAccessExpression(Box<ElementAccessExpressionData>),
    EmptyStatement(Box<EmptyStatementData>),
    EnumDeclaration(Box<EnumDeclarationData>),
    EnumMember(Box<EnumMemberData>),
    ExportAssignment(Box<ExportAssignmentData>),
    ExportDeclaration(Box<ExportDeclarationData>),
    ExportSpecifier(Box<ExportSpecifierData>),
    ExpressionStatement(Box<ExpressionStatementData>),
    ExpressionWithTypeArguments(Box<ExpressionWithTypeArgumentsData>),
    ExternalModuleReference(Box<ExternalModuleReferenceData>),
    ForInOrOfStatement(Box<ForInOrOfStatementData>),
    ForStatement(Box<ForStatementData>),
    FunctionDeclaration(Box<FunctionDeclarationData>),
    FunctionExpression(Box<FunctionExpressionData>),
    FunctionTypeNode(Box<FunctionTypeNodeData>),
    GetAccessorDeclaration(Box<GetAccessorDeclarationData>),
    HeritageClause(Box<HeritageClauseData>),
    Identifier(Box<IdentifierData>),
    IfStatement(Box<IfStatementData>),
    ImportAttribute(Box<ImportAttributeData>),
    ImportAttributes(Box<ImportAttributesData>),
    ImportClause(Box<ImportClauseData>),
    ImportDeclaration(Box<ImportDeclarationData>),
    ImportEqualsDeclaration(Box<ImportEqualsDeclarationData>),
    ImportSpecifier(Box<ImportSpecifierData>),
    ImportTypeNode(Box<ImportTypeNodeData>),
    IndexSignatureDeclaration(Box<IndexSignatureDeclarationData>),
    IndexedAccessTypeNode(Box<IndexedAccessTypeNodeData>),
    InferTypeNode(Box<InferTypeNodeData>),
    InterfaceDeclaration(Box<InterfaceDeclarationData>),
    IntersectionTypeNode(Box<IntersectionTypeNodeData>),
    JsDoc(Box<JsDocData>),
    JsDocAllType(Box<JsDocAllTypeData>),
    JsDocAugmentsTag(Box<JsDocAugmentsTagData>),
    JsDocCallbackTag(Box<JsDocCallbackTagData>),
    JsDocDeprecatedTag(Box<JsDocDeprecatedTagData>),
    JsDocImplementsTag(Box<JsDocImplementsTagData>),
    JsDocImportTag(Box<JsDocImportTagData>),
    JsDocLink(Box<JsDocLinkData>),
    JsDocLinkCode(Box<JsDocLinkCodeData>),
    JsDocLinkPlain(Box<JsDocLinkPlainData>),
    JsDocNameReference(Box<JsDocNameReferenceData>),
    JsDocNonNullableType(Box<JsDocNonNullableTypeData>),
    JsDocNullableType(Box<JsDocNullableTypeData>),
    JsDocOptionalType(Box<JsDocOptionalTypeData>),
    JsDocOverloadTag(Box<JsDocOverloadTagData>),
    JsDocOverrideTag(Box<JsDocOverrideTagData>),
    JsDocParameterOrPropertyTag(Box<JsDocParameterOrPropertyTagData>),
    JsDocPrivateTag(Box<JsDocPrivateTagData>),
    JsDocProtectedTag(Box<JsDocProtectedTagData>),
    JsDocPublicTag(Box<JsDocPublicTagData>),
    JsDocReadonlyTag(Box<JsDocReadonlyTagData>),
    JsDocReturnTag(Box<JsDocReturnTagData>),
    JsDocSatisfiesTag(Box<JsDocSatisfiesTagData>),
    JsDocSeeTag(Box<JsDocSeeTagData>),
    JsDocSignature(Box<JsDocSignatureData>),
    JsDocTemplateTag(Box<JsDocTemplateTagData>),
    JsDocText(Box<JsDocTextData>),
    JsDocThisTag(Box<JsDocThisTagData>),
    JsDocThrowsTag(Box<JsDocThrowsTagData>),
    JsDocTypeExpression(Box<JsDocTypeExpressionData>),
    JsDocTypeLiteral(Box<JsDocTypeLiteralData>),
    JsDocTypeTag(Box<JsDocTypeTagData>),
    JsDocTypedefTag(Box<JsDocTypedefTagData>),
    JsDocUnknownTag(Box<JsDocUnknownTagData>),
    JsDocVariadicType(Box<JsDocVariadicTypeData>),
    JsxAttribute(Box<JsxAttributeData>),
    JsxAttributes(Box<JsxAttributesData>),
    JsxClosingElement(Box<JsxClosingElementData>),
    JsxClosingFragment(Box<JsxClosingFragmentData>),
    JsxElement(Box<JsxElementData>),
    JsxExpression(Box<JsxExpressionData>),
    JsxFragment(Box<JsxFragmentData>),
    JsxNamespacedName(Box<JsxNamespacedNameData>),
    JsxOpeningElement(Box<JsxOpeningElementData>),
    JsxOpeningFragment(Box<JsxOpeningFragmentData>),
    JsxSelfClosingElement(Box<JsxSelfClosingElementData>),
    JsxSpreadAttribute(Box<JsxSpreadAttributeData>),
    JsxText(Box<JsxTextData>),
    KeywordExpression(Box<KeywordExpressionData>),
    KeywordTypeNode(Box<KeywordTypeNodeData>),
    LabeledStatement(Box<LabeledStatementData>),
    LiteralTypeNode(Box<LiteralTypeNodeData>),
    MappedTypeNode(Box<MappedTypeNodeData>),
    MetaProperty(Box<MetaPropertyData>),
    MethodDeclaration(Box<MethodDeclarationData>),
    MethodSignatureDeclaration(Box<MethodSignatureDeclarationData>),
    MissingDeclaration(Box<MissingDeclarationData>),
    ModuleBlock(Box<ModuleBlockData>),
    ModuleDeclaration(Box<ModuleDeclarationData>),
    NamedExports(Box<NamedExportsData>),
    NamedImports(Box<NamedImportsData>),
    NamedTupleMember(Box<NamedTupleMemberData>),
    NamespaceExport(Box<NamespaceExportData>),
    NamespaceExportDeclaration(Box<NamespaceExportDeclarationData>),
    NamespaceImport(Box<NamespaceImportData>),
    NewExpression(Box<NewExpressionData>),
    NoSubstitutionTemplateLiteral(Box<NoSubstitutionTemplateLiteralData>),
    NonNullExpression(Box<NonNullExpressionData>),
    NotEmittedStatement(Box<NotEmittedStatementData>),
    NotEmittedTypeElement(Box<NotEmittedTypeElementData>),
    NumericLiteral(Box<NumericLiteralData>),
    ObjectLiteralExpression(Box<ObjectLiteralExpressionData>),
    OmittedExpression(Box<OmittedExpressionData>),
    OptionalTypeNode(Box<OptionalTypeNodeData>),
    ParameterDeclaration(Box<ParameterDeclarationData>),
    ParenthesizedExpression(Box<ParenthesizedExpressionData>),
    ParenthesizedTypeNode(Box<ParenthesizedTypeNodeData>),
    PartiallyEmittedExpression(Box<PartiallyEmittedExpressionData>),
    PostfixUnaryExpression(Box<PostfixUnaryExpressionData>),
    PrefixUnaryExpression(Box<PrefixUnaryExpressionData>),
    PrivateIdentifier(Box<PrivateIdentifierData>),
    PropertyAccessExpression(Box<PropertyAccessExpressionData>),
    PropertyAssignment(Box<PropertyAssignmentData>),
    PropertyDeclaration(Box<PropertyDeclarationData>),
    PropertySignatureDeclaration(Box<PropertySignatureDeclarationData>),
    QualifiedName(Box<QualifiedNameData>),
    RegularExpressionLiteral(Box<RegularExpressionLiteralData>),
    RestTypeNode(Box<RestTypeNodeData>),
    ReturnStatement(Box<ReturnStatementData>),
    SatisfiesExpression(Box<SatisfiesExpressionData>),
    SemicolonClassElement(Box<SemicolonClassElementData>),
    SetAccessorDeclaration(Box<SetAccessorDeclarationData>),
    ShorthandPropertyAssignment(Box<ShorthandPropertyAssignmentData>),
    SourceFile(Box<SourceFileData>),
    SpreadAssignment(Box<SpreadAssignmentData>),
    SpreadElement(Box<SpreadElementData>),
    StringLiteral(Box<StringLiteralData>),
    SwitchStatement(Box<SwitchStatementData>),
    SyntaxList(Box<SyntaxListData>),
    SyntheticExpression(Box<SyntheticExpressionData>),
    SyntheticReferenceExpression(Box<SyntheticReferenceExpressionData>),
    TaggedTemplateExpression(Box<TaggedTemplateExpressionData>),
    TemplateExpression(Box<TemplateExpressionData>),
    TemplateHead(Box<TemplateHeadData>),
    TemplateLiteralTypeNode(Box<TemplateLiteralTypeNodeData>),
    TemplateLiteralTypeSpan(Box<TemplateLiteralTypeSpanData>),
    TemplateMiddle(Box<TemplateMiddleData>),
    TemplateSpan(Box<TemplateSpanData>),
    TemplateTail(Box<TemplateTailData>),
    ThisTypeNode(Box<ThisTypeNodeData>),
    ThrowStatement(Box<ThrowStatementData>),
    Token(Box<TokenData>),
    TryStatement(Box<TryStatementData>),
    TupleTypeNode(Box<TupleTypeNodeData>),
    TypeAliasDeclaration(Box<TypeAliasDeclarationData>),
    TypeAssertion(Box<TypeAssertionData>),
    TypeLiteralNode(Box<TypeLiteralNodeData>),
    TypeOfExpression(Box<TypeOfExpressionData>),
    TypeOperatorNode(Box<TypeOperatorNodeData>),
    TypeParameterDeclaration(Box<TypeParameterDeclarationData>),
    TypePredicateNode(Box<TypePredicateNodeData>),
    TypeQueryNode(Box<TypeQueryNodeData>),
    TypeReferenceNode(Box<TypeReferenceNodeData>),
    UnionTypeNode(Box<UnionTypeNodeData>),
    VariableDeclaration(Box<VariableDeclarationData>),
    VariableDeclarationList(Box<VariableDeclarationListData>),
    VariableStatement(Box<VariableStatementData>),
    VoidExpression(Box<VoidExpressionData>),
    WhileStatement(Box<WhileStatementData>),
    WithStatement(Box<WithStatementData>),
    YieldExpression(Box<YieldExpressionData>),
}

impl NodeData {
    pub const SCHEMA_NODE_COUNT: usize = 192;
    pub const SCHEMA_BASE_COUNT: usize = 35;
    pub const SCHEMA_NODE_ALIAS_COUNT: usize = 72;
    pub const SCHEMA_LIST_ALIAS_COUNT: usize = 23;

    #[must_use]
    #[allow(clippy::too_many_lines)]
    pub const fn schema_name(&self) -> &'static str {
        match self {
            Self::ArrayLiteralExpression(..) => "ArrayLiteralExpression",
            Self::ArrayTypeNode(..) => "ArrayTypeNode",
            Self::ArrowFunction(..) => "ArrowFunction",
            Self::AsExpression(..) => "AsExpression",
            Self::AwaitExpression(..) => "AwaitExpression",
            Self::BigIntLiteral(..) => "BigIntLiteral",
            Self::BinaryExpression(..) => "BinaryExpression",
            Self::BindingElement(..) => "BindingElement",
            Self::BindingPattern(..) => "BindingPattern",
            Self::Block(..) => "Block",
            Self::BreakStatement(..) => "BreakStatement",
            Self::CallExpression(..) => "CallExpression",
            Self::CallSignatureDeclaration(..) => "CallSignatureDeclaration",
            Self::CaseBlock(..) => "CaseBlock",
            Self::CaseOrDefaultClause(..) => "CaseOrDefaultClause",
            Self::CatchClause(..) => "CatchClause",
            Self::ClassDeclaration(..) => "ClassDeclaration",
            Self::ClassExpression(..) => "ClassExpression",
            Self::ClassStaticBlockDeclaration(..) => "ClassStaticBlockDeclaration",
            Self::ComputedPropertyName(..) => "ComputedPropertyName",
            Self::ConditionalExpression(..) => "ConditionalExpression",
            Self::ConditionalTypeNode(..) => "ConditionalTypeNode",
            Self::ConstructSignatureDeclaration(..) => "ConstructSignatureDeclaration",
            Self::ConstructorDeclaration(..) => "ConstructorDeclaration",
            Self::ConstructorTypeNode(..) => "ConstructorTypeNode",
            Self::ContinueStatement(..) => "ContinueStatement",
            Self::DebuggerStatement(..) => "DebuggerStatement",
            Self::Decorator(..) => "Decorator",
            Self::DeleteExpression(..) => "DeleteExpression",
            Self::DoStatement(..) => "DoStatement",
            Self::ElementAccessExpression(..) => "ElementAccessExpression",
            Self::EmptyStatement(..) => "EmptyStatement",
            Self::EnumDeclaration(..) => "EnumDeclaration",
            Self::EnumMember(..) => "EnumMember",
            Self::ExportAssignment(..) => "ExportAssignment",
            Self::ExportDeclaration(..) => "ExportDeclaration",
            Self::ExportSpecifier(..) => "ExportSpecifier",
            Self::ExpressionStatement(..) => "ExpressionStatement",
            Self::ExpressionWithTypeArguments(..) => "ExpressionWithTypeArguments",
            Self::ExternalModuleReference(..) => "ExternalModuleReference",
            Self::ForInOrOfStatement(..) => "ForInOrOfStatement",
            Self::ForStatement(..) => "ForStatement",
            Self::FunctionDeclaration(..) => "FunctionDeclaration",
            Self::FunctionExpression(..) => "FunctionExpression",
            Self::FunctionTypeNode(..) => "FunctionTypeNode",
            Self::GetAccessorDeclaration(..) => "GetAccessorDeclaration",
            Self::HeritageClause(..) => "HeritageClause",
            Self::Identifier(..) => "Identifier",
            Self::IfStatement(..) => "IfStatement",
            Self::ImportAttribute(..) => "ImportAttribute",
            Self::ImportAttributes(..) => "ImportAttributes",
            Self::ImportClause(..) => "ImportClause",
            Self::ImportDeclaration(..) => "ImportDeclaration",
            Self::ImportEqualsDeclaration(..) => "ImportEqualsDeclaration",
            Self::ImportSpecifier(..) => "ImportSpecifier",
            Self::ImportTypeNode(..) => "ImportTypeNode",
            Self::IndexSignatureDeclaration(..) => "IndexSignatureDeclaration",
            Self::IndexedAccessTypeNode(..) => "IndexedAccessTypeNode",
            Self::InferTypeNode(..) => "InferTypeNode",
            Self::InterfaceDeclaration(..) => "InterfaceDeclaration",
            Self::IntersectionTypeNode(..) => "IntersectionTypeNode",
            Self::JsDoc(..) => "JSDoc",
            Self::JsDocAllType(..) => "JSDocAllType",
            Self::JsDocAugmentsTag(..) => "JSDocAugmentsTag",
            Self::JsDocCallbackTag(..) => "JSDocCallbackTag",
            Self::JsDocDeprecatedTag(..) => "JSDocDeprecatedTag",
            Self::JsDocImplementsTag(..) => "JSDocImplementsTag",
            Self::JsDocImportTag(..) => "JSDocImportTag",
            Self::JsDocLink(..) => "JSDocLink",
            Self::JsDocLinkCode(..) => "JSDocLinkCode",
            Self::JsDocLinkPlain(..) => "JSDocLinkPlain",
            Self::JsDocNameReference(..) => "JSDocNameReference",
            Self::JsDocNonNullableType(..) => "JSDocNonNullableType",
            Self::JsDocNullableType(..) => "JSDocNullableType",
            Self::JsDocOptionalType(..) => "JSDocOptionalType",
            Self::JsDocOverloadTag(..) => "JSDocOverloadTag",
            Self::JsDocOverrideTag(..) => "JSDocOverrideTag",
            Self::JsDocParameterOrPropertyTag(..) => "JSDocParameterOrPropertyTag",
            Self::JsDocPrivateTag(..) => "JSDocPrivateTag",
            Self::JsDocProtectedTag(..) => "JSDocProtectedTag",
            Self::JsDocPublicTag(..) => "JSDocPublicTag",
            Self::JsDocReadonlyTag(..) => "JSDocReadonlyTag",
            Self::JsDocReturnTag(..) => "JSDocReturnTag",
            Self::JsDocSatisfiesTag(..) => "JSDocSatisfiesTag",
            Self::JsDocSeeTag(..) => "JSDocSeeTag",
            Self::JsDocSignature(..) => "JSDocSignature",
            Self::JsDocTemplateTag(..) => "JSDocTemplateTag",
            Self::JsDocText(..) => "JSDocText",
            Self::JsDocThisTag(..) => "JSDocThisTag",
            Self::JsDocThrowsTag(..) => "JSDocThrowsTag",
            Self::JsDocTypeExpression(..) => "JSDocTypeExpression",
            Self::JsDocTypeLiteral(..) => "JSDocTypeLiteral",
            Self::JsDocTypeTag(..) => "JSDocTypeTag",
            Self::JsDocTypedefTag(..) => "JSDocTypedefTag",
            Self::JsDocUnknownTag(..) => "JSDocUnknownTag",
            Self::JsDocVariadicType(..) => "JSDocVariadicType",
            Self::JsxAttribute(..) => "JsxAttribute",
            Self::JsxAttributes(..) => "JsxAttributes",
            Self::JsxClosingElement(..) => "JsxClosingElement",
            Self::JsxClosingFragment(..) => "JsxClosingFragment",
            Self::JsxElement(..) => "JsxElement",
            Self::JsxExpression(..) => "JsxExpression",
            Self::JsxFragment(..) => "JsxFragment",
            Self::JsxNamespacedName(..) => "JsxNamespacedName",
            Self::JsxOpeningElement(..) => "JsxOpeningElement",
            Self::JsxOpeningFragment(..) => "JsxOpeningFragment",
            Self::JsxSelfClosingElement(..) => "JsxSelfClosingElement",
            Self::JsxSpreadAttribute(..) => "JsxSpreadAttribute",
            Self::JsxText(..) => "JsxText",
            Self::KeywordExpression(..) => "KeywordExpression",
            Self::KeywordTypeNode(..) => "KeywordTypeNode",
            Self::LabeledStatement(..) => "LabeledStatement",
            Self::LiteralTypeNode(..) => "LiteralTypeNode",
            Self::MappedTypeNode(..) => "MappedTypeNode",
            Self::MetaProperty(..) => "MetaProperty",
            Self::MethodDeclaration(..) => "MethodDeclaration",
            Self::MethodSignatureDeclaration(..) => "MethodSignatureDeclaration",
            Self::MissingDeclaration(..) => "MissingDeclaration",
            Self::ModuleBlock(..) => "ModuleBlock",
            Self::ModuleDeclaration(..) => "ModuleDeclaration",
            Self::NamedExports(..) => "NamedExports",
            Self::NamedImports(..) => "NamedImports",
            Self::NamedTupleMember(..) => "NamedTupleMember",
            Self::NamespaceExport(..) => "NamespaceExport",
            Self::NamespaceExportDeclaration(..) => "NamespaceExportDeclaration",
            Self::NamespaceImport(..) => "NamespaceImport",
            Self::NewExpression(..) => "NewExpression",
            Self::NoSubstitutionTemplateLiteral(..) => "NoSubstitutionTemplateLiteral",
            Self::NonNullExpression(..) => "NonNullExpression",
            Self::NotEmittedStatement(..) => "NotEmittedStatement",
            Self::NotEmittedTypeElement(..) => "NotEmittedTypeElement",
            Self::NumericLiteral(..) => "NumericLiteral",
            Self::ObjectLiteralExpression(..) => "ObjectLiteralExpression",
            Self::OmittedExpression(..) => "OmittedExpression",
            Self::OptionalTypeNode(..) => "OptionalTypeNode",
            Self::ParameterDeclaration(..) => "ParameterDeclaration",
            Self::ParenthesizedExpression(..) => "ParenthesizedExpression",
            Self::ParenthesizedTypeNode(..) => "ParenthesizedTypeNode",
            Self::PartiallyEmittedExpression(..) => "PartiallyEmittedExpression",
            Self::PostfixUnaryExpression(..) => "PostfixUnaryExpression",
            Self::PrefixUnaryExpression(..) => "PrefixUnaryExpression",
            Self::PrivateIdentifier(..) => "PrivateIdentifier",
            Self::PropertyAccessExpression(..) => "PropertyAccessExpression",
            Self::PropertyAssignment(..) => "PropertyAssignment",
            Self::PropertyDeclaration(..) => "PropertyDeclaration",
            Self::PropertySignatureDeclaration(..) => "PropertySignatureDeclaration",
            Self::QualifiedName(..) => "QualifiedName",
            Self::RegularExpressionLiteral(..) => "RegularExpressionLiteral",
            Self::RestTypeNode(..) => "RestTypeNode",
            Self::ReturnStatement(..) => "ReturnStatement",
            Self::SatisfiesExpression(..) => "SatisfiesExpression",
            Self::SemicolonClassElement(..) => "SemicolonClassElement",
            Self::SetAccessorDeclaration(..) => "SetAccessorDeclaration",
            Self::ShorthandPropertyAssignment(..) => "ShorthandPropertyAssignment",
            Self::SourceFile(..) => "SourceFile",
            Self::SpreadAssignment(..) => "SpreadAssignment",
            Self::SpreadElement(..) => "SpreadElement",
            Self::StringLiteral(..) => "StringLiteral",
            Self::SwitchStatement(..) => "SwitchStatement",
            Self::SyntaxList(..) => "SyntaxList",
            Self::SyntheticExpression(..) => "SyntheticExpression",
            Self::SyntheticReferenceExpression(..) => "SyntheticReferenceExpression",
            Self::TaggedTemplateExpression(..) => "TaggedTemplateExpression",
            Self::TemplateExpression(..) => "TemplateExpression",
            Self::TemplateHead(..) => "TemplateHead",
            Self::TemplateLiteralTypeNode(..) => "TemplateLiteralTypeNode",
            Self::TemplateLiteralTypeSpan(..) => "TemplateLiteralTypeSpan",
            Self::TemplateMiddle(..) => "TemplateMiddle",
            Self::TemplateSpan(..) => "TemplateSpan",
            Self::TemplateTail(..) => "TemplateTail",
            Self::ThisTypeNode(..) => "ThisTypeNode",
            Self::ThrowStatement(..) => "ThrowStatement",
            Self::Token(..) => "Token",
            Self::TryStatement(..) => "TryStatement",
            Self::TupleTypeNode(..) => "TupleTypeNode",
            Self::TypeAliasDeclaration(..) => "TypeAliasDeclaration",
            Self::TypeAssertion(..) => "TypeAssertion",
            Self::TypeLiteralNode(..) => "TypeLiteralNode",
            Self::TypeOfExpression(..) => "TypeOfExpression",
            Self::TypeOperatorNode(..) => "TypeOperatorNode",
            Self::TypeParameterDeclaration(..) => "TypeParameterDeclaration",
            Self::TypePredicateNode(..) => "TypePredicateNode",
            Self::TypeQueryNode(..) => "TypeQueryNode",
            Self::TypeReferenceNode(..) => "TypeReferenceNode",
            Self::UnionTypeNode(..) => "UnionTypeNode",
            Self::VariableDeclaration(..) => "VariableDeclaration",
            Self::VariableDeclarationList(..) => "VariableDeclarationList",
            Self::VariableStatement(..) => "VariableStatement",
            Self::VoidExpression(..) => "VoidExpression",
            Self::WhileStatement(..) => "WhileStatement",
            Self::WithStatement(..) => "WithStatement",
            Self::YieldExpression(..) => "YieldExpression",
        }
    }
}

pub type ArrayLiteralExpressionNode = NodeId;
pub type ArrayTypeNodeNode = NodeId;
pub type ArrowFunctionNode = NodeId;
pub type AsExpressionNode = NodeId;
pub type AwaitExpressionNode = NodeId;
pub type BigIntLiteralNode = NodeId;
pub type BinaryExpressionNode = NodeId;
pub type BindingElementNode = NodeId;
pub type BindingPatternNode = NodeId;
pub type BlockNode = NodeId;
pub type BreakStatementNode = NodeId;
pub type CallExpressionNode = NodeId;
pub type CallSignatureDeclarationNode = NodeId;
pub type CaseBlockNode = NodeId;
pub type CaseOrDefaultClauseNode = NodeId;
pub type CatchClauseNode = NodeId;
pub type ClassDeclarationNode = NodeId;
pub type ClassExpressionNode = NodeId;
pub type ClassStaticBlockDeclarationNode = NodeId;
pub type ComputedPropertyNameNode = NodeId;
pub type ConditionalExpressionNode = NodeId;
pub type ConditionalTypeNodeNode = NodeId;
pub type ConstructSignatureDeclarationNode = NodeId;
pub type ConstructorDeclarationNode = NodeId;
pub type ConstructorTypeNodeNode = NodeId;
pub type ContinueStatementNode = NodeId;
pub type DebuggerStatementNode = NodeId;
pub type DecoratorNode = NodeId;
pub type DeleteExpressionNode = NodeId;
pub type DoStatementNode = NodeId;
pub type ElementAccessExpressionNode = NodeId;
pub type EmptyStatementNode = NodeId;
pub type EnumDeclarationNode = NodeId;
pub type EnumMemberNode = NodeId;
pub type ExportAssignmentNode = NodeId;
pub type ExportDeclarationNode = NodeId;
pub type ExportSpecifierNode = NodeId;
pub type ExpressionStatementNode = NodeId;
pub type ExpressionWithTypeArgumentsNode = NodeId;
pub type ExternalModuleReferenceNode = NodeId;
pub type ForInOrOfStatementNode = NodeId;
pub type ForStatementNode = NodeId;
pub type FunctionDeclarationNode = NodeId;
pub type FunctionExpressionNode = NodeId;
pub type FunctionTypeNodeNode = NodeId;
pub type GetAccessorDeclarationNode = NodeId;
pub type HeritageClauseNode = NodeId;
pub type IdentifierNode = NodeId;
pub type IfStatementNode = NodeId;
pub type ImportAttributeNode = NodeId;
pub type ImportAttributesNode = NodeId;
pub type ImportClauseNode = NodeId;
pub type ImportDeclarationNode = NodeId;
pub type ImportEqualsDeclarationNode = NodeId;
pub type ImportSpecifierNode = NodeId;
pub type ImportTypeNodeNode = NodeId;
pub type IndexSignatureDeclarationNode = NodeId;
pub type IndexedAccessTypeNodeNode = NodeId;
pub type InferTypeNodeNode = NodeId;
pub type InterfaceDeclarationNode = NodeId;
pub type IntersectionTypeNodeNode = NodeId;
pub type JsDocNode = NodeId;
pub type JsDocAllTypeNode = NodeId;
pub type JsDocAugmentsTagNode = NodeId;
pub type JsDocCallbackTagNode = NodeId;
pub type JsDocDeprecatedTagNode = NodeId;
pub type JsDocImplementsTagNode = NodeId;
pub type JsDocImportTagNode = NodeId;
pub type JsDocLinkNode = NodeId;
pub type JsDocLinkCodeNode = NodeId;
pub type JsDocLinkPlainNode = NodeId;
pub type JsDocNameReferenceNode = NodeId;
pub type JsDocNonNullableTypeNode = NodeId;
pub type JsDocNullableTypeNode = NodeId;
pub type JsDocOptionalTypeNode = NodeId;
pub type JsDocOverloadTagNode = NodeId;
pub type JsDocOverrideTagNode = NodeId;
pub type JsDocParameterOrPropertyTagNode = NodeId;
pub type JsDocPrivateTagNode = NodeId;
pub type JsDocProtectedTagNode = NodeId;
pub type JsDocPublicTagNode = NodeId;
pub type JsDocReadonlyTagNode = NodeId;
pub type JsDocReturnTagNode = NodeId;
pub type JsDocSatisfiesTagNode = NodeId;
pub type JsDocSeeTagNode = NodeId;
pub type JsDocSignatureNode = NodeId;
pub type JsDocTemplateTagNode = NodeId;
pub type JsDocTextNode = NodeId;
pub type JsDocThisTagNode = NodeId;
pub type JsDocThrowsTagNode = NodeId;
pub type JsDocTypeExpressionNode = NodeId;
pub type JsDocTypeLiteralNode = NodeId;
pub type JsDocTypeTagNode = NodeId;
pub type JsDocTypedefTagNode = NodeId;
pub type JsDocUnknownTagNode = NodeId;
pub type JsDocVariadicTypeNode = NodeId;
pub type JsxAttributeNode = NodeId;
pub type JsxAttributesNode = NodeId;
pub type JsxClosingElementNode = NodeId;
pub type JsxClosingFragmentNode = NodeId;
pub type JsxElementNode = NodeId;
pub type JsxExpressionNode = NodeId;
pub type JsxFragmentNode = NodeId;
pub type JsxNamespacedNameNode = NodeId;
pub type JsxOpeningElementNode = NodeId;
pub type JsxOpeningFragmentNode = NodeId;
pub type JsxSelfClosingElementNode = NodeId;
pub type JsxSpreadAttributeNode = NodeId;
pub type JsxTextNode = NodeId;
pub type KeywordExpressionNode = NodeId;
pub type KeywordTypeNodeNode = NodeId;
pub type LabeledStatementNode = NodeId;
pub type LiteralTypeNodeNode = NodeId;
pub type MappedTypeNodeNode = NodeId;
pub type MetaPropertyNode = NodeId;
pub type MethodDeclarationNode = NodeId;
pub type MethodSignatureDeclarationNode = NodeId;
pub type MissingDeclarationNode = NodeId;
pub type ModuleBlockNode = NodeId;
pub type ModuleDeclarationNode = NodeId;
pub type NamedExportsNode = NodeId;
pub type NamedImportsNode = NodeId;
pub type NamedTupleMemberNode = NodeId;
pub type NamespaceExportNode = NodeId;
pub type NamespaceExportDeclarationNode = NodeId;
pub type NamespaceImportNode = NodeId;
pub type NewExpressionNode = NodeId;
pub type NoSubstitutionTemplateLiteralNode = NodeId;
pub type NonNullExpressionNode = NodeId;
pub type NotEmittedStatementNode = NodeId;
pub type NotEmittedTypeElementNode = NodeId;
pub type NumericLiteralNode = NodeId;
pub type ObjectLiteralExpressionNode = NodeId;
pub type OmittedExpressionNode = NodeId;
pub type OptionalTypeNodeNode = NodeId;
pub type ParameterDeclarationNode = NodeId;
pub type ParenthesizedExpressionNode = NodeId;
pub type ParenthesizedTypeNodeNode = NodeId;
pub type PartiallyEmittedExpressionNode = NodeId;
pub type PostfixUnaryExpressionNode = NodeId;
pub type PrefixUnaryExpressionNode = NodeId;
pub type PrivateIdentifierNode = NodeId;
pub type PropertyAccessExpressionNode = NodeId;
pub type PropertyAssignmentNode = NodeId;
pub type PropertyDeclarationNode = NodeId;
pub type PropertySignatureDeclarationNode = NodeId;
pub type QualifiedNameNode = NodeId;
pub type RegularExpressionLiteralNode = NodeId;
pub type RestTypeNodeNode = NodeId;
pub type ReturnStatementNode = NodeId;
pub type SatisfiesExpressionNode = NodeId;
pub type SemicolonClassElementNode = NodeId;
pub type SetAccessorDeclarationNode = NodeId;
pub type ShorthandPropertyAssignmentNode = NodeId;
pub type SourceFileNode = NodeId;
pub type SpreadAssignmentNode = NodeId;
pub type SpreadElementNode = NodeId;
pub type StringLiteralNode = NodeId;
pub type SwitchStatementNode = NodeId;
pub type SyntaxListNode = NodeId;
pub type SyntheticExpressionNode = NodeId;
pub type SyntheticReferenceExpressionNode = NodeId;
pub type TaggedTemplateExpressionNode = NodeId;
pub type TemplateExpressionNode = NodeId;
pub type TemplateHeadNode = NodeId;
pub type TemplateLiteralTypeNodeNode = NodeId;
pub type TemplateLiteralTypeSpanNode = NodeId;
pub type TemplateMiddleNode = NodeId;
pub type TemplateSpanNode = NodeId;
pub type TemplateTailNode = NodeId;
pub type ThisTypeNodeNode = NodeId;
pub type ThrowStatementNode = NodeId;
pub type TokenNode = NodeId;
pub type TryStatementNode = NodeId;
pub type TupleTypeNodeNode = NodeId;
pub type TypeAliasDeclarationNode = NodeId;
pub type TypeAssertionNode = NodeId;
pub type TypeLiteralNodeNode = NodeId;
pub type TypeOfExpressionNode = NodeId;
pub type TypeOperatorNodeNode = NodeId;
pub type TypeParameterDeclarationNode = NodeId;
pub type TypePredicateNodeNode = NodeId;
pub type TypeQueryNodeNode = NodeId;
pub type TypeReferenceNodeNode = NodeId;
pub type UnionTypeNodeNode = NodeId;
pub type VariableDeclarationNode = NodeId;
pub type VariableDeclarationListNode = NodeId;
pub type VariableStatementNode = NodeId;
pub type VoidExpressionNode = NodeId;
pub type WhileStatementNode = NodeId;
pub type WithStatementNode = NodeId;
pub type YieldExpressionNode = NodeId;
pub type AccessExpression = NodeId;
pub type AccessorDeclaration = NodeId;
pub type AnyImportSyntax = NodeId;
pub type ArrayBindingElement = NodeId;
pub type ArrayDestructuringAssignment = NodeId;
pub type AssertionExpression = NodeId;
pub type BindingName = NodeId;
pub type BlockOrExpression = NodeId;
pub type BooleanLiteral = NodeId;
pub type BreakOrContinueStatement = NodeId;
pub type CallLikeExpression = NodeId;
pub type CallOrNewExpression = NodeId;
pub type ClassElement = NodeId;
pub type ClassLikeDeclaration = NodeId;
pub type ConciseBody = NodeId;
pub type Declaration = NodeId;
pub type DeclarationName = NodeId;
pub type DestructuringAssignment = NodeId;
pub type EntityName = NodeId;
pub type Expression = NodeId;
pub type ForInitializer = NodeId;
pub type FunctionBody = NodeId;
pub type FunctionLikeDeclaration = NodeId;
pub type ImportAttributeName = NodeId;
pub type ImportClauseOrBindingPattern = NodeId;
pub type IncrementExpression = NodeId;
pub type JsDocComment = NodeId;
pub type JsDocFullName = NodeId;
pub type JsDocTag = NodeId;
pub type JsxAttributeLike = NodeId;
pub type JsxAttributeName = NodeId;
pub type JsxAttributeValue = NodeId;
pub type JsxChild = NodeId;
pub type JsxOpeningLikeElement = NodeId;
pub type JsxTagNameExpression = NodeId;
pub type LeftHandSideExpression = NodeId;
pub type LiteralExpression = NodeId;
pub type LiteralLikeNode = NodeId;
pub type LiteralToken = NodeId;
pub type MemberName = NodeId;
pub type Modifier = NodeId;
pub type ModifierLike = NodeId;
pub type ModuleBody = NodeId;
pub type ModuleExportName = NodeId;
pub type ModuleName = NodeId;
pub type ModuleReference = NodeId;
pub type NamedExportBindings = NodeId;
pub type NamedImportBindings = NodeId;
pub type NamedImportsOrExports = NodeId;
pub type NodeBody = NodeId;
pub type NumericOrStringLikeLiteral = NodeId;
pub type ObjectDestructuringAssignment = NodeId;
pub type ObjectLiteralElement = NodeId;
pub type ObjectLiteralElementLike = NodeId;
pub type ObjectLiteralLikeNode = NodeId;
pub type ObjectTypeDeclaration = NodeId;
pub type PropertyName = NodeId;
pub type PropertyNameLiteral = NodeId;
pub type PseudoLiteralToken = NodeId;
pub type SignatureDeclaration = NodeId;
pub type Statement = NodeId;
pub type StringLiteralLikeNode = NodeId;
pub type TemplateLiteral = NodeId;
pub type TemplateLiteralLikeNode = NodeId;
pub type TemplateLiteralToken = NodeId;
pub type TemplateMiddleOrTail = NodeId;
pub type TypeElement = NodeId;
pub type TypeNode = NodeId;
pub type TypePredicateParameterName = NodeId;
pub type UnionOrIntersectionTypeNode = NodeId;
pub type VariableOrParameterDeclaration = NodeId;
pub type VariableOrPropertyDeclaration = NodeId;
pub type ArgumentList = NodeList;
pub type BindingElementList = NodeList;
pub type CaseClausesList = NodeList;
pub type ClassElementList = NodeList;
pub type ElementList = NodeList;
pub type EnumMemberList = NodeList;
pub type ExportSpecifierList = NodeList;
pub type ExpressionWithTypeArgumentsList = NodeList;
pub type HeritageClauseList = NodeList;
pub type ImportAttributeList = NodeList;
pub type ImportSpecifierList = NodeList;
pub type JsxAttributeList = NodeList;
pub type JsxChildList = NodeList;
pub type ParameterList = NodeList;
pub type PropertyDefinitionList = NodeList;
pub type StatementList = NodeList;
pub type TemplateLiteralTypeSpanList = NodeList;
pub type TemplateSpanList = NodeList;
pub type TypeArgumentList = NodeList;
pub type TypeElementList = NodeList;
pub type TypeList = NodeList;
pub type TypeParameterList = NodeList;
pub type VariableDeclarationNodeList = NodeList;
