[package]
name = "ts_cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "tsgo"
path = "src/main.rs"

[dependencies]
ts_ast = { path = "../ts_ast" }
ts_compiler = { path = "../ts_compiler" }
ts_config = { path = "../ts_config" }
ts_diagnostic_writer = { path = "../ts_diagnostic_writer" }
ts_lsp = { path = "../ts_lsp" }
ts_module = { path = "../ts_module" }
ts_options = { path = "../ts_options" }
ts_parser = { path = "../ts_parser" }
ts_project = { path = "../ts_project" }
ts_scanner = { path = "../ts_scanner" }
ts_vfs = { path = "../ts_vfs" }
ts_watch = { path = "../ts_watch" }

[lints]
workspace = true
