[package]
name = "ts_printer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ts_ast = { path = "../ts_ast" }
ts_options = { path = "../ts_options" }
ts_sourcemap = { path = "../ts_sourcemap" }

[dev-dependencies]
ts_parser = { path = "../ts_parser" }

[lints]
workspace = true
