use std::{env, fmt::Write as _, fs, path::PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap());
    let library_directory = manifest.join("libs");
    println!("cargo:rerun-if-changed={}", library_directory.display());
    let mut names: Vec<_> = fs::read_dir(&library_directory)
        .unwrap()
        .map(|entry| entry.unwrap().file_name().into_string().unwrap())
        .filter(|name| name.ends_with(".d.ts"))
        .collect();
    names.sort();

    let mut generated =
        String::from("// Generated by build.rs.\n\npub static LIBRARIES: &[(&str, &str)] = &[\n");
    for name in names {
        writeln!(
            generated,
            "    ({name:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/libs/{name}\"))),"
        )
        .unwrap();
    }
    generated.push_str("];\n");
    let output = PathBuf::from(env::var_os("OUT_DIR").unwrap()).join("libraries.rs");
    fs::write(output, generated).unwrap();
}
