[package]
name = "ts_compiler"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ts_binder = { path = "../ts_binder" }
ts_bundled = { path = "../ts_bundled" }
ts_checker = { path = "../ts_checker" }
ts_ast = { path = "../ts_ast" }
ts_config = { path = "../ts_config" }
ts_core = { path = "../ts_core" }
ts_diagnostics = { path = "../ts_diagnostics" }
ts_glob = { path = "../ts_glob" }
ts_module = { path = "../ts_module" }
ts_options = { path = "../ts_options" }
ts_outputpaths = { path = "../ts_outputpaths" }
ts_parser = { path = "../ts_parser" }
ts_path = { path = "../ts_path" }
ts_printer = { path = "../ts_printer" }
ts_sourcemap = { path = "../ts_sourcemap" }
ts_vfs = { path = "../ts_vfs" }

[lints]
workspace = true
