[package]
name = "ts_watch"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ts_compiler = { path = "../ts_compiler" }
ts_fswatch = { path = "../ts_fswatch" }

[dev-dependencies]
ts_module = { path = "../ts_module" }
ts_vfs = { path = "../ts_vfs" }

[lints]
workspace = true
